### ISSUE TITLE
Some users seeing start page too often

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2344] opened 2019-04-04 19:05 UTC
We've had 3 separate reports in the past couple of weeks about people seeing the "Thanks for installing Privacy Badger" page every time they open their browser, all using Firefox. Two of those people have said they routinely clear cookies when they close the browser.

Privacy Badger stores booleans tracking whether (1) this is the first time it's been run (`isFirstRun`), (2) it should show the start-up page (`showIntroPage`), and (3) it should show the "comic" nag in the pop-up (`seenComic`). All of these are in the [settings_map](https://github.com/EFForg/privacybadger/blob/d9207dd9a2dc9b684f307993920930280fa5d820/src/js/background.js#L493), saved to local storage. Generally, Firefox's [Clear Cookies and Site Data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox) feature doesn't clear extension data (according to my own tests), but it's possible there's a bug or that the behavior varies by version/platform.

Need to do some more investigation to figure out what's going on, but creating this issue to track future developments.

**Comment by bcyphers** [comment] 2019-04-18 03:35
@jalcine, we just got another report about this behavior, which didn't give us any information that we didn't already know. Would you mind trying to figure out why this is happening?

**Comment by bcyphers** [comment] 2019-04-22 17:44
Got another couple of reports over the weekend. I'll spend some time trying to reproduce today.

**Comment by bcyphers** [comment] 2019-04-22 22:47
Worth noting that one of our reporters said the same thing is happening for other extensions, as well. Might be worth reaching out to Mozilla as well to see if they know something we don't.

**Comment by ghostwords** [comment] 2019-05-14 16:10
This might be caused by [Firefox bug 1313401: "Background Page LocalStorage is cleared along with site storage"](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401).

**Comment by ghostwords** [comment] 2019-05-15 16:22
As this is a (probably IndexedDB-related) bug in Firefox, other extensions run into the same problem ([uMatrix](https://github.com/uBlockOrigin/uMatrix-issues/issues/129), [uBlock Origin](https://github.com/uBlockOrigin/uBlock-issues/issues/176)).

**Comment by ghostwords** [comment] 2019-08-06 19:32
Haven't gotten any new reports recently, closing.

**Closed by ghostwords** 2019-08-06 19:32 UTC
Labels: Firefox, bug, wontfix
