### ISSUE TITLE
Nanovisor loading potential tracking around privacy badger

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadger#1044] opened 2016-12-12 19:29 UTC
@alexristich 
this is in relation to
https://github.com/EFForg/privacybadger/issues/1018
comment no 4 of above thread
firstly googleadservices or doubleclick ads are loaded though logger doesn't show entry of that....
after right click> inspect page>console ,page reloads and all ads are gone????
why they are not blocked previously(before reaching inspect page>console)...
is it like the way pb works
https://www.dropbox.com/s/z39esviabxca6pf/Dec%2013%202016%2012-41%20AM.webm?dl=0

**Comment by terrorist96** [comment] 2016-12-12 19:57
I can confirm that I do see ads on both nationalpost and chicagotribune, even with PB, ABP, Ghostery all installed.

**Comment by cooperq** [comment] 2016-12-12 20:02
Well then this confirms that they are either using first party ads or
have some adblocker circumvention. (likely web sockets)

**Comment by ghajini** [comment] 2016-12-12 20:05
@cooperq
After clicking Ctrl+shift+J 
Reload of page occur automatically
All ads are gone and pb blocks those ads....
It requires development console to trigger to hide that ads

**Comment by ghostwords** [comment] 2016-12-12 20:35
Looks like it's using a product called [Nanovisor](https://www.instartlogic.com/technology/end-to-end-platform/nanovisor). Also used by `weather.com`, `nasdaq.com`, `boston.com`, ...

**Comment by ghajini** [comment] 2016-12-21 12:58
Looks like some interactive discussion taking place here
https://github.com/uBlockOrigin/uAssets/issues/227
about Chicago tribune.com 
g00 crap
Instart logic's code

**Comment by ghajini** [comment] 2017-01-05 19:22
@cooperq any suggestions

**Comment by pde** [comment] 2017-03-24 07:11
If these were web sockets, there is now an API we can use to block them:

https://bugs.chromium.org/p/chromium/issues/detail?id=129353

**Comment by ghajini** [comment] 2017-03-25 09:06
@pde, @cooperq @alexristich  using chrome 59
still see ads....they are using scripts to push ads not the websocket

**Comment by ghajini** [comment] 2017-03-27 20:14
nanovisor code is changing day by day,,,how can privacy badger solves this....they have bypassed ublock 3 times....really need help @cooperq

**Comment by ghajini** [comment] 2017-08-12 04:32
Hey pb people.....***are  you give up on this issue?***
Instart logic rocking nowadays except ublock origin who is countering them

**Comment by cowlicks** [comment] 2017-08-14 19:35
@ghajini assigning to myself, I'll take a look sometime  this week

**Comment by ghajini** [comment] 2018-08-23 12:37
@ghostwords
Now that IL bug in privacy badger makes pb extension tracking extension.... almost 1 year passed

**Comment by ghostwords** [comment] 2018-08-23 13:03
It's a matter of prioritization. This seems like a niche situation without a straightforward workaround. Until something changes, I recommend using uBlock Origin on Firefox (Chrome does not support [request content filtering](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/StreamFilter)) to defeat this particular tracker.

**Comment by ghostwords** [comment] 2020-11-06 17:55
[Instart](https://en.wikipedia.org/wiki/Instart) was [acquired by Akamai](https://www.akamai.com/us/en/about/news/press/2020-press/akamai-technologies-acquires-customers-and-select-intellectual-property-from-instart.jsp).

**Closed by ghostwords** 2020-11-06 17:55 UTC
Labels: enhancement, heuristic
