### ISSUE TITLE
Spotify Player widget replacement crashes Discord

### ISSUE THREAD

**Issue by P-vh** [EFForg/privacybadger#2539] opened 2020-01-15 07:37 UTC
What is your browser and browser version?
Mozilla Firefox 72.0.1 (64-bit)

What is broken and where?
Privacy badger blocks Spotify's embeded widget on Discord web client, as intended.
But when you scroll past the blocked Spotify's embeded widget it crashes Discord.

What is the "culprit" domain?
open.spotify.com

What is your debug output for this domain?

```
**** ACTION_MAP for spotify.com
spotify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
api.spotify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579203028666
}
open.spotify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579556511535
}
**** SNITCH_MAP for spotify.com
spotify.com [
  "reddit.com",
  "withspotify.com",
  "twitter.com"
]
```

**Comment by ghostwords** [comment] 2020-01-15 14:54
Hello and thanks for reporting this problem! Does the problem go away if you disable replacement for Spotify (under the Widget Replacement tab on the options page)?

**Comment by P-vh** [comment] 2020-01-15 17:09
Yes, if you disable it the problem goes away

**Comment by ghostwords** [comment] 2020-01-21 16:31
When you say, "blocking only Spotify", do you mean that disabling replacement for just Spotify (screenshot below), leaving Widget Replacement enabled, and reloading the page doesn't seem to help?

![Screenshot from 2020-01-21 11:31:07](https://user-images.githubusercontent.com/794578/72823325-892a1a00-3c41-11ea-807e-79aca57b39e6.png)

**Comment by P-vh** [comment] 2020-01-22 07:44
Exactly. When I excluded "Spotify Player" and reloaded Discord it didn't replace it. For it to work I had to disable widget replacement (the checkmark). 
I believe the widget that the option " Spotify Player" blocks isn't the one causing the problem. Just speculation though.

**Comment by GiraffeKey** [comment] 2020-02-16 18:38
I was able to recreate this. Here is what I found:

They are right in that you have to uncheck widget replacement in order to fix the issue; excluding Spotify Player did not work. I did this while open.spotify.com was manually set to red.

I then set the domain to yellow, removed Spotify Player from the list, and enabled widget replacement once more. It stopped Discord from crashing, however, the entire window kept flashing a dark color each time I scrolled past the widget. Setting the domain to green stopped this from happening.

Having open.spotify.com at yellow still seems to cause an issue (for me, at least), but perhaps the domain should be added to the yellowlist?

**Comment by ghostwords** [comment] 2020-05-14 20:46
@P-vh @GiraffeKey Once your Privacy Badger upgrades to version 2020.5.12, could you see if disabling replacement just for Spotify Player is enough to work around this problem on Discord? It seems we had a bug with widget replacement exceptions.

**Comment by P-vh** [comment] 2020-06-04 04:29
I'm now in version 2020.6.2. Enabling widget replacement and disabling Spotify Player now works, the container still reserves the space for the widget but it doesn't show it. Nor does it crash the web client when you try to emulate the bug I still have when you _don't disable Spotify Player_ and scroll past it.

**Comment by clasick** [comment] 2021-06-28 16:10
Not able to reproduce this issue anymore. Here's a gif of the scrolling behavior of the widget working properly:

![discord-spotify-repo](https://user-images.githubusercontent.com/13066221/123668783-13c07100-d859-11eb-8e20-5dd8f7bcc5fa.gif)
### Versions
Firefox: 89.0.1 (64-bit)
Privacy Badger: 2021.6.8
### Repro method
1. api.spotify.com and open.spotify.com are both set to "red" state.
2. Posted a Spotify embed link in a Discord channel.
3. Scrolled up and down to identify crashes.

Perhaps we can close this issue if it's not happening in later versions?

**Closed** 2021-08-19 16:45 UTC
Labels: bug, broken site, widgets
