### ISSUE TITLE
Accessing website crashes Chrome with enabled Privacy Badger

### ISSUE THREAD

**Issue by roshavagarga** [EFForg/privacybadger#2325] opened 2019-03-08 08:02 UTC
#### What is your browser and browser version?
Chrome, 72.0.3626.121, x64
#### What is broken and where?
dumbingofage.com crashes Chrome with enabled PB.

#### What is the "culprit" domain?
I feel like you can figure this out, I'm at work so can't really do that.

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
Paste debug output here.
```

**Comment by mijiturka** [comment] 2019-03-08 14:40
I am unable to reproduce this with the same version of Chrome on Linux, using a new (untrained) copy of Privacy Badger 2019.2.19.

I've tried blocking every domain through the pop-up sliders and refreshing, didn't get a crash either.

Here's the list of initial decisions for this site. It may be helpful to find out what the difference in script blocking is between your Badger and one that doesn't crash (a new one which probably doesn't block something yours does)?

```
2.gravatar.com: "noaction"
a1.vdna-assets.com: "noaction"
ad.lkqd.net: "noaction"
adservice.google.co.uk: "allow"
adservice.google.com: "block"
as.casalemedia.com: "block"
bidder.criteo.com: "block"
cdn.exelator.com: "block"
cdn.syndication.twimg.com: "noaction"
cdn.thehiveworks.com: "noaction"
edge.quantserve.com: "block"
fastlane.rubiconproject.com: "block"
g2.gumgum.com: "block"
hb.vntsm.com: "noaction"
ib.adnxs.com: "block"
mc.yandex.ru: "cookieblock"
pbs.twimg.com: "noaction"
pixel.wp.com: "noaction"
platform.twitter.com: "cookieblock"
securepubads.g.doubleclick.net: "block"
static.criteo.net: "noaction"
stats.wordpress.com: "cookieblock"
syndication.twitter.com: "cookieblock"
ton.twimg.com: "noaction"
u.openx.net: "block"
uscdn.pixietrixcomix.com: "noaction"
vdna.exelator.com: "block"
venatusmedia-d.openx.net: "block"
vendorlist.consensu.org: "cookieblock"
www.facebook.com: "cookieblock"
www.google-analytics.com: "noaction"
www.googletagservices.com: "noaction"
www.thehiveworks.com: "noaction"
```

I got this list by following the instructions here https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain to open the debug console, and then, leaving dumbingofage.com as the only tab, typing:
```
> badger.tabData
5: {...}
> badger.tabData[5].origins
```

**Comment by ablanathtanalba** [comment] 2019-03-08 16:53
I was unable to reproduce this with the same version of Chrome on a MacOS, with both a new untrained Badger and an older one with over 2000 blocked domains.

**Comment by roshavagarga** [comment] 2019-03-08 16:57
How do I go about checking which domains are blocked?
Literally every time I open the website Chrome just crashes into infinity. I am running several other things (uBlock Origin, decentraleyes, https everywhere, minerblock) so I'm wondering whether something weird is going on between all of them?

**Comment by ablanathtanalba** [comment] 2019-03-08 19:38
It's worth experimenting different combinations of activated/on extensions running in tandem with your Privacy Badger. The issue may rest with some interaction between the different extensions, and finding that right combination will definitely give some more insight into what the problem may be.

**Comment by mijiturka** [comment] 2019-03-08 19:39
I was able to get blocked domains with `badger.tabData[x].origins` even when Privacy Badger is disabled for a website. You can disable it through the options page and open the website only afterwards.

Chrome [debug logs](https://support.google.com/chrome/a/answer/6271282?hl=en) may give a better idea of what's going on too.

**Comment by ghostwords** [comment] 2019-03-09 21:30
Is this a duplicate of #2249?

**Comment by ghostwords** [comment] 2019-03-09 21:36
You can now always get a copy/paste-able list of domains if you click on the Share button in the popup. This is a bit hidden at the moment, sorry.

![Screenshot from 2019-03-09 16:33:18](https://user-images.githubusercontent.com/794578/54077654-5d03e580-4289-11e9-8dee-fc88030219e7.png)

I'm guessing this is a Chrome extensions bug though and doesn't have anything to do with the domains on the page.

**Comment by ghostwords** [comment] 2019-05-14 16:21
Resolving as duplicate of #2249.

**Closed by ghostwords** 2019-05-14 16:21 UTC
Labels: Chrome, crash
