### ISSUE TITLE
breaks paypal.  report does not work

### ISSUE THREAD

**Issue by LargePrime** [EFForg/privacybadger#1132] opened 2017-01-12 04:13 UTC
came to say this breaks paypal.  perhaps issue #1052 ?

tried to report, and get Oops, something went wrong.

**Comment by cooperq** [comment] 2017-01-18 02:41
Thanks we will look into it.

**Comment by ghostwords** [comment] 2017-03-28 17:46
Hi @LargePrime, what was broken on the PayPal site? Is Badger's issue reporting feature still broken for you?

**Comment by ghostwords** [comment] 2017-03-29 14:00
Also, do you have NoScript (or some other addon like NoScript) installed?

**Comment by ghostwords** [comment] 2017-05-04 00:06
Error reporting being broken is probably a duplicate of #1164.

**Comment by ghostwords** [comment] 2017-05-04 00:07
PayPal being broken might be a duplicate of #1295 .

**Closed** 2017-05-04 00:08 UTC
Labels: broken site, duplicate, Firefox, high priority

**Comment by ghostwords** [comment] 2017-05-04 00:54
Is PayPal broken in a fresh profile with only Privacy Badger installed?
