### ISSUE TITLE
Firefox Quantum: v57.0 (64-bit): Privacy Badger add-on dropdown menu is all messed up, can't toggle tracking status and other problems.

### ISSUE THREAD

**Issue by Naturally-Delicious** [EFForg/privacybadger#1781] opened 2017-11-18 20:12 UTC
![screen shot 2017-11-18 at 3 10 37 pm](https://user-images.githubusercontent.com/20430449/32984331-aaa5f866-cc72-11e7-883e-12d50b8a75b7.png)

As seen in the image above, icons are in weird places and I can't toggle the tracking status fully, I can only put it in red and yellow, but not green. It's like half of the menu just got cut off. I can't scroll horizontally to see more.

**Comment by ghostwords** [comment] 2017-11-19 03:53
This seems like a duplicate of #1120. As a workaround, you could move Privacy Badger from the menu back to the toolbar.

**Closed by ghostwords** 2017-11-19 03:53 UTC

**Comment by Naturally-Delicious** [comment] 2017-11-24 06:30
Fixes it, thanks
