### ISSUE TITLE
Crosspixel tracking pixels not being blocked

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#2498] opened 2019-11-05 16:10 UTC
I look at androidpolice.com and it connects to https://tag.crsspxl.com/s1.js?d=651&cb=1572969955300

I look at this commit and domains like this should be blocked, right?

https://github.com/EFForg/privacybadger/pull/2147

**Comment by jawz101** [comment] 2019-11-05 16:24
another on https://www.avsforum.com/forum/40-oled-technology-flat-panels-general/2987240-2018-lg-b8-owners-thread-no-price-talk.html

https://tags.crwdcntrl.net/c/8060/cc_af.js

**Comment by ghostwords** [comment] 2019-11-05 20:07
- `crsspxl.com` is in the current pre-trained db, having been seen [tracking on two sites](https://github.com/EFForg/privacybadger/blob/master/src/data/seed.json#L19058-L19061).
- If I visit `androidpolice.com` in a new browser profile, my Privacy Badger learns to block `crsspxl.com` because it sees plain old cookie tracking, and that constitutes the third strike.
- Privacy Badger does not see tracking from `tags.crwdcntrl.net` because it doesn't detect pixel cookie sharing (#2147), or any other kind of tracking we detect at this time.
- General pixel tracking detection is tracked in #794.

I'll close this as a duplicate of #794. Let me know if you have any other questions.

**Closed by ghostwords** 2019-11-05 20:07 UTC

**Comment by ghostwords** [comment] 2019-11-05 20:14
According to https://github.com/EFForg/privacybadger/pull/2147#issuecomment-417121690, we do sometimes learn to block `crwdcntrl.net`.
