### ISSUE TITLE
*.unicornmedia.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1166] opened 2017-01-28 00:43 UTC
http://www.vox.com/world/2016/11/10/13577474/president-elect-donald-trump-muslim-ban

The following break the video, should be moved to yellowlist.
`onceux.unicornmedia.com`
`once-aws-eu-central-1-lb.unicornmedia.com`

**Comment by ghostwords** [comment] 2017-08-03 15:26
Duplicate of #1512.

**Closed by ghostwords** 2017-08-03 15:26 UTC
Labels: broken site, good volunteer task
