### ISSUE TITLE
Conflict with GreaseMonkey

### ISSUE THREAD

**Issue by B00ze64** [EFForg/privacybadger#1724] opened 2017-10-11 04:47 UTC
Good day.

Discovered a weird problem I have been having is caused by having both GreaseMonkey and Privacy Badger installed on FF 52 ESR. When both are active (you must have at least 1 script in GreaseMonkey) then when you click on simple a JPG (or any other media) anchor in a web page, the image does not load. I thought some change in FF was causing this, until tonight. When I disable GreaseMonkey then everything works, but disabling Privacy Badger also fixes the problem (and PB is the addOn I added last, I had no issues with GreaseMonkey before).

Tested in brand new profile:

1- Install GreaseMonkey & restart browser
2- Install a script (*)
3- Install Privacy Badger
4- Go to
https://www.anandtech.com/show/11907/logitech-ups-precision-of-g203-prodigy-mouse-to-8000-dpi
5- Click on the picture of the 3 mice -> The picture fails to load.

With either of these addOns disabled, the picture loads, but with both, nothing happens. I've had this with PDF files not loading, pictures not loading, sounds not playing, you name it. I've had to switch to ViolentMonkey for now (or disable Privacy Badger).

(*) Use this script https://raw.githubusercontent.com/Mechazawa/Firefox-plugin-enum-disable/master/DisablePluginEnum.user.js

Thank you.
Best Regards,

**Comment by ghostwords** [comment] 2017-10-11 13:08
Duplicate of #1653.

**Closed by ghostwords** 2017-10-11 13:08 UTC
