### ISSUE TITLE
Can't login to Google hashcode. accounts.google.com is the culprit.

### ISSUE THREAD

**Issue by Anutrix** [EFForg/privacybadger#2557] opened 2020-02-21 13:58 UTC
#### What is your browser and browser version?
Firefox 73.0.1 (64-bit)

#### What is broken and where?
Google hashcode website(g.co.in/hashcode redirects to https://codingcompetitions.withgoogle.com/hashcode) is broken. Can't login to hashcode or authenticate even if already logged into a google account. Doing so does nothing.

#### What is the "culprit" domain?
accounts.google.com is the culprit. Works fine if I allow this domain on Privacy Badger and refresh few times.

#### What is your debug output for this domain?
```
**** ACTION_MAP for google.com
google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
accounts.google.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
apis.google.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
books.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
calendar.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
checkout.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
clients1.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
clients6.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
consent.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
cse.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
developers.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
docs.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
drive.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
feedburner.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
feedproxy.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
fusiontables.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
groups.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
kh.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
khms0.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
khms1.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
khms2.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
khms3.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
khms4.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
labs.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
maps-api-ssl.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mapsengine.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
maps.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mt0.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mt1.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mts0.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mts1.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mw1.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
mw2.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
picasaweb.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
play.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
plus.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
sites.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
spreadsheets.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
talkgadget.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
translate.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
trends.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
video.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
www.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
smartlock.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1545582926865
}
pay.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1548411277355
}
fonts.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
adservice.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1580691631596
}
ogs.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1581475400352
}
signaler-pa.clients6.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1581735995094
}
scholar.google.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1582681545367
}
**** SNITCH_MAP for google.com
google.com [
  "linkedin.com",
  "vimeo.com",
  "copypastemap.com",
  "github.com",
  "mangadex.org"
]
```

**Comment by ghostwords** [comment] 2020-02-24 16:36
Hi and thanks for the report!

Just to be clear, are you signing in to Google from https://codingcompetitions.withgoogle.com/hashcode? I'm not clear on what g.com/hashcode is, or whether it is relevant to reproducing the problem.

This seems like the same problem as #137, but since it's happening on another Google domain, we can fix this particular case just by adding the missing domain to [Google's MDFP list](https://github.com/EFForg/privacybadger/blob/1ab519b90954627e50c8845533b5fd19c3a0c6b8/src/js/multiDomainFirstParties.js#L1050).

**Comment by ghostwords** [comment] 2020-03-05 16:28
Let me know if you have more information. Closing for now.

**Closed by ghostwords** 2020-03-05 16:28 UTC
Labels: MDFP, broken site

**Comment by LockedThread** [comment] 2022-02-24 13:54
This is still occurring. I am unable to sign up for the competition. Whenever I select the account to sign in with it redirects me the same page.

**Comment by ghostwords** [comment] 2022-02-24 16:23
> This is still occurring. I am unable to sign up for the competition. Whenever I select the account to sign in with it redirects me the same page.

Is this happening on https://codingcompetitions.withgoogle.com/hashcode? Are you blocking third-party cookies by any chance?
