### ISSUE TITLE
redlisted CDN

### ISSUE THREAD

**Issue by Chamaeleon-** [EFForg/privacybadger#1794] opened 2017-12-05 15:01 UTC
like mentioned in #1598 `cdn.datatables.net` is redlisted by default. this breaks sites with datatables.
this domain should be fine on the yellowlist !

**Comment by ghostwords** [comment] 2017-12-05 15:59
Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "datatables.net";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by Chamaeleon-** [comment] 2017-12-05 16:34
This is the output of the script.
```
**** ACTION_MAP for datatables.net 
cdn.datatables.net {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1512640373948
} 
datatables.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for datatables.net 
datatables.net [
  "127.0.0.1",
  "jsfiddle.net"
]
```

**Comment by ghostwords** [comment] 2017-12-05 21:55
That's strange, your data says that Privacy Badger decided to start blocking `cdn.datatables.net` after seeing it track on `127.0.0.1` and `jsfiddle.net`, but Privacy Badger needs to see a domain perform tracking three times before it will decide to start blocking that domain.

**Comment by Chamaeleon-** [comment] 2017-12-06 10:04
for privacy reasons i had to delete one domain (which points to 127.0.0.1 for debugging), sorry that i forgot to mention it.

**Comment by ghostwords** [comment] 2017-12-07 03:29
Ah OK good, I was concerned it's another bug.

I'll mark this as a duplicate of #1538. Privacy Badger used to view Cloudflare `__cfduid` security cookies as tracking, but no longer does. The problem is that we never told existing Privacy Badgers to forget about Cloudflare domains.

**Closed by ghostwords** 2017-12-07 03:29 UTC
