### ISSUE TITLE
Unable to globally reset all tracking domains at once

### ISSUE THREAD

**Issue by sylerner** [EFForg/privacybadger#1790] opened 2017-11-27 19:42 UTC
On the "Tracking Domains" tab, there is no way to reset all tracking domains to their default behavior.

Because it isn't clear that changing the behavior of a tracking domain on one web site changes the behavior of that tracking domain for all sites, I have globally disabled many trackers when I only wanted to disable them for a particular site.

In order to recover from this, I need to reset all tracking domains to their default behavior - it's not feasible to scroll though over 5,000 tracking domains searching for and resetting modified tracking domains.

Alternatively, having a way to sort the domain list so that all modified tracking domains are at the top would at least avoid the need of reviewing over 5,000 sites, although the inconvenience of having to reset each one individually would still remain.

**Comment by ghostwords** [comment] 2017-11-27 20:31
Duplicate of https://github.com/EFForg/privacybadger/issues/1422#issuecomment-329396546.

**Closed by ghostwords** 2017-11-27 20:31 UTC
