### ISSUE TITLE
First visit to www.rt.com yields "no trackers", simple reload yields many.

### ISSUE THREAD

**Issue by DeriJames** [EFForg/privacybadger#2100] opened 2018-07-16 15:36 UTC
The image on the right shows that PB has detected no trackers (icon is green) but opening the same page in another firefox instance (or simply reloading in the first instance) causes PB to block a lot of trackers, see image on left, icon is amber.

Whilst the first instance is open, cpu activity is quite high, but no cpu activity occurs whilst the second instance is open. This behaviour is seen only the first time firefox is opened, if it is already running navigating to an rt.com page will block the trackers.

Is this behaviour expected?
![image](https://user-images.githubusercontent.com/37815964/42768006-4b660998-8916-11e8-9e1c-4ed6421de55b.png)

**Comment by ghostwords** [comment] 2018-07-16 16:19
Is your homepage set to rt.com, or is your Firefox set to reopen tabs from last time on start? This is then a duplicate of #1845.

**Comment by DeriJames** [comment] 2018-07-16 16:39
Yes, I suspect you are correct (it is related), but it is not related to homepage definition. I suspect the underlying cause is because my typical use case is to click on a link in a KDE plasma RSS feed viewer, which results in an external call to "firefox <url>". So it looks like the delayed PB startup causes the trackers to be missed.

Many thanks for your reply.
![image](https://user-images.githubusercontent.com/37815964/42771409-0b3136dc-891f-11e8-80dc-dfe6d6754eb6.png)

**Comment by ghostwords** [comment] 2018-07-16 16:47
OK, thanks for clarifying! Let's subscribe to #1845 for updates.

**Closed by ghostwords** 2018-07-16 16:47 UTC
