### ISSUE TITLE
the slider widgets on the main extension window have very inconsistent response to mouse action

### ISSUE THREAD

**Issue by yohanneshabte** [EFForg/privacybadger#2514] opened 2019-12-04 15:07 UTC
### OS Version, Browser and Browser Version, Extension Version 
**Mac O.S. 10.15.1**
**Google Chrome**
*Version 78.0.3904.108*
### Detailed description of issue
While using the chrome extension, the sliders that are used to toggle between "block domain", "block cookies", and "allow domain" next to each trackers don't function as intended all of the time. After one change(doesn't matter the position/ranking), there seems to be a UI malfunction that results in the rest of the trackers having a very unresponsive slider that is persistent until the page is reloaded. 
**Other related slider issues**
1. Very large delay between input of choice and actual value being changed
2. Additionally Sliders don't toggle to one option completely sometimes, resulting in ambiguous slider position(between two different values)
### Steps to reproduce problem
nothing specific I did on my part. Except 
1. Open a webpage with a handful or more trackers active 
2. Toogle one of the trackers to a different value(first one usually works without any issue)
3. Next ones after the first successful change will need a lot of single clicks or double clicks before any change occurs to the value of the trackers.
4. After a lot of consecutive attempts there's still a huge chance the values will not change, unless you reload the page and give it another go one tracker at a time on the first try(which would mean having to reload multiple time to disable or re-enable a couple trackers) 
#### Example 1
![example 1](https://user-images.githubusercontent.com/54902916/70153275-4ce03180-1674-11ea-875d-dc2bab001708.gif)
#### Example 2
![example 2](https://user-images.githubusercontent.com/54902916/70153333-64b7b580-1674-11ea-9971-238282d3ce7b.gif)
#### Example 3
![example 3](https://user-images.githubusercontent.com/54902916/70153409-86b13800-1674-11ea-8b45-a685272275e0.gif)

### Expected Behavior
Easier to toggle back and forth between the three choices, preferably a single click if not double click for all the trackers without having to reload after a single change.
**notes:** it doesn't make a difference what the value of a tracker is at the start(block domain, cookies or allow both) according to my experience with it.

Is this expected behavior by any chance? Perhaps some kind of delay to restrict switching trackers on and off quickly. It's definitely not a fatal error, but discounts a lot from the user experience not having the fluid UI you would expect. Thank you very much for your help!

**Comment by ghostwords** [comment] 2019-12-04 17:31
Hello and thanks for getting in touch! I'm having trouble reproducing.

Are you able to reproduce in a different browser (Firefox)? How about in a new Chrome profile?

Does it matter whether you click (where you want the slider to be), or drag the slider (to where you want it to be)? If clicking, does it matter if you click on the bottom (where the cursor is a hand for you), or elsewhere (where the cursor is a "move" cursor)?

**Comment by yohanneshabte** [comment] 2019-12-05 17:20
Thanks for responding so quickly. I seem to be getting the issue with google chrome only. I just installed the same extension on Firefox, and it turned out to be a pleasant experience using it. I have attached more short gifs to demonstrate the difference between FireFox and chrome for me. I have also added more of chrome's screen capture to show there's no difference between clicking, sliding, or even the switch between the cursor, pointer or crosshair doesn't make a difference for the issue I'm facing. 
#### Chrome(Version 78.0.3904.108)
##### Dragging slider
![sliding](https://user-images.githubusercontent.com/54902916/70256718-93a25a00-174e-11ea-97d2-7bdd4ce428ad.gif)
##### Clicking slider
![clicking](https://user-images.githubusercontent.com/54902916/70256730-99983b00-174e-11ea-8e73-f34414560536.gif)
##### Cursor type and location of click makes no difference
![cursor type](https://user-images.githubusercontent.com/54902916/70256743-9e5cef00-174e-11ea-9b89-a83f9fcc15d1.gif)
#### Firefox(Version 71.0)
![firefox](https://user-images.githubusercontent.com/54902916/70257866-c77e7f00-1750-11ea-8a21-fa7ad0b52cd3.gif)

**Note:** I don't have any other extensions enabled during testing for chrome. I have also reinstalled chrome to see if it makes a difference, but nothing has helped yet.
I will also try to reproduce the error using my library's computer later today on both a Windows and Mac OS systems.
Is there anything else you might want me to show you, for you to be able to reproduce the error?

**Comment by ghostwords** [comment] 2019-12-05 17:40
Thank you! I'll let you know if I have any more questions.

@daly Could you see if you can reproduce in Chrome on macOS?

**Comment by ablanathtanalba** [comment] 2019-12-05 17:49
> Thank you! I'll let you know if I have any more questions.
> 
> @ablanathtanalba Could you see if you can reproduce in Chrome on macOS?

Hi there, unfortunately I am able to reproduce the bug at this time. I just tested on the same build of Chrome (Version 78.0.3904.108). I suspect this bug must have been introduced recently as I'm often testing the sliders in Chrome. Since I'm able to reproduce, I'm happy to look more into this bug and find a solution.

**Comment by ghostwords** [comment] 2019-12-05 17:50
Great, thanks! Could you find the culprit commit (with `git bisect`)?

**Comment by yohanneshabte** [comment] 2019-12-05 18:44
Thank you very much @ablanathtanalba. I was very worried the problem was from a new O.S. update on my part. I look forward to any kind of fix/work arounds you might have for the issue.

**Comment by ablanathtanalba** [comment] 2019-12-06 21:30
I tried reproducing this bug in previous builds of Privacy Badger, going back as far as 2017, and the issue still persists. This leads me to believe that the bug was introduced with a change to Chrome itself. I filed an [https://bugs.chromium.org/p/chromium/issues/detail?id=1031675](issue with Chrome here).

**Comment by ablanathtanalba** [comment] 2019-12-11 00:32
Tested this bug on Chrome version 75.0.3770.80, and the problem doesn't persist with that build (released June of this year). Further evidence that the issue lies with Chrome.

![chrome_75_testing](https://user-images.githubusercontent.com/25778052/70581032-aeb80400-1b6a-11ea-9210-552bcc57a8e7.gif)

**Comment by ablanathtanalba** [comment] 2019-12-11 23:49
Chrome's most recent release, version 79.0.3945.79, seems to have corrected this issue on my end. @yohanneshabte please update your Chrome version and let me know if the problem still persists on your end.

**Comment by ablanathtanalba** [comment] 2019-12-16 19:03
Closing this issue for now, as it still seems to have been righted in the most recent update of Chrome

**Closed by ablanathtanalba** 2019-12-16 19:03 UTC
Labels: bug, ui
