### ISSUE TITLE
Not from Chrome Web Store.

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1496] opened 2017-07-15 18:48 UTC
I feel like this was supposed to have been fixed some time ago, but I'm still seeing it in the extensions page with `2017.6.13.1`.

**Comment by ghostwords** [comment] 2017-07-16 19:56
Yes, still an unsightly but harmless bug; as @cooperq wrote, a workaround for #843.

**Comment by ghostwords** [comment] 2017-07-19 17:53
Previously: #1204.

**Comment by Kakurady** [comment] 2018-01-04 21:27
Chrome just disabled Privacy Badger because it's "not from Chrome Web Store", now I have to uninstall and reinstall to get it working again. (Reinstallation did not fail though.)

**Comment by ghostwords** [comment] 2018-01-04 22:00
Hi @Kakurady, which OS and which version of Chrome do you have?

**Comment by chhe** [comment] 2018-01-05 07:34
Same thing for me.

OS: `Windows 10 x64 1709`
Chrome: `Version 64.0.3282.71 (Official Build) beta (64-bit)`

**Comment by ghostwords** [comment] 2018-01-05 15:39
@Kakurady @chhe Does your issue appear to be the same as #1186? Chrome's extensions page UI may have changed but the core issue might be the same.

**Comment by Kakurady** [comment] 2018-01-05 15:50
@ghostwords It is, and the extension is still enabled after relaunch. OS: Windows 10, Chrome: `64.0.3282.71 (Official Build) beta (64-bit) (cohort: Beta)`

From reading #1186, looks like the problem is on Chrome / Chrome Web Store's end.

**Comment by Chaz6** [comment] 2018-01-18 18:35
I just installed Privacy Badger from the chrome web store, and it says "Not from Chrome Web Store" (version 2017.11.20).

**Comment by ghostwords** [comment] 2018-01-25 16:37
We are going to do an update later today that should fix "Not from Chrome Web Store"-related issues.

**Comment by ghostwords** [comment] 2018-01-25 18:17
This should be fixed as of [Privacy Badger version 2018.1.25](https://github.com/EFForg/privacybadger/releases/tag/release-2018.1.25).

Let me know if updating fixes your problem. You could try forcing an update by visiting `chrome://extensions` and clicking the "Update extensions now" button.

**Closed by ghostwords** 2018-01-25 18:17 UTC
Labels: Chrome, bug, ui, wontfix

**Comment by jeremyn** [comment] 2018-01-25 18:39
@ghostwords "Not from Chrome Web Store" is gone for me, thanks.

**Comment by Kakurady** [comment] 2018-01-26 03:28
Looks like it's gone for me too, neat. (version 2018.1.25)
