### ISSUE TITLE
PB UI is cut off when icon is placed inside the menu of Firefox

### ISSUE THREAD

**Issue by MegaPhantomII** [EFForg/privacybadger#1709] opened 2017-10-04 13:27 UTC
When the PB icon is placed in the Firefox menu, the UI is cut off and the sliders to adjust site settings are cut off. A scroll bar does appear, but using it does not reveal the missing part of the slider. I have noticed this issue while using Firefox 56.0 on Windows 7, MacOS 10.12.6, and Ubuntu 16.04.
![screen shot 2017-10-04 at 9 26 45 am](https://user-images.githubusercontent.com/27040052/31178159-37b4828c-a8e6-11e7-95ce-d1945bf57f27.png)
![screen shot 2017-10-04 at 9 26 59 am](https://user-images.githubusercontent.com/27040052/31178171-3dfe72ba-a8e6-11e7-9898-b2b2149d88fc.png)

**Comment by ghostwords** [comment] 2017-10-04 13:42
Duplicate of #1120.

**Closed by ghostwords** 2017-10-04 13:42 UTC
Labels: bug, duplicate, Firefox, ui
