### ISSUE TITLE
[feat request] A site to share some pre-set settings ready to import

### ISSUE THREAD

**Issue by GeorgeWL** [EFForg/privacybadger#1472] opened 2017-07-04 10:23 UTC
Feel like this might be a really useful way to quickstart for some people.

**Comment by ghostwords** [comment] 2017-07-05 00:00
I'll mark this as a duplicate of #1333 and maybe #1299.

**Closed by ghostwords** 2017-07-05 00:00 UTC

**Comment by GeorgeWL** [comment] 2017-07-05 08:28
oh sorry @ghostwords somehow my quick search missed those when I looked for similar issues.
