### ISSUE TITLE
Privacy Badger blocks pictures from my domain, what can I do?

### ISSUE THREAD

**Issue by schiessle** [EFForg/privacybadger#1450] opened 2017-06-21 13:58 UTC
Hi,

I have a personal homepage build with Hugo: www.schiessle.org
My blog is syndicated on some planets, now I noticed that I don't see any pictures in my blog posts on those planets because Privacy Badger blocks my domain. Is there anything I can do? How can I found out why Privacy Badger blocks my domain? Of course I can whitelist it for me, but I would prefer a solution which makes sure that everybody who reads my blog through a planet and uses Privacy Badger see the pictures.

Anything I can do to find out what causes privacy badger to block my domain and how to fix it?

Thanks!

**Comment by schiessle** [comment] 2017-06-21 14:03
Hm, strange. I observed the problem yesterday and today it seems to work. Anyhow would be good to have a page where I can "test" a domain to see if privacy badger accept or decline it with offering some tips what need to be changed. Similiar to the HTML or CSS validation pages from w3c or the SSL server test from SSLLabs

**Comment by ghostwords** [comment] 2017-06-21 15:09
I'll mark this as a duplicate of #963. Once implemented, Privacy Badger's popup will say something like, "`www.schiessle.org` is being blocked because it was seen tracking via cookies on `example.com`."

**Closed by ghostwords** 2017-06-21 15:09 UTC

**Comment by ghostwords** [comment] 2017-06-21 15:10
Could you specify a few pages where you saw pictures from your domain getting blocked?

**Comment by schiessle** [comment] 2017-06-21 16:10
@ghostwords one example would be planet.debianforum.de. My last blog post is already a few months old so only few planets have a current example at the moment. But if you scroll down at planet.debianforum.de to "Rolle Rückwärts in München: Diese Fragen sollte man sich stellen" by "Bjoern Schiessle" you will find a example. The pictures in there was blocked yesterday, then I whitelisted my domain and today I reset Privacy Badger and the pictures are still visible. So not sure what changed between yesterday and today.

**Comment by ghostwords** [comment] 2017-06-21 16:29
By resetting, do you mean you uninstalled/reinstalled Privacy Badger? Doing that erases Privacy Badger's learnings, which is no big deal, Badger will relearn quickly enough, but it does mean Badger won't decide to block your domain until it again sees it perform tracking on three or more unrelated domains.

**Comment by ghostwords** [comment] 2017-06-21 16:38
My Privacy Badger doesn't see any tracking from `schiessle.org` on `planet.debianforum.de`. I think what happened is that you had login cookies for your website, and those cookies were being sent for static resources requested from your domain on `planet.debianforum.de` and other sites. If so, this doesn't seem like a problem other people would run into since they won't have cookies set for your domain.

You can tell your Privacy Badger to allow your domain's resources to load by toggling the slider for your domain to "green".

Also, to improve website performance/security, you could avoid sending cookies when fetching static resources by configuring a dedicated static resources (sub)domain.

**Comment by schiessle** [comment] 2017-06-21 16:48
> By resetting, do you mean you uninstalled/reinstalled Privacy Badger?

No, I went to the settings and removed my domain from "User Filter Settings"
