### ISSUE TITLE
Tooltips on Tracking Domains only appear when hovering on bottom section of slider

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadger#1821] opened 2018-01-03 05:45 UTC
There currently looks to be a conflict on the Tracking Domains tab where the draggable nature of the sliders introduced way back in a6024271 interferes with the hoverable area on the slider that triggers the tooltip. As a result, the tooltip only appears to be triggered when hovering on the bottom 1/4 or so of the slider.

One curious observation is that when you scroll down in the list of tracking domains, the slider is not actually loaded in lazily loaded entries. When you scroll into this region, the correct tooltip appears regardless of where you are hovering on the slider, and the cursor remains the default cursor.

I fiddled a bit with this, and I didn't see an obvious way to preserve the draggable nature of the slider while allowing the tooltips to be triggered across the entire range of the slider. I should clarify, the `ui-slider` is not the slider itself, but the ability to drag the slider with the mouse pressed rather than simply clicking on another position on the slider.

Removal of the drag feature would easily remedy this, as the cursor CSS property could be added to the `actionToggle` class, though I'm not certain whether this is an appropriate compromise or whether another more obvious solution exists.

**Comment by ghostwords** [comment] 2018-01-03 14:44
Duplicate of #1746.

**Closed by ghostwords** 2018-01-03 14:44 UTC
Labels: bug, duplicate, ui

**Comment by ghostwords** [comment] 2018-01-15 16:12
@alexristich I think what you observed re sliders generated on scroll is also the source of bug #1706.
