### ISSUE TITLE
Error on console in Firefox Nightly

### ISSUE THREAD

**Issue by Mte90** [EFForg/privacybadger#1388] opened 2017-05-19 16:22 UTC
I get this errors in Firefox Nightly on the console:
```
Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/heuristicblocking.js 540
[[Exception stack
startListeners/<@moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/heuristicblocking.js:540:7
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:203:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:234:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:130:32
receiveMessage@resource://gre/modules/ExtensionChild.jsm:725:49
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]
Extension error: TypeError: settings is undefined moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/background.js 533
[[Exception stack
isPrivacyBadgerEnabled@moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/background.js:533:9
onBeforeSendHeaders@moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/webrequest.js:140:7
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:203:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:234:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:130:32
receiveMessage@resource://gre/modules/ExtensionChild.jsm:725:49
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]
Extension error: TypeError: settings is undefined moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/background.js 533
[[Exception stack
isPrivacyBadgerEnabled@moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/background.js:533:9
onBeforeSendHeaders@moz-extension://dc9f2f32-7d5e-43df-94f5-f6a873d3cae3/js/webrequest.js:140:7
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:203:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:234:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:130:32
receiveMessage@resource://gre/modules/ExtensionChild.jsm:725:49
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]
```
I don't know if are Firefox nightly specific bugs but it is better to report :-)

**Comment by ghostwords** [comment] 2017-08-21 14:42
I'm going to close this, much changed in Firefox since May.

**Closed by ghostwords** 2017-08-21 14:42 UTC
Labels: Firefox

**Comment by guillaume-uH57J9** [comment] 2017-12-27 14:15
I can still reproduce this using
* Firefox ESR 52.5.0 (64 bits), the long-term support release of Firefox
* Privacy Badger 2017.11.20

The following errors are shown at startup. There same errors repeats numerous time, I am just pasting the first few occurrences here. 

> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
> Extension error: TypeError: badger.heuristicBlocking is undefined moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js 508
> [[Exception stack
> startListeners/<@moz-extension://91cbe87b-20bb-43e8-bea6-8077b8515256/js/heuristicblocking.js:508:7
> Current stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
> runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
> runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
> receiveMessage@resource://gre/modules/ExtensionChild.jsm:586:49
> _callHandlers/<@resource://gre/modules/MessageChannel.jsm:574:17
> _callHandlers@resource://gre/modules/MessageChannel.jsm:573:14
> _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:637:7
> _handleMessage@resource://gre/modules/MessageChannel.jsm:634:24
> receiveMessage@resource://gre/modules/MessageChannel.jsm:165:5
> ]]
>
