### ISSUE TITLE
Tracking info in URLs?

### ISSUE THREAD

**Issue by sandy-harris** [EFForg/privacybadger#1718] opened 2017-10-06 20:10 UTC
Quite often a URL given as a link somewhere includes info I would sooner not reveal. For example, reading email on Gmail & clicking on a link in an email from Threatpost this morning I was taken to:

https://threatpost.com/us-top-law-enforcement-calls-strong-encryption-a-serious-problem/128302/?utm_source=newsletter&utm_medium=Email&utm_campaign=tp%20daily%20digest

If I delete everything after the first question mark, the link still works & I give away less information. In this case I'm not much worried. I'm inclined to trust Kapersky Labs who run the Threatpost site & telling them I'm following a link from their email does not seem much of a hazard anyway.

In other cases it may matter more. For example, I am an admin on the travel guide site wikivoyage.org and have several times removed ?referrer= tags in URLs for hotels & restaurants, preventing some editors from trying to get commission when someone clicks on the link.

I'd like a switch that would make the badger delete everything after a '?' character in every URL, or a pointer to some other Firefox add-on that will do that. Not giving sites unnecessary info seems like good policy. I've only tested in about a dozen cases, but every time I tried it the unadorned URL got me to the same page.

**Comment by ghostwords** [comment] 2017-10-06 20:15
Duplicate of #681?

**Comment by ghostwords** [comment] 2017-10-16 15:56
Resolving as a duplicate. Here are some existing solutions (no personal experience with any of them):
- https://chrome.google.com/webstore/detail/tracking-token-stripper/kcpnkledgcbobhkgimpbmejgockkplob
- https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/
- https://addons.mozilla.org/en-US/firefox/addon/pure-url/

**Closed** 2017-10-16 15:57 UTC
Labels: duplicate, enhancement, privacy
