### ISSUE TITLE
In Firefox, New Window Shows Blocked Privacy Indicator, No Sliders

### ISSUE THREAD

**Issue by tanabi** [EFForg/privacybadger#1119] opened 2017-01-04 14:38 UTC
Hey there;

Using Firefox 50.1.0 on a Mac.  Privacy badger works correctly in most cases, but when I open a new window, it indicates 1 privacy error ... but clicking Privacy Badger shows no sliders.  I've grabbed the error out of the web console.

![privacy-badger](https://cloud.githubusercontent.com/assets/6575637/21645839/ad76fc54-d261-11e6-80b2-aad34e4b6b15.jpg)

The no-slider screen looks the same as the slider does when there's no trackers on a page.  If there's really something trying to load every time I open a new window, I'd really like to see what it is!

**Comment by tanabi** [comment] 2017-01-04 14:44
As a follow-up, this doesn't seem to always happen.  I just restarted my browser and I'm not getting this problem.  However, I've seen it happen a few times before, so I think this may be something that happens over time.  I'm going to keep an eye on it and see if I can reliably reproduce the problem.

**Comment by cooperq** [comment] 2017-01-05 02:52
Looks like a duplicate of #1101 closing this in favor of that.

**Closed by cooperq** 2017-01-05 02:52 UTC

**Comment by ghostwords** [comment] 2017-01-06 18:18
Hi @tanabi, do you have JavaScript disabled by any chance?

**Comment by tanabi** [comment] 2017-01-06 19:41
No, Javascript is enabled.

I actually suspect it might have been an interaction with an add-on that caused it, but I haven't been able to reliably reproduce it yet.
