### ISSUE TITLE
Breaks ServiceWorkers in Firefox

### ISSUE THREAD

**Issue by Boldewyn** [EFForg/privacybadger#1144] opened 2017-01-17 11:54 UTC
Service Worker requests are intercepted as well. In some occasions this leads to a completely broken website.

Given the power of [Service Workers](https://www.w3.org/TR/service-workers/) intercepting them might be a good idea, but when this leads to the site becoming completely unusable, it should be turned off for the time being.

Screenshot: [Smashing Magazine](https://www.smashingmagazine.com/2017/01/designing-better-app-icons/), renowned news site, inaccessible due to PB blocking its Service Worker. 
![sw](https://cloud.githubusercontent.com/assets/48738/22019462/fee2f370-dcb3-11e6-81f1-feaab865f525.png)

PB version: 2016.12.15.1
Browser: Firefox 50.1 (Linux)

**Comment by cooperq** [comment] 2017-01-18 02:53
Hmm, that's strange. Privacy Badger shouldn't be blocking any service workers unless they are from a third party domain which is also blocked by privacy badger. Will have to look into this deeper.

**Comment by Boldewyn** [comment] 2017-01-18 07:54
I don't know, what exactly triggered the issue. [Apparently](https://twitter.com/smashingmag/status/821325629345976324) the owner himself uses PB, too.

**Comment by cowlicks** [comment] 2017-07-24 06:33
@Boldewyn @liocalset is this still an issue? I'm unable to reproduce it on my first try.

**Comment by Boldewyn** [comment] 2017-07-24 09:25
For me, yes. Firefox 54.0, PB 2017.6.13.1. But I see it exclusively on Smashing Magazine.

**Comment by ghostwords** [comment] 2018-10-16 21:06
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1499523

**Comment by ghostwords** [comment] 2018-11-06 23:15
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1499523#c4, this will be fixed in Firefox when https://bugzilla.mozilla.org/show_bug.cgi?id=1231208 is fixed. We may release workarounds in Privacy Badger before then, however.

**Comment by ghostwords** [comment] 2019-01-30 22:45
A related uMatrix issue: https://github.com/uBlockOrigin/uMatrix-issues/issues/72

**Comment by bcyphers** [comment] 2019-04-17 19:08
Looks like this affects the new Twitter experience (mobile.twitter.com) as well, sending users into a redirect loop or bumping them to a log-in page even when they're already logged in.

**Closed** 2019-09-19 19:15 UTC
Labels: Firefox, broken site, bug, high priority
