### ISSUE TITLE
Tracking Domain List in Settings Should Be Larger

### ISSUE THREAD

**Issue by Marsfan** [EFForg/privacybadger#2803] opened 2021-09-26 05:38 UTC
In the Privacy Badger Settings, there is a a tab that allows the user to view all tracking domains that Privacy Badger has decided to block. For some reason, this list is displayed as only a small section of the entire page, when it could be much larger, allowing the user to utilize the full size of the window to display the list. 

I suggest that this list should be resized to utilize all available space, instead of being a small sub-section of the page.

<details>
<summary> Current Appearance </summary>

![image](https://user-images.githubusercontent.com/9311953/134794877-b71935e1-2797-480e-a910-af1bbb0e5462.png)

</details>

<details>
<summary> Proposed Appearance Concept </summary>

![image](https://user-images.githubusercontent.com/9311953/134795072-1cdd3bc6-3da3-44ec-bb94-61ba85dfea8c.png)

</details>

**Comment by ghostwords** [comment] 2021-09-26 17:41
Hi, thanks for the suggestion! I'll mark this as a duplicate of #1599.

**Closed by ghostwords** 2021-09-26 17:41 UTC
Labels: enhancement, ui
