### ISSUE TITLE
Blocking algolianet.com

### ISSUE THREAD

**Issue by asurak** [EFForg/privacybadger#809] opened 2016-04-14 13:38 UTC
We operate API on `*.algolia.net` and `*.algolianet.com` and `algolianet.com` gets sporadically blocked by the badger for no reason. We don't set cookies, we don't read cookies, we don't track users, we even host `https://algolianet.com/.well-known/dnt-policy.txt`.

This blocking impacts our service and it's difficult to debug as our users installing Privacy Badger are not completely aware of the consequences.

How should we proceed?

**Comment by cooperq** [comment] 2016-04-27 01:52
oh no! This definitely sounds like a bug, I wonder what is going on here. I will look into it further.

**Comment by asurak** [comment] 2016-04-29 14:37
Let me know if I can provide any additional info ;)

**Comment by cooperq** [comment] 2016-05-02 19:52
Can you give me some example sites that might be including content from algolia.net and .com please

**Comment by asurak** [comment] 2016-05-02 19:59
try to search in the upper right corner on https://medium.com/ or https://hn.algolia.com - we never include content, we always do just XHR ... the algolianet.com is a fallback domain that is used when connection to algolia.net fails

**Comment by cooperq** [comment] 2016-05-02 21:29
Interesting, I am seeing a call to algolia.net but it's marked as not tracking in my browser. Also I see that you have the DNT policy posted on algiolanet.com but not algiola.net

**Comment by asurak** [comment] 2016-05-02 21:32
That is because we have never seen the issue on `algolia.net`. We don't set any cookies so we see no reason why to get blocked.

**Comment by asurak** [comment] 2016-05-03 12:34
Today we have seen blocking of `www.algolia.com`. We are not tracking users on any of our domains `algolia.com`, `algolia.net` or `algolianet.com`. `algolia.com` is behind CloudFlare, is it possible that the security cookies they are setting are considered tracking?

Is there any possibility to get our domains to a whitelist? We are getting reports from users getting our API blocked almost everyday and they are not able to give us any detailed info as it takes them a long time to even find out it's the privacy badger 😢

**Comment by cooperq** [comment] 2016-05-03 16:55
Ah, it's almost cetainly the cloudflare security cookie causing the issue then. If you post the DNT policy to algolia.com that should stop privacy badger from blocking it. That is the only way to get whitelisted.

**Comment by asurak** [comment] 2016-05-03 16:56
But how does it relate to algolianet.com and algolia.net? We don't have these two domains behind Cloudflare's proxy.

**Comment by cooperq** [comment] 2016-05-17 06:15
Hmmm okay well the algiolanet.com should be getting marked as DNT compatible. There may have been bugs in that which are fixed in the next release. As for www.algiola.com the cloudflare cookie is probably what's causing the trouble. I would reccomend you put the DNT policy up there too (as long as you can abide by it.)

**Comment by cooperq** [comment] 2016-09-28 22:05
Ah! I have found the issue! Your copy is not hashing properly because you did not post it *verbatim*

Specifcally you changed the line:
`posted via HTTPS at https://example-domain.com/.well-known/dnt-policy.txt`
to algolia.net. You should not do this as it will cause privacy badger to see the wrong hash for the file and not mark it as DNT compliant. Fixing this should fix the problem.

**Comment by asurak** [comment] 2016-10-03 15:27
Thanks @cooperq! We'll deploy a verbatim version of the DNT policy to fix it.

**Comment by asurak** [comment] 2016-11-24 12:55
The issue has returned and its worse than ever. We see our domain `algolia.net` and `algolianet.com` blocked for no reason.
![screen shot 2016-11-24 at 13 52 44](https://cloud.githubusercontent.com/assets/313744/20599286/9962fdfa-b24d-11e6-8824-cf5da86e37d4.png)

All the domains have DNT policy and no cookies. Why are we blocked?

**Comment by asurak** [comment] 2016-11-24 18:18
This issue is widespread and it's causing us serious business impact

**Comment by ghostwords** [comment] 2016-11-30 16:47
I have trouble reproducing ... Could you share how to get Privacy Badger to start blocking algolia domains?

**Comment by asurak** [comment] 2016-12-01 13:12
Have not been able to reliably reproduce the issue. Is there any debug information I can get for your from the extension at the moment of blocking?

**Comment by cooperq** [comment] 2016-12-08 16:54
Hi @asurak it looks like you have the same issue where you have changed the domain name in the dnt policy and not posted it verbaitm. Please try reposting the verbatim copy!

**Comment by asurak** [comment] 2016-12-09 08:36
I'm afraid that is not the case this time:
```
➜  ~ curl -s https://0h4smabbsg-1.algolianet.com/.well-known/dnt-policy.txt > algolia-dnt.txt
➜  ~ curl -s https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt > eff-dnt.txt
➜  ~ shasum ./*-dnt.txt
a18e8dba6848d3fc241b03b88291cb75a3cfec3b  ./algolia-dnt.txt
a18e8dba6848d3fc241b03b88291cb75a3cfec3b  ./eff-dnt.txt
```

![privacy-badger-producthunt](https://cloud.githubusercontent.com/assets/313744/21042630/f323c166-bdf2-11e6-866d-cb327c001182.png)

**Comment by asurak** [comment] 2016-12-09 09:21
Ah, seems like there was one more file that is was checking, which was not really obvious - `https://algolianet.com/.well-known/dnt-policy.txt` -  since it shows blocking per sub-domain, not per domain

**Comment by asurak** [comment] 2016-12-09 10:02
We're not hosting the DNT file for `algolia.net` because nothing is hosted on `https://algolia.net/*` and we don't even have a certificate for it, everything is `https://*.algolia.net/*`. None of the calls to the domain is having cookies either. Why is it getting blocked? Not hosting the DNT file does not seem a good enough reason.

**Comment by cooperq** [comment] 2016-12-09 22:13
@asurak can you give me some examples of sites that embed algolianet.com as a third party so I can try to reproduce this?

**Comment by asurak** [comment] 2016-12-10 01:55
producthunt.com

Le ven. 9 déc. 2016 à 23:14, Cooper Quintin <notifications@github.com> a
écrit :

**Comment by asurak** [comment] 2016-12-12 11:12
What can we do? This has absolutely disastrous impact on our business. The `algolianet.com` domain is still being blocked on `https://www.ohmygift.co.uk/catalogsearch/result/?q=christmas` as a potential tracker for absolutely no reason. We have customers churning because of non working search that we're unable to prevent or explain.

**Comment by cooperq** [comment] 2016-12-12 19:04
@asurak I am having trouble reproducing this problem. Can you send me as many websites as possible that are using algolianet? I checked producthunt and ohmygift.co.uk and both are correctly marking *.algolia.net as DNT compliant.

**Comment by asurak** [comment] 2016-12-12 19:31
This is what I see the badger configured for itself. Are any algolia domains blocked in some centralised rules that the badger is getting? algolia.net does not serve any content and it does not seem to be manually possible to block it from the UI either.

![screen shot 2016-12-12 at 20 29 01](https://cloud.githubusercontent.com/assets/313744/21113378/abdac25a-c0a9-11e6-90af-8ea6b26f9851.png)

**Comment by cooperq** [comment] 2016-12-12 19:59
Very strange indeed. All algolia.net algolianet.com domains are correctly shown as having the DNT policy for me. 
Can you start a new browser profile with privacy badger and browse around to a few sites with aloglia and see if you can reproduce the issue?

**Comment by asurak** [comment] 2016-12-12 21:15
When I start a new profile, I cannot reproduce the issue. Although I can clean my profile, what about those that don't?

**Comment by jawz101** [comment] 2017-01-06 17:57
xda forums use algolia.net for [their search engine](https://forum.xda-developers.com/search).  That's my example because I use them often.  In NoScript I have to whitelist algolia.net and cloudflare.com to search anything on their site.

**Comment by cooperq** [comment] 2017-01-10 00:40
@asurak can you run the following code for me in your main profile in the privacy badger debug console:
`_.each(badger.storage.action_map.getItemClones(), function(v,k){if(k.indexOf('algolia') > -1){console.log(k, v.dnt, new Date(v.nextUpdateTime))}}); console.log(a);` and paste the output here?

**Comment by cooperq** [comment] 2017-02-27 21:11
@asurak good news! I think we have tracked down the cause of this bug and I have a fix in here #1182 which should fix the issue once and for all!

**Comment by asurak** [comment] 2017-03-02 23:27
That's great @cooperq !

**Comment by ghostwords** [comment] 2017-04-21 16:08
This should be fixed at this point. Let us know if it isn't.

**Closed by ghostwords** 2017-04-21 16:08 UTC
Labels: broken site, bug, DNT policy, high priority
