### ISSUE TITLE
Block canvas & cache based evercookie

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#616] opened 2015-09-27 21:53 UTC
I've noticed that the firefox version (fresh install + clean install of browser and extensions) detects the c.t4ft.de domain referenced in golem.de and zeit.de as fingerprinting website.

Going to the page in a fresh chrome installation (browser and extension) shows this domain under non-tracking domains. But looking at the script http://c.t4ft.de/c/ftg_iq.min.js shows that it does canvas fingerprinting. This is also the reason why this domain gets blocked after a while in firefox but not in chrome

As said earlier, both were fresh installations with fresh user profiles. Both browsers only had privacy badger and https everywhere installed,

**Comment by SwartzCr** [comment] 2015-10-01 21:01
@ghostwords any ideas?

**Comment by ghostwords** [comment] 2015-10-01 22:35
It seems that the canvas fingerprinting function (if that is what it is ...) writes to the canvas element using [drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage), which is not one of the "write methods" we currently support. If so, this wouldn't get picked up for canvas fingerprinting on any browser.

**Comment by ghostwords** [comment] 2015-10-01 22:59
After adding drawImage to Chameleon, I got two hits on golem.de:

```{
  "obj": "CanvasRenderingContext2D.prototype",
  "prop": "getImageData",
  "scriptUrl": "https:\/\/c.t4ft.de\/c\/ftg_t_v_bk.min.js?aid=1331&plus=0&fcui=190100&fcai=1427\u2026&ffli=54232&fpli=3003248&element=ftge_4780611&size=300x250&size100=300x250",
  "extra": {
    "canvas": true,
    "dataURL": "data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAABCAYAAADTjP5iAAAANklEQ\u20262HcBwfosVCoXklobsPSXQ3VBVVhZnBIiL3P\/5eNzNkJiICBz\/yFgEMMfxVAAAAAElFTkSuQmCC",
    "width": 18,
    "height": 1
  }
}```

and

```{
  "obj": "CanvasRenderingContext2D.prototype",
  "prop": "getImageData",
  "scriptUrl": "http:\/\/batch.theadex.com\/d\/199\/360\/s\/adex.js",
  "extra": {
    "canvas": true,
    "dataURL": "data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NMZWD4DwACnQFmmn3AvQAAAABJRU5ErkJggg==",
    "width": 1,
    "height": 1
  }
}```

I had to temporarily disable both [text length](https://github.com/EFForg/privacybadgerchrome/blob/3b32d0a61d6a45500b53e428d913b32fcbe0cb65/src/fingerprinting.js#L165-L169) (needs to be updated for drawImage, since it doesn't work with text) and [canvas width/height](https://github.com/EFForg/privacybadgerchrome/blob/3b32d0a61d6a45500b53e428d913b32fcbe0cb65/src/webrequest.js#L421) checks (both images above currently considered too small to count).

**Comment by cooperq** [comment] 2015-10-02 16:07
I guess we should add `drawImage` dection to our own canvas fingerprinting algorithms. @ghostwords any chance you have time for this?

**Comment by ghostwords** [comment] 2015-10-02 20:04
Yes, just not sure when.

To clarify, when I said I added `drawImage` to Chameleon, I meant I hacked it in temporarily just to see what's going on the page. To add it properly, I would want to understand what that script does a bit better, and to run Chameleon Crawler to see what happens when you add `drawImage` and adjust canvas width/height checks.

**Comment by gunesacar** [comment] 2015-12-01 00:57
I think this is canvas & cache based evercookie, not canvas fingerprinting. Check Samy's [evercookie code](https://github.com/samyk/evercookie/blob/dc3a19cf552ad9fbdecc693acac24afe155552c6/js/evercookie.js#L682) or read [How does the PNG caching work?](http://samy.pl/evercookie/) The only difference is that t4ft.de script uses GIF, instead of PNG.

The script draws an image loaded from http://c.t4ft.de/ckgif/ (or cache) into the canvas. The image, which is immediately cached, contains the RGB encoded user ID. Even if you remove your cookies or local storage, the script will draw the cached image into the canvas and read your ID from canvas (using `getImageData`).

This behavior is conditionally triggered and doesn't run for me at the moment, but I can see different GIF contents when I load the ckgif URL with different profiles. You can see the request to http://c.t4ft.de/ckgif/ on [HTTP Archive](http://httparchive.org/viewsite.php?u=http%3A%2F%2Fwww.pcgames.de%2F&l=Nov%201%202015#waterfall).

The script also uses ETag based evercookie. Base64 decoding the *ftgnetid* cookie content gives you the ETag value (thanks to light obfuscation.) For instance in the above [HTTP Archive example]((http://httparchive.org/viewsite.php?u=http%3A%2F%2Fwww.pcgames.de%2F&l=Nov%201%202015#waterfall)), ETag=71151108140103233, ftgnetid=NzExNTExMDgxNDAxMDMyMzM=.

**Comment by cooperq** [comment] 2015-12-02 22:32
Dang! Good work @gunesacar, we really need to start adding heuristics to detect other types of supercookies I guess.

**Comment by cooperq** [comment] 2016-11-01 20:14
detection: etag supercookies 
detection: session, db, other html5 storage
blocking: session, db, other html5 storage
blocking: etag?
detection: navigator plugins
blocking: navigator plugins

**Comment by ghostwords** [comment] 2020-11-06 18:13
Duplicate of #1558, #2136.

**Closed by ghostwords** 2020-11-06 18:13 UTC
Labels: enhancement, heuristic
