### ISSUE TITLE
AbortError: A request was aborted, for example through a call to IDBTransaction.abort. error

### ISSUE THREAD

**Issue by m4lk4** [EFForg/privacybadger#2379] opened 2019-06-04 11:22 UTC
AbortError: A request was aborted, for example through a call to IDBTransaction.abort.

**Comment by ghostwords** [comment] 2019-06-04 14:59
Hello and thanks for letting us know! This is some sort of Firefox bug that Privacy Badger will stop pestering you about after our next update.

**Comment by ghostwords** [comment] 2019-06-04 15:00
Closing as a duplicate of #2156.

**Closed by ghostwords** 2019-06-04 15:00 UTC
