### ISSUE TITLE
Remove URL Tracking /#Echobox

### ISSUE THREAD

**Issue by 2zzly** [EFForg/privacybadger#2905] opened 2023-08-15 16:38 UTC
Many sites like newscientist.com and telegraph.co.uk etc... use URL/#Echobox=[tracking number]

**Comment by ghostwords** [comment] 2023-08-15 21:18
Hello! Could you provide a bit more information about what this is and where we can see it happen? I just looked at a [random article](https://www.telegraph.co.uk/news/2023/08/15/rupert-murdoch-wives-elena-zhukova-jerry-hall-wendi-deng/) but I don't see "Echobox" anywhere in the page.

**Comment by 2zzly** [comment] 2023-08-20 14:11
It has to be a link from somewhere else, other than the main site. Facebook, Instagram etc... all add #Echobox to the end of the URL

**Comment by 2zzly** [comment] 2023-08-21 20:37
[https://www.facebook.com/newscientist](url)
[https://www.facebook.com/TELEGRAPH.CO.UK](url)

click on any post, it adds #Echobox= to the end of URL

**Comment by ghostwords** [comment] 2023-08-21 22:21
I'm confused now, is this an issue on `facebook.com` or on `telegraph.co.uk`? When you write "click on any post", where do I click?

**Comment by ghostwords** [comment] 2023-08-23 20:39
OK, I see that some outgoing links on Facebook include this tracking hash. For example, at this moment the second post on https://www.facebook.com/TELEGRAPH.CO.UK links to `https://www.telegraph.co.uk/films/0/actors-green-rider-celebrity-hollywood-excess/?utm_campaign=Echobox&utm_content=telegraph&utm_medium=Social&utm_source=Facebook#Echobox=1692802413`.

Is this a Facebook-specific thing, or does this happen on other sites?

**Comment by ghostwords** [comment] 2023-08-23 20:40
This might be a duplicate of #681.

**Closed** 2023-09-05 20:52 UTC
Labels: duplicate, enhancement, privacy
