### ISSUE TITLE
PB interferes with rendering on Meetup.com

### ISSUE THREAD

**Issue by bmeacham** [EFForg/privacybadger#1376] opened 2017-05-08 20:35 UTC
PB on Firefox 53.0.2 (32-bit) running on 64-bit Windows 7 Pro causes certain sites to display as if the CSS is not applied.  This problem appears on the following sites (and possbly others):

- https://www.meetup.com/
- https://melmagazine.com/if-you-speak-multiple-languages-do-you-need-multiple-therapists-462c7575e08b

The problem disappears when I disable PB.  

Attached is a screenshot of the problem on meetup.com.
![meetuponfirefox](https://cloud.githubusercontent.com/assets/17537744/25824117/d1313b88-3403-11e7-8f66-927809f9bd03.JPG)

**Comment by ghostwords** [comment] 2017-05-08 20:47
Does clicking "Disable Privacy Badger for This Site" on `meetup.com` also fix the problem?

**Comment by bmeacham** [comment] 2017-05-08 22:21
I have enabled Privacy Badger and restarted Firefox, but I do not see the PB icon on the menu bar, so I can't disable it for a particular site.  Meetup.com displays properly, but is PB actually running?

**Comment by ghostwords** [comment] 2017-05-08 22:28
If you visit `about:addons` and click on Extensions, do you see Privacy Badger listed and enabled?

**Comment by bmeacham** [comment] 2017-05-08 23:03
Yes.  Privacy Badger is listed and has two buttons, "disable" and "remove."

**Comment by ghostwords** [comment] 2017-05-08 23:06
The icon might be hidden ... You should be able to bring it back using Firefox's [Customize feature](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars).

**Comment by bmeacham** [comment] 2017-05-09 02:09
I have removed and then reinstalled PB.  Now it is enabled and I have the icon.  And, oddly, now the problematic sites render OK.  Any idea what happened?

**Comment by ghostwords** [comment] 2017-05-09 02:38
It seems that Privacy Badger learned to block something essential to `meetup.com`, maybe `meetupstatic.com`. Uninstalling and reinstalling probably reset your Privacy Badger's learning process.

**Comment by ghostwords** [comment] 2017-06-21 17:11
We might want to update [multi-domain first-parties](https://github.com/EFForg/privacybadger/issues/781) for `meetup.com`.

**Comment by ghostwords** [comment] 2017-06-22 15:53
The second URL in the original report above sounds like a duplicate of #1352.

**Closed** 2017-06-26 20:17 UTC
Labels: broken site, good volunteer task
