### ISSUE TITLE
Ugly cut messages in Opera

### ISSUE THREAD

**Issue by PinkLouie** [EFForg/privacybadger#1754] opened 2017-10-30 23:23 UTC
The messages are all around the web while using PB in Opera. Disconnect, for example, replaces this messages for a blank space. Can you do the same?

Thank you anyway. You extension is great!

![opera instant neo_2017-10-30_212133_www ghacks net](https://user-images.githubusercontent.com/30609937/32200407-9c488f4a-bdb8-11e7-83cf-a6e5de5d3758.png)

**Comment by ghostwords** [comment] 2017-10-31 00:08
Is this like #442 but with extra Opera-specific messaging? What do the messages say?

**Comment by PinkLouie** [comment] 2017-10-31 20:32
Full Message

![opera snapshot_2017-10-31_183214_www youtube com](https://user-images.githubusercontent.com/30609937/32247583-e4f25706-be69-11e7-87df-aca261eac961.png)

**Comment by ghostwords** [comment] 2017-11-07 16:00
Could you provide a couple of example pages where you see these messages?

**Comment by ghostwords** [comment] 2017-11-07 16:02
Seems like this is the Opera version of #907. Should be the same underlying issue. I'll mark it as a duplicate of #442.

**Closed by ghostwords** 2017-11-07 16:02 UTC

**Comment by ghostwords** [comment] 2017-11-08 17:15
Ah, yes, I think [Disconnect replaces blocked images and frames with blank images and frames](https://github.com/disconnectme/disconnect/blob/master/firefox/content/disconnect.safariextension/opera/chrome/scripts/background.js#L915-L920). Seems straightforward for us to do the same.
