### ISSUE TITLE
globalPrivacyControl Error with Firefox 

### ISSUE THREAD

**Issue by DrI-T** [EFForg/privacybadger#2771] opened 2021-05-29 12:09 UTC
I am using FF88.0.1 (ubuntu)
and I have the following error an all pages:
```
typeError: can't redefine non-configurable property "globalPrivacyControl"
```
even on <https://example.com/>

**Comment by ghostwords** [comment] 2021-06-01 16:16
Hello! What other extensions do you have installed?

**Comment by ghostwords** [comment] 2021-06-02 16:19
I can reproduce with the DDG extension in Firefox, but only in Firefox. Curious that this doesn't happen in Chrome. I wonder what changed since I don't think we had this conflict as of https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/531.

@dharb Any thoughts? Will this be fixed by https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/688?

**Comment by DrI-T** [comment] 2021-06-04 03:37
Hello Alexei,

I have a bunch of other apps : Duckduckgo privacy essential, foxytab
do you believe it can be a extention "conflict" w/ the duckduckgo one ?


Regards,
+Michel

Alexei ***@***.***> a écrit :

**Comment by ghostwords** [comment] 2021-06-15 21:21
Yes, it looks like this is caused by some change on DuckDuckGo's side. You could ignore this error as it should be harmless, you could wait for DDG to release the update with the fix, or you could disable the [Global Privacy Control](https://globalprivacycontrol.org/) signal in DDG (it'll still be sent by Privacy Badger).

Let me know if you have any questions.

**Closed by ghostwords** 2021-06-15 21:21 UTC
Labels: Firefox, broken extension
