### ISSUE TITLE
Remove automatic "back to top" from tracking domains list

### ISSUE THREAD

**Issue by sam0jones0** [EFForg/privacybadger#2051] opened 2018-06-05 09:47 UTC
On the settings page --> tracking domains list, you scroll down the list and move the tracking slider for each domain manually. Annoyingly, when you move the slider for a domain, you are auto-returned to the top of that list, meaning one has to re-scroll back down the list each time the slider is moved. Very frustrating when a large number of domains need adjustments to their tracking setting.

Chromium: Version 66.0.3359.181 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by ghostwords** [comment] 2018-06-05 17:01
Duplicate of #1581.

May I ask why you find yourself manually toggling Privacy Badger's sliders? Privacy Badger is meant to be an install-and-forget, no-configuration necessary extension.

**Closed by ghostwords** 2018-06-05 17:01 UTC
Labels: bug, duplicate, ui

**Comment by sam0jones0** [comment] 2018-06-06 14:38
Thanks for pointing out this is a duplicate.

If the feature is included, it's going to used... I found myself looking through the extensions capabilities and fine tuning the presented URLs, I guess I like settings.

**Comment by ghostwords** [comment] 2018-06-06 15:30
We are working on making Privacy Badger's nature more clear, by updating how we describe Privacy Badger to new users (#1930) and in the app stores (#2017), by moving the tracking domains list behind an acknowledgement (#1804), and, coming soon, by shipping Privacy Badger to new users with a pre-trained database (#1947). We want it to be clear that Privacy Badger learns on its own, you should just let it do its thing, but here is what you do when a site does get broken.

We haven't gotten to where we want to be yet. The sliders are still very prominent and our explanations are easy to ignore. We are going to want to redesign the popup at some point, probably to hide the sliders by default, replacing them with some sort of summary of site activity.

Note that if you do customize sliders to block more aggressively, it's easy to create problems for yourself: #2021. Also see https://github.com/EFForg/privacybadger/issues/1422#issuecomment-348229277 for a similar conversation in the past.
