### ISSUE TITLE
localhost pages becoming erratic even when disabled for local sites

### ISSUE THREAD

**Issue by rexxmagnus** [EFForg/privacybadger#1536] opened 2017-07-28 07:50 UTC
I'm working on a web app that uses asp.net (and its associated authentication cookies, running on localhost) but no external services. Privacy Badger seems to cause problems with those pages loading in firefox. Clicking a link to a new page often results in the address bar changing but the page either appearing blank or not changing at all.
It also causes svgs loaded using <object> and running their own integrated javascript to load slowly.
Disabling the plugin for localhost seems to have no effect. I only noticed a return to normal service after disabling the plugin entirely.

**Comment by cowlicks** [comment] 2017-07-28 08:23
Would you happen to have a  sample svg I can test with? (I think #1221 would be useful here)

**Comment by rexxmagnus** [comment] 2017-07-28 08:40
Unfortunately I can't post the code for it as it's something my company is working on, but I think it's a minor symptom of the cause, given that entire pages fail to render before the point at which the svgs are triggered.

Our svgs are relatively plain, however, and trigger an onload event that runs javascript inside them to modify their dom. I think they may be rendering late because the entire page has been slowed.

When pages don't load, the get request fires but the response (in firefox's inspector) is completely empty. The response headers have come back and seem completely normal. If I reload the page after a failure, the headers are identical but the page shows and the response body is present.

Request:
Host: localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost/GROWebApp/targets.aspx?
Cookie: [data removed]
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

Response:
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Fri, 28 Jul 2017 08:33:09 GMT
Content-Length: 39039

**Comment by ghostwords** [comment] 2017-07-28 13:45
This seems like a duplicate of #1438, which is caused by a Firefox bug with the following Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1373776.

Could you double-check that you run into the same bug by (temporarily) disabling all other add-ons (including Privacy Badger), installing [this test add-on](https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip) I made, and verifying that the problem occurs with the add-on and goes away without it?

To load the above add-on in Firefox, unzip the archive somewhere, visit about:debugging, click on Load Temporary Add-on, and pick the manifest.json file inside the unzipped folder.

**Comment by rexxmagnus** [comment] 2017-07-28 14:56
Sadly it doesn't seem to trigger the same behaviour. Our site does however have  this running on every page, and I'm not sure whether that would be interfering with your test case:
window.addEventListener('beforeunload', function () { });

I had to add it because of the way we are using a busy cursor when navigating from one page to the next - it was keeping the page state cached (busy cursor and all) when you went back to it, so I had to add that line to trick the DOM into refreshing. I have no idea why it works!

**Comment by rexxmagnus** [comment] 2017-07-28 14:56
Sadly it doesn't seem to trigger the same behaviour. Our site does however have  this running on every page, and I'm not sure whether that would be interfering with your test case:
window.addEventListener('beforeunload', function () { });

I had to add it because of the way we are using a busy cursor when navigating from one page to the next - it was keeping the page state cached (busy cursor and all) when you went back to it, so I had to add that line to trick the DOM into refreshing. I have no idea why it works!

**Comment by ghostwords** [comment] 2017-07-28 15:34
That's strange, since your symptoms and browser strongly suggest the same issue. It could be a matter of timing; the Mozilla employee on Bugzilla is still unable to reproduce any of our bug scenarios, whereas most reporters are able to reproduce consistently.

**Comment by ghostwords** [comment] 2017-07-28 15:36
The symptoms being that navigating in a site updates the URL in the address bar but fails to update the page, and that the mere presence of Privacy Badger is enough to trigger the bug, disabling Badger on the site does not help.

**Comment by ghostwords** [comment] 2017-07-28 15:37
Would you be able to create a stripped-down webpage you can reproduce the issue on with Privacy Badger, and share that page with us in whatever form?

**Comment by rexxmagnus** [comment] 2017-07-28 15:52
I wouldn't really know where to start. This is quite a big webapp with a huge amount of javascript, and it would probably take me some hours to test stripping it down to see if I can replicate it in something that I can post.

**Comment by ghostwords** [comment] 2017-07-28 15:57
If it's too much work, no problem. My hunch is this is the same issue as https://github.com/EFForg/privacybadger/issues/1438 (URL updates but page doesn't on navigation, disabling for the site doesn't help, Firefox-only), and we just have trouble replicating for the same reason the Mozilla person has trouble replicating on their end.

**Comment by ghostwords** [comment] 2017-08-05 23:06
According to https://github.com/EFForg/privacybadger/issues/1295#issuecomment-315998618, you should be able to get rid of this issue in your Firefox profile without having to start over from scratch by [refreshing your Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and then reinstalling all your add-ons.

**Comment by ghostwords** [comment] 2017-08-17 14:47
This might be fixed now that Firefox 55 reached stable.

**Closed** 2017-08-18 17:44 UTC
Labels: bug, duplicate, Firefox
