### ISSUE TITLE
Not replacing Twitter t.co tracking links when logged in to twitter

### ISSUE THREAD

**Issue by locky3** [EFForg/privacybadger#2475] opened 2019-10-07 20:21 UTC
Issue with Privacy Badger v 2019.9.23 and Chrome 77.0.3865.90 64-bit on twitter.com

Privacy Badger no longer replaces the t.co tracking links on twitter while logged in.  Being logged in also forces the new Twitter interface.  When I tested in incognito mode twitter loaded the old interface version of the website and privacy badger replaced the t.co tracking links with the destination URL as expected.

**Comment by ghostwords** [comment] 2019-10-07 20:37
Hello and thanks for the report! Is this and #1886 the same issue?

**Comment by locky3** [comment] 2019-10-07 20:59
I think it is.  I am having this problem on twitter.com not mobile.twitter.com.  I never visited mobile.twitter.com in the past but rugk says the new default GUI is the same as what the mobile.twitter interface was when #1886 was opened (https://github.com/EFForg/privacybadger/issues/1886#issuecomment-486093841).  Going to mobile.twitter.com today does bring me to the same interface as twitter.com when logged in so it probably is the same issue.

**Comment by ghostwords** [comment] 2019-11-13 15:20
Closing as a duplicate of #1886.

**Closed by ghostwords** 2019-11-13 15:20 UTC
Labels: bug, first-party
