### ISSUE TITLE
Blocks Images from Loading on app.wire.com

### ISSUE THREAD

**Issue by liocalset** [EFForg/privacybadger#1170] opened 2017-01-29 15:50 UTC
Hi,

When Privacy Badger version 2017.1.26.1 is enabled under Firefox 50.1.0, images won't load in the wire webapp: wireapp/wire-webapp#689

I've tried the: "Disable Privacy Badger for This Site" option, but the only way to get images to load in the wire web app is to completely disable the extension in _about:addons._ Privacy Badger isn't blocking any trackers as there are no trackers to block. This problem was introduced very recently, possibly in this latest version of Privacy Badger or the one before it.

Thanks!

**Comment by ghostwords** [comment] 2017-05-03 22:53
Quoting from the above `wire-webapp` bug report:

Viewing the FF browser console, here are the errors I just got when sending a picture to a friend:

`Failed to load ‘https://prod-nginz-https.wire.com/conversations/a81e40f5-63c8-4b21-a1ef-6585af0dd526/otr/assets/bdb2c02d-8853-487b-8b24-c44225c702f2?access_token=o81CQHLqkMT_PurV9n8HUwflR1eMAMXPe3NUHyy6aoFfXBa2EXraElkU8_vlkogzGTw2WAusBhxv6brTl36bBA==.v=1.k=1.d=1485531707.t=a.l=.u=3c2e2553-6e13-4f65-9fb1-4358c83e6d93.c=6531907568139570110&forceCaching=true’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.`

`Failed to load ‘https://prod-nginz-https.wire.com/assets/a20bc881-cdad-4f3f-b222-4fb71c9e68d1?access_token=o81CQHLqkMT_PurV9n8HUwflR1eMAMXPe3NUHyy6aoFfXBa2EXraElkU8_vlkogzGTw2WAusBhxv6brTl36bBA==.v=1.k=1.d=1485531707.t=a.l=.u=3c2e2553-6e13-4f65-9fb1-4358c83e6d93.c=6531907568139570110&conv_id=6bf01ba2-f5b5-4bbc-823e-222de6cf6793&forceCaching=true’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.`

**Comment by ghostwords** [comment] 2017-05-03 22:54
I'll mark this as a duplicate of #1144.

**Closed by ghostwords** 2017-05-03 22:54 UTC
Labels: broken site, duplicate, Firefox
