### ISSUE TITLE
AbortError: A request was aborted, for example through a call to IDBTransaction.abort.

### ISSUE THREAD

**Issue by cjcarey67** [EFForg/privacybadger#2373] opened 2019-05-27 16:29 UTC
I just started receiving the above message from PB. What does it mean and what do I do about it?

**Comment by ghostwords** [comment] 2019-05-27 16:45
Hello and thanks for letting us know!

Are you using Firefox? This seems like some kind of IndexedDB (how Firefox stores extension data) problem, almost certainly unrelated to Privacy Badger.

Privacy Badger just happens to surface some of these errors to the user, while other extensions silently ignore them. But if we can't do anything about a particular error, we should ignore it too.

Marking as a duplicate of #2156.

**Comment by ghostwords** [comment] 2019-05-27 16:46
You could ask Firefox developers as to what this error means and if there is anything you can do it about it. Some of these errors may be caused by your disk being nearly full, for example.

**Comment by ghostwords** [comment] 2019-05-28 19:29
Closing as a duplicate.

**Closed by ghostwords** 2019-05-28 19:29 UTC
Labels: Firefox, bug, duplicate
