### ISSUE TITLE
sucdn.sphereup.com breaks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1138] opened 2017-01-14 06:51 UTC
http://grammarist.com/spelling/council-counsel/

`sucdn.sphereup.com` breaks magnifying glass image on left.

**Comment by terrorist96** [comment] 2017-08-18 19:21
Should I make a PR to add sucdn.sphereup.com to the yellowlist? @ghostwords

**Comment by ghostwords** [comment] 2017-08-18 19:29
I'd like to have a few pages (ideally three, each from a different domain) where you see tracking from the domain in question (here `sucdn.sphereup.com`).

**Comment by terrorist96** [comment] 2017-08-18 19:31
No dice.
![image](https://user-images.githubusercontent.com/12802056/29474569-39c79130-842a-11e7-8c58-acd0f2cfc984.png)

**Comment by terrorist96** [comment] 2017-08-18 19:31
Found some without the subdomain though:
![image](https://user-images.githubusercontent.com/12802056/29474597-5d220ae8-842a-11e7-9f06-8c4bd0459ef3.png)

**Comment by ghostwords** [comment] 2017-08-18 19:34
Yep, makes sense, the parent domain cascades to children. Should rephrase "tracking from the domain in question" to "tracking from the domain in question, or any of its parent domains."

**Comment by ghostwords** [comment] 2017-08-18 19:37
I've got some documentation for getting useful info [here](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) linked from my "model" yellowlist PR (https://github.com/EFForg/privacybadger/pull/1543)

**Comment by ghostwords** [comment] 2021-08-20 13:59
Closing as duplicate of #1344.

**Closed by ghostwords** 2021-08-20 13:59 UTC
Labels: broken site
