### ISSUE TITLE
Privacy Badger 2.x not displaying sliders

### ISSUE THREAD

**Issue by VikDeshmukh** [EFForg/privacybadger#1098] opened 2016-12-19 02:55 UTC
I have the new 2.x series of Privacy Badger installed and it is not showing any of the sliders, or the count of trackers detected, unlike the old version although clicking on the toolbar button tells me that it detected trackers on this page. Clicking the settings icon also does nothing. This issue is very similar to an older issue posted last year: https://github.com/EFForg/privacybadger/issues/524 which I found via Google.

**Comment by wolf6243** [comment] 2016-12-19 20:07
I've got the same problem with Privacy Badger v2 not showing any of the sliders, or the count of trackers detected. Hope this is sorted soon.
![privacy badger 1](https://cloud.githubusercontent.com/assets/18146947/21327396/cda21bd6-c626-11e6-9536-ad212dd58600.jpg)

**Comment by tl87** [comment] 2016-12-20 06:34
Hello,
I have the same problem with my Privacy Badger, please see attached picture below:
![pb](https://cloud.githubusercontent.com/assets/5989314/21340389/6af5feb6-c686-11e6-844c-b9992a3c794b.png)
Also to note, I've noticed that if you turn on JavaScript and/or Cookies, it sometimes fixes the problem, and Privacy Badger is working as normal, however in previous versions, you did not have to turn on JavaScript and/or Cookies to get it to work.

**Comment by skorokithakis** [comment] 2016-12-20 15:14
Same here, I even reinstalled and the sliders still won't show.

**Comment by cementboy** [comment] 2016-12-29 17:21
Ubuntu 16.04. Privacy Badger 2016.12.15.1.  Same problem.
![pb](https://cloud.githubusercontent.com/assets/22922694/21549594/23753978-cdeb-11e6-8020-615727f7a9c8.jpg)

**Comment by cooperq** [comment] 2017-01-05 02:50
hmm, this looks related to #1101 closing in favor of that.

**Comment by ghostwords** [comment] 2017-01-06 18:15
>I've noticed that if you turn on JavaScript and/or Cookies, it sometimes fixes the problem, and Privacy Badger is working as normal, however in previous versions, you did not have to turn on JavaScript and/or Cookies to get it to work.

@cooperq Does disabling JavaScript in Firefox break Web Extensions? Another report [here](https://github.com/EFForg/privacybadger/issues/1058#issuecomment-267842902).

>If the JavaScript is disabled, the Privacy Badger's UI looks like the screenshot above. If the JavaScript is enabled, the UI looks OK.

**Comment by groovecoder** [comment] 2017-01-07 20:52
Hmm ... our [mozilla/blok Web Extension](https://github.com/mozilla/blok) doesn't execute its background script when JavaScript is disabled. But our [codesy/widgets Web Extension](https://github.com/codesy/widgets) content scripts still work. So maybe it's only background scripts that don't work with JavaScript disabled?

**Comment by ghostwords** [comment] 2017-01-09 19:22
Opened a Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1329731

**Comment by cooperq** [comment] 2017-01-09 23:27
We should confirm that this is the case in privacy badger as well.

**Comment by ghostwords** [comment] 2017-02-08 15:04
Closing this as duplicate of #1058. If your problem seems unrelated to having disabled JavaScript in Firefox directly or via addons (RequestPolicy, QuickJS, maybe NoScript), please open a new issue.

**Closed by ghostwords** 2017-02-08 15:04 UTC
Labels: bug, firefox, High priority
