### ISSUE TITLE
Privacy badger does not update domains that are not tracking anymore

### ISSUE THREAD

**Issue by Titan-C** [EFForg/privacybadger#1827] opened 2018-01-09 22:34 UTC
Recently, in the Sphinx-Gallery documentation we integrated badges from the mybinder project. As this badges were originating from a 3rd party which had installed Google Analytics, privacy badger fired and blocked the domain.
After reporting the issue to the mybinder project https://github.com/jupyterhub/binderhub/issues/379
They first moved the images to subdomain(which privacy badger also marked as tracker), and then they understood Google Analytics was active for all subdomains. When they fixed that to avoid tracking, privacy badger in my browser still marked the now non-tracking domain as tracking. see issue https://github.com/sphinx-gallery/sphinx-gallery/pull/334
Nevertheless, on a clean installation of privacy badger the domain would not be considered as tracking anymore.

Is it possible for privacy badger to stop blacklisting domains, when it recognizes that they are not tracking anymore?

**Comment by ghostwords** [comment] 2018-01-09 22:45
I think this came up before in #882.

Great discussion and resolution in the binderhub issue linked above. Thanks for referencing it!

Exactly, as you point out, while you fixed the problem going forward, existing Badgers will not know to stop blocking the domain question.

**Comment by ghostwords** [comment] 2018-01-09 22:48
As a workaround, if the domain's owner is able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements on that domain, posting the policy on the domain will tell Privacy Badger to always allow loading of resources from the domain.

**Comment by ghostwords** [comment] 2018-01-09 22:50
I'll close this as a duplicate of #882 for now.

**Closed by ghostwords** 2018-01-09 22:50 UTC
Labels: DNT policy, duplicate, heuristic, question
