### ISSUE TITLE
Privacy Badger cannot report problems in Firefox with NoScript

### ISSUE THREAD

**Issue by keybounce** [EFForg/privacybadger#1164] opened 2017-01-27 21:38 UTC
Attempting to leave feedback on broken sites with privacy badger gives an error message.

Firefox version ESR 45.7.0 (up to date)

**Comment by ghostwords** [comment] 2017-01-27 21:51
Is this still an issue after updating to Privacy Badger version 2017.1.26.1?

**Comment by contranym** [comment] 2017-02-15 18:23
Yes. Using Privacy Badger 2017.1.26.1 on Firefox 51.0.1 (64-bit).

**Comment by cooperq** [comment] 2017-02-27 20:53
I have heard this from several other people as well.

**Comment by ghostwords** [comment] 2017-03-28 17:43
Sorry, just got to looking into this. I am unable to reproduce. @contranym, is this still an issue, and if yes, does it happen if you disable all other addons?

Is the error message the following? `Oops. Something went wrong.`

@cooperq Is/was there a lull in error reports from Firefox user agents?

**Comment by contranym** [comment] 2017-03-29 04:06
Yes, still an issue, but ONLY with NoScript (in my environment). Reporting is successful with all add-ons disabled, and with all of my installed add-ons except NoScript enabled. You are correct about the error message. 

Test conducted with this GitHub page using Firefox 52.0.2 (64-bit), NoScript 5.0.2, Privacy Badger 2017.3.22. Sorry about all the false reports on the GitHub page, I commented them as bug tests.

**Comment by ghostwords** [comment] 2017-05-04 00:12
Possibly related to #1058.

**Comment by ghostwords** [comment] 2017-06-15 22:25
@keybounce @contranym Firefox 54 just got released; could you check if it solved the problem of disabling JavaScript breaking WebExtensions?

**Comment by contranym** [comment] 2017-06-18 16:58
Seems to be working as expected now, Privacy Badger version 2017.6.13.1, Firefox 54.0 (64-bit), NoScript 5.0.5.

**Comment by ghostwords** [comment] 2017-06-18 17:32
Excellent, resolving!

**Closed by ghostwords** 2017-06-18 17:32 UTC
Labels: bug, Firefox, high priority

**Comment by keybounce** [comment] 2017-06-19 02:09
Sadly, I use 52 ESR, not 54. (Just got switched).

... I really, really dislike this new search bar interface. The old one gave me more choices, and the URL is far more important than the title. Not to mention being compressed into one line makes it harder to read.

At least the ESR version kept plug-ins turned on for another year. I can't figure out how to enable/disable multi-threading, and need to figure that out for Firebug.

On 2017-06-15, at 3:25 PM, Alexei <notifications@github.com> wrote:

> @keybounce @contranym Firefox 54 just got released; could you check if it solved the problem of disabling JavaScript breaking WebExtensions?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce
