### ISSUE TITLE
Unable to disable on site in Firefox 57

### ISSUE THREAD

**Issue by mrboring** [EFForg/privacybadger#1809] opened 2017-12-15 09:49 UTC
Hi

Windows 10 x64
Firefox 57.0.2 x64 (same behaviour on all Firefox 57 releases)
Installed extentions: Privacy Badger, uBlock Origin, Stylish
Test site: http://www.bbc.co.uk/news (same behaviour on other sites)

When using a "Private Window" Privacy Badger does not work correctly. The slider list is missing and "Disable Privacy Badger for This Site", and the other buttons, do not work. I tested this in a normal window and in a "Private Window". The normal window worked fine. Below are screen captures for both.

**Normal window - http://www.bbc.co.uk/news**

![image](https://user-images.githubusercontent.com/5991977/34036252-80aec848-e17c-11e7-862f-c50dc8ebba40.png)

**Private Window - http://www.bbc.co.uk/news**

![image](https://user-images.githubusercontent.com/5991977/34036274-948512aa-e17c-11e7-9336-cd335a7486b8.png)

I'm assuming this a bug.

Thanks.

**Comment by ghostwords** [comment] 2017-12-15 14:21
It is a bug, apologies! Privacy Badger's UI doesn't yet work in Private Browsing windows in Firefox.

Marking as a duplicate of #1060.

**Closed by ghostwords** 2017-12-15 14:21 UTC
Labels: bug, duplicate, Firefox
