### ISSUE TITLE
Preferences not working on nightly

### ISSUE THREAD

**Issue by CircleCode** [EFForg/privacybadger#2218] opened 2018-11-20 19:08 UTC
when opening PB preferences, I get a blank page, and the console shows this error:
```
TypeError: backgroundPage is null; can't access its "require" property (options.js:34:5)
```

**Comment by ghostwords** [comment] 2018-11-21 15:50
Hello! I am unable to reproduce this with Nightly version 65.0a1 (2018-11-21) on Linux. Is this still an issue? Does this happen in a fresh profile with a new Privacy Badger installation? Does this happen with [Privacy Badger installed from source](https://github.com/EFForg/privacybadger/blob/master/doc/develop.md#install-from-source)?

**Comment by ghostwords** [comment] 2018-11-26 19:45
Let me know if you have any more information. Closing for now.

**Closed by ghostwords** 2018-11-26 19:45 UTC
Labels: Firefox, bug, unable to reproduce

**Comment by CircleCode** [comment] 2018-11-27 05:58
@ghostwords does not seem to be reproducible on an empty profile… so seems perfect to close it for now
