### ISSUE TITLE
Shows site "" (empty string) as blocked

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadger#2081] opened 2018-06-29 21:21 UTC
In the settings `/skin/options.html#tab-tracking-domains` I can see this:

![grafik](https://user-images.githubusercontent.com/11966684/42115431-2096e2bc-7bf3-11e8-8e5b-812fee782846.png)

The first entry is quite strange. 

Firefox 61

**Comment by ghostwords** [comment] 2018-06-29 21:28
Might be a duplicate of #1447.

Could you run the following script in that Badger's background page console and share what it prints out?
```javascript
(function () {
  console.log("**** ACTION_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('action_map')._store[""], null, 2))
  console.log("**** SNITCH_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('snitch_map')._store[""], null, 2))
}());
```
To get to the background page console in Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by rugk** [comment] 2018-06-30 09:35
Yeah, might be a dupe.

``` 
11:34:24.268 **** ACTION_MAP for '' debugger eval code:2:3
11:34:24.269 {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1523533671330
} debugger eval code:3:3
11:34:24.269 **** SNITCH_MAP for '' debugger eval code:4:3
11:34:24.269 [
  "[…].fr",
  "[…].at",
  "mozilla.org"
] debugger eval code:5:3
11:34:24.266 undefined
```

**Comment by ghostwords** [comment] 2018-07-02 16:51
I wonder where on mozilla.org this happened. Closing as a duplicate. Feel free to delete the blank domain from the options page; it may return though.

**Closed by ghostwords** 2018-07-02 16:51 UTC

**Comment by rugk** [comment] 2018-07-02 17:15
Drop me a mail at the address listed in my GitHub profile and I can give you the two other URLs I've "*****"ed above. If that is useful to you.
