### ISSUE TITLE
*.jwpsrv.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1564] opened 2017-08-08 00:02 UTC
www.investopedia.com/terms/e/ema.asp

`videos-f.jwpsrv.com` breaks video on right.

![image](https://user-images.githubusercontent.com/12802056/29050647-4ee180c6-7bab-11e7-9590-1cf57121d74d.png)

**Comment by terrorist96** [comment] 2017-08-14 19:00
https://venturebeat.com/2012/10/31/google-earth-adds-new-3d-imagery-in-21-cities-to-its-11000-guided-tours-of-our-planet/

`videos-f.jwpsrv.com`

Video at bottom (Fender Is Restringing Music Lessons For Wannabe Guitar Masters)

related to #1030 ?
@ghostwords

**Comment by ghostwords** [comment] 2017-08-14 20:13
Thank you! I'll take a look in a few days. By the way, I'll do a yellowlist update next Monday, releasing a bunch of fixes together.

**Comment by ghostwords** [comment] 2017-08-17 21:16
I see resources from `assets-jpcust.jwpsrv.com` ([here](https://www.digitaltrends.com/desktop-computer-reviews/dell-inspiron-5675-review/) and [here](http://www.thekitchn.com/10-amazing-ways-to-turn-a-can-of-tuna-into-a-meal-247281), for example), but I don't know how to get Privacy Badger to see tracking from `assets-jpcust.jwpsrv.com`.

**Comment by terrorist96** [comment] 2017-08-18 18:00
Yellowlist?

**Comment by ghostwords** [comment] 2017-08-18 18:03
Probably, I would like to understand where the tracking comes from first. Can you reproduce `jwpsrv.com` getting blocked with a fresh profile?

**Comment by terrorist96** [comment] 2017-08-18 18:39
No. Might need another purge to fix incorrectly blocked sites?
Though I did manage to find something else breaking the video from investopedia (first post). I'll make another issue.

**Comment by terrorist96** [comment] 2017-09-11 23:58
http://www.wnd.com/2017/09/tidal-wave-of-support-for-colorado-baker-hits-supreme-court/

**Comment by terrorist96** [comment] 2017-09-13 02:30
From #1030, still broken:
https://theintercept.com/2017/01/18/trump-education-nominee-betsy-devos-lied-to-the-senate/
http://www.myrecordjournal.com/news/state/9990595-154/malloy-on-increasing-pistol-permit-fees-im-not-anti-gun.html
http://www.iflscience.com/editors-blog/the-finalists-from-the-sony-world-photography-awards-2017-are-absolutely-astonishing/
http://www.wnd.com/2016/04/trump-erupts-as-cruz-sweeps-colorado-without-votes/
https://www.sayanythingblog.com/entry/video-legislature-sends-constitutional-carry-bill-governor-doug-burgum/
http://www.thekitchn.com/how-to-make-hummus-from-scratch-cooking-lessons-from-the-kitchn-107560
https://www.seeker.com/new-spider-species-is-named-after-harry-potter-sorting-hat-2143331899.html
https://www.reviewjournal.com/news/news-columns/victor-joecks/nevadans-for-background-checks-shifts-blame-for-20m-mistake/
@ghostwords

**Comment by terrorist96** [comment] 2017-09-14 21:21
http://www.businessinsider.com/ethereum-price-plunging-2017-9

**Comment by terrorist96** [comment] 2017-09-20 04:18
http://elitedaily.com/social-news/android-users-dont-fret-youll-able-make-long-snapchat-vids-eventually/2024379/

**Comment by ghostwords** [comment] 2017-09-24 17:08
I see `jwpsrv.com` assets, I can play all the videos, I don't see any tracking from `jwpsrv.com`. We should probably make Badgers forget about this one.

What is your [debug output](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) for "jwpsrv"?

**Comment by ghostwords** [comment] 2017-09-24 17:23
Should also forget about `jwplayer.com` domains ... I see error reports for those too, but can't reproduce tracking.

**Comment by terrorist96** [comment] 2017-09-24 22:51
```
**** ACTION_MAP for jwpsrv
VM436:5 assets-jpcust.jwpsrv.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1495215648132,
  "userAction": ""
}
VM436:5 hls-jp.jwpsrv.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492739069494,
  "userAction": ""
}
VM436:5 jwpsrv.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492967314366,
  "userAction": ""
}
VM436:5 videos-f.jwpsrv.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1495236529324,
  "userAction": ""
}
VM436:7 **** SNITCH_MAP for jwpsrv
VM436:9 jwpsrv.com [
  "digitaltrends.com",
  "thekitchn.com",
  "kgwn.tv"
]
```

**Comment by terrorist96** [comment] 2017-11-03 01:08
https://www.mediaite.com/tv/clinton-says-a-president-shouldnt-point-fingers-amid-tragedies-after-she-blasted-the-nra-for-vegas/

**Comment by terrorist96** [comment] 2017-11-06 02:29
http://seahawkswire.usatoday.com/2017/11/05/twitter-reacts-as-seahawks-kicker-blair-walsh-misses-three-consecutive-fgs/

**Comment by terrorist96** [comment] 2017-11-18 19:54
https://www.snopes.com/marijuana-grower-hiding-law-enforcement/

**Comment by johnBartos** [comment] 2017-12-08 21:02
@ghostwords Have you pushed any fixes for this? `video-f.jwpsrv`, our Fastly video delivery CDN, is being blocked. Breaks non-ad videoplayback for our users and a resolution would be great. Check `steveharvey.com`'s video for an example.

**Comment by ghostwords** [comment] 2017-12-08 22:25
I'll try to get this fixed with the next Privacy Badger update.

**Comment by johnBartos** [comment] 2017-12-08 22:36
@ghostwords Thanks a lot for the quick update 🥇

**Comment by terrorist96** [comment] 2017-12-27 18:48
https://screengrabber.deadspin.com/deandre-hopkins-makes-a-catch-to-remember-1821574335/amp

**Comment by terrorist96** [comment] 2018-01-19 01:25
https://www.snopes.com/tide-pod-challenge/

**Comment by ghostwords** [comment] 2018-01-22 16:55
Apologies, I missed this for today's update. I will try to get this done and deployed with the next update, which should happen in a few days.

**Comment by terrorist96** [comment] 2018-01-25 22:56
http://www.nationalreview.com/article/455683/anthony-kennedy-swing-vote-supreme-court-we-need-him-alive

**Closed** 2018-01-30 22:26 UTC
Labels: broken site, migrations, unable to reproduce
