### ISSUE TITLE
An unexpected error occurred in Firefox 71 in Fedora 31

### ISSUE THREAD

**Issue by xundeenergie** [EFForg/privacybadger#2522] opened 2019-12-11 10:11 UTC
After upgrade to Firefox 71 i get "An unexpected error occurred"

Maybe it's the same problem as with passff Add-on. Which will not work any longer.
https://github.com/passff/passff/issues/427
The problem seems to be a compiler-issue. It works in Firefox 71 compiled with gcc, but not with Firefox compiled with clang.

Just a hint... maybe it's the same problem here.

**Comment by valsu** [comment] 2019-12-11 13:49
I too run Firefox 71 on Fedora 31 and have the same problem with Badger. It worked flawlessly with FF 70.

**Comment by ghostwords** [comment] 2019-12-11 17:27
This is a Firefox (gcc?) bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1601365

Duplicate of #2474.

**Closed by ghostwords** 2019-12-11 17:27 UTC
