### ISSUE TITLE
overblocking of *.simplyedit.io

### ISSUE THREAD

**Issue by mjrider** [EFForg/privacybadger#1069] opened 2016-12-14 15:21 UTC
SimplyEdit is a javascript application which applies the website content in the browser.
Because of the Cloudflare cookie privacybadger blocks it. The result is an empty webpage

example websites using it:
- https://simplyedit.io
- https://www.muze.nl/

dns names:
- cdn.simplyedit.io
- canary.simplyedit.io
- beta.simplyedit.io

disclaimer: i'm one of the developers

**Comment by KidPluto** [comment] 2016-12-14 22:08
Looked at both sample links.  Not able to reproduce.

Windows 7 & PB v2016.12.8 | Firefix 50.1.0 and Chrome 54.0.2840.99

**Comment by mjrider** [comment] 2016-12-16 08:29
i will ask the people who reported this to be to add additional information about the blocking and which os/browser/plugin combo's they are using
on a browser where

**Comment by mjrider** [comment] 2016-12-16 09:08
extra information:
i just tried to reproduce on a clean browser profile, and found a difference between a computer wit was blocking cdn.simplyedit.io and the clean browser.
We published a DNT policy after we discovered that privacybadger was blocking our cdn. Clean installs show a DNT logo beside it and are allowed. Visiters who visited a site with simplyedit before we published the policy do not show the logo. and after visiting a few sites, it starts blocking simplyedit. 

Does Privacy badger recheck for a dnt policy after a while?

**Comment by alexristich** [comment] 2016-12-16 10:02
@mjrider Glad to hear you've published the DNT policy. Yup, Privacy Badger rechecks for DNT policy every 7 days for a given domain, so for everyone who is using the extension, they should see the updated status within 7 days from when you added the policy.

I'll go ahead and close this issue for now, though do post here if you still hear reports of any issues after about a week has passed. Also, we are looking at ways to improve the heuristic to allow CDNs to operate with minimal interruption. Still very much a work in progress here though!

**Closed by alexristich** 2016-12-16 10:02 UTC

**Comment by ghostwords** [comment] 2018-04-28 16:43
Related: #1237.
