### ISSUE TITLE
Improve support for peers on local network in WebRTC applications

### ISSUE THREAD

**Issue by Zythyr** [EFForg/privacybadger#1967] opened 2018-04-15 19:27 UTC
When two peers on the same local network are trying to connect in an WebRTC application, I see the following error in console: `ICE failed, your TURN server appears to be broken, see about:webrtc for more details `

After troubleshooting, I figured out the issue is related to Privacy Badger. PB has globally overridden the following variables from their default value as listed here: https://wiki.mozilla.org/Media/WebRTC/Privacy. 

```
media.peerconnection.ice.default_address_only;true 
media.peerconnection.ice.no_host;true 
```

You can test this issue on this demo page for a WebRTC application that does NOT use a TURN server as a relay and relies solely on direct peer to peer connection. https://simplewebrtc.com/filetransfer 

For peers on local network trying to connect directly in a WebRTC application, Privacy Badger extension has to be fully disabled. Selecting "_Disable Privacy Badger for This Site_" does NOT resolve the issue because the modified variables are global to the browser. 

This issue happens both in Firefox and Chrome.

**Comment by ghostwords** [comment] 2018-04-15 19:40
I'll mark this as a duplicate of #1099. Let me know if this is not the case.

**Closed by ghostwords** 2018-04-15 19:40 UTC

**Comment by ghostwords** [comment] 2018-04-16 22:04
@Zythyr As a workaround, could you try installing [WebRTC Network Limiter](https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia) and using it to overwrite Privacy Badger's setting? Let me know if this works for you.
