### ISSUE TITLE
Unable to connect Google Drive via Google account authentication in BrainTool

### ISSUE THREAD

**Issue by tconfrey** [EFForg/privacybadger#2729] opened 2021-01-07 16:35 UTC
My extension, [BrainTool](https://chrome.google.com/webstore/detail/braintool/fialfmcgpibjgdoeodaondepigiiddio), requires users to authenticate to their Google account to allow data to be saved to a Google Drive file. Having Privacy Badger installed causes calls to the google api to fail silently. I would like to automatically detect that Badger is installed and warn users of the need to whitelist.

Is there some page visible change Badger makes that I can look for from my extensions content script (eg a DOM addition)? From some research I see that if you mark some resource in your manifest as [Web Accessible](https://developer.chrome.com/docs/extensions/mv2/manifest/web_accessible_resources/) then I can query a url for its existence (eg chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/icons/badger-16.png) thus indicating Badger is present. Any other ways I can check for the Badger?

Thanks for any help.

**Comment by ghostwords** [comment] 2021-01-07 17:32
Hello and thanks for getting in touch!

This sounds like a duplicate of #137. Does moving the slider for `accounts.google.com` to "green" work around the problem?

Instead of trying to detect the presence of Privacy Badger, I suggest detecting when authentication fails and showing a helpful error message that says something about making sure that `accounts.google.com` is fully allowed with access to cookies. (Your users may block `google.com` domains with other tools. Perhaps blocking third-party cookies also causes authentication to fail.)

**Comment by tconfrey** [comment] 2021-01-07 19:44
Thanks @ghostwords for the quick reply. I agree the root cause here is #137 and confirm that greening google.com solves my problem. l **do** detect when authentication fails in other ways, and handle the third-party cookies case by catching an exception thrown by the gapi.js library. However when Privacy Badger is present my experience is that the failure is silent and auth calls just never return (ie don't call a success/error callback or throw an exception). I have not been able to find a way to detect the error (and would appreciate any insights).

My suggestion of exposing some resource as a web_accessible_resource in your manifest file was an attempt to allow myself and other developers to work around the long-pending #137. It should be trivially easy to implement and totally safe and secure.

I appreciate your further consideration here.

**Comment by ghostwords** [comment] 2021-01-07 19:50
> I have not been able to find a way to detect the error (and would appreciate any insights).

You could add a timer and then error out generically if the timer expires (success/detected failures remove the timer). Could be a network issue, could be something (cookie)blocking `accounts.google.com`.

**Comment by tconfrey** [comment] 2021-01-07 20:23
I can, and do, timeout and issue a generic error. But it's not very user friendly or helpful to say 'Google Auth failed' after the fact rather than something like 'Looks like you are using Privacy Badger, please whitelist accounts.google.com' on first execution.

Is there a reason to avoid the web_accessible_resource route? For an invasive (but useful) and widely deployed tool like Badger it seems like a good practice to make your presence known to other extensions the user has chosen to install.

**Comment by ghostwords** [comment] 2021-01-07 20:42
>Is there a reason to avoid the web_accessible_resource route?

You don't want to encourage detection of your extension, as this information can be used by websites to fingerprint your users.

Regardless, I don't think hardcoding for Privacy Badger is the right approach. Like I wrote earlier, your users might be (cookie)blocking `google.com` domains using other extensions, desktop apps, or DNS blockers on the router.

We plan on fixing #137, but until we do, I once again suggest to remind users that `accounts.google.com` needs to be allowed with access to cookies in the generic error message.

**Closed** 2021-04-08 22:18 UTC
Labels: broken extension, duplicate
