### ISSUE TITLE
Blocking cookies from youtube.com prevents embedded videos from playing

### ISSUE THREAD

**Issue by Gallion** [EFForg/privacybadger#2340] opened 2019-04-01 14:05 UTC
I started having this issue today. None of the embedded youtube videos I came across today was working. I figured out that it's caused by privacy badger blocking everything from youtube.com, which is the default. The slider has to be moved to allow the domain for embedded videos to work. I don't know if this is by design. I'm reporting it in case it's not.

**Comment by bcyphers** [comment] 2019-04-01 16:04
Thanks for reporting. I think this is a duplicate of https://github.com/EFForg/privacybadger/issues/2305, which unfortunately has become more common recently. We're working on a fix in #2280.

**Closed** 2019-04-01 16:04 UTC
