### ISSUE TITLE
page becomes unresponsive with privacy badger

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadger#1001] opened 2016-11-28 18:16 UTC
@cooperq 
http://www.ibtimes.co.in/7th-pay-commission-salary-hike-central-government-employees-not-reflecting-gdp-data-706000
this page becomes unresponsive with privacy badger....video at this site plays for 2 seconds only then pauses...
chrome advice me to kill or wait prompt........
![screenshot 57](https://cloud.githubusercontent.com/assets/20338483/20680491/512d13d8-b5c5-11e6-80db-d100bc7497db.png)
![screenshot 58](https://cloud.githubusercontent.com/assets/20338483/20680489/512a9108-b5c5-11e6-806b-ebb9979cb97f.png)
![screenshot 59](https://cloud.githubusercontent.com/assets/20338483/20680490/512b0912-b5c5-11e6-819f-b598278cc48c.png)
![screenshot 60](https://cloud.githubusercontent.com/assets/20338483/20680492/51307dde-b5c5-11e6-8879-8ad9d236f8f4.png)
![screenshot 61](https://cloud.githubusercontent.com/assets/20338483/20680493/51315ac4-b5c5-11e6-8024-ea87a73d68fa.png)
![screenshot 62](https://cloud.githubusercontent.com/assets/20338483/20680494/5147f3c4-b5c5-11e6-944d-72c3f5220aeb.png)
![screenshot 63](https://cloud.githubusercontent.com/assets/20338483/20680495/51547360-b5c5-11e6-9e0c-9a0a3ed486e6.png)

**Comment by ghajini** [comment] 2016-12-01 02:56
@cooperq sort out this issue

**Comment by alexristich** [comment] 2016-12-01 03:09
@ghajini I gave this page a try and it seems to be working properly for me, though it's entirely possible it's due to the difference in our sets of trackers. Would you try clicking the "Disable Privacy Badger for This Site" button and seeing if you get the same issue? Then re-enable Privacy Badger and compare the results. This should hopefully make it clearer whether it's caused by a site Privacy Badger is blocking.

**Comment by alexristich** [comment] 2016-12-06 22:34
@ghajini Just following up on this one - would you be able to try the suggestion I noted above? This should be helpful in better understanding what's going on.

**Comment by ghajini** [comment] 2016-12-09 17:26
Followed your instructions, still the same

**Comment by cooperq** [comment] 2016-12-09 20:22
@ghajini did the page still freeze when privacy badger was disabled?

**Comment by ghajini** [comment] 2016-12-10 02:45
Nope

**Comment by alexristich** [comment] 2016-12-10 08:38
Thanks for the update. 

I went ahead and took another look into this and this time experienced the issue you referred to in the original report. I then disabled Privacy Badger for that site, but still experienced it. I then disabled Privacy Badger altogether, but still experienced the issue. I also opened it in an incognito window with all extensions and plugins disabled, and still experienced the issue. After these tests, I can confirm that there is an issue with this site, but it is not related to Privacy Badger. I'll go ahead then and close this issue.

**Closed by alexristich** 2016-12-10 08:38 UTC

**Comment by ghajini** [comment] 2016-12-10 09:58
screen recorded with privacy badger disabled...site works...don't lie
you can close thread...
https://www.dropbox.com/s/qggg20i2igqbjmj/9b9047f5-32df-4757-yb6a-e342c3443715.webm?dl=0

**Comment by alexristich** [comment] 2016-12-10 21:15
Checked again just to be sure, and it's back to the original state for me, where the site doesn't lock up in either case. I still can't detect any difference in terms of CPU usage or page slowness when Privacy Badger is enabled or disabled, so I'm adding the label `Can not reproduce` to this issue. If you find this same issue on another site or another page I'd be happy to give another look into this one.
