### ISSUE TITLE
Strip destination tracking parameters?

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadger#2197] opened 2018-10-17 23:15 UTC
In addition to wrapping links, a number of large first party platforms add tracking parameters to URLs, where they can be detected by analytics at the destination page. For instance I just saw facebook ad this tracking parameter to a link:

http://www.oracleopenworld.org/?fbclid=IwAR3waKwwsd--w_IkaPwl4hBbvD-R3bww9pi-53A5Np5eRvJG75E

This I think is new from Facebook, but Google Analytics has long added various <b>utm_*</b> parameters that are similar:

https://www.washingtonpost.com/world/national-security/manafort-jury-suggests-it-cannot-come-to-a-consensus-on-a-single-count/2018/08/21/a2478ac0-a559-11e8-a656-943eefab5daf_story.html?noredirect=on&utm_term=.f06ba6ed2f25

**Comment by ghostwords** [comment] 2018-10-17 23:20
Duplicate of #681, I think.

**Closed by ghostwords** 2018-10-17 23:20 UTC
Labels: enhancement, first-party

**Comment by ghostwords** [comment] 2018-10-29 14:59
We have a PR specifically to remove "fbclid" from outgoing Facebook links: #2207.

**Comment by iVoka** [comment] 2019-12-22 09:50
> We have a PR specifically to remove "fbclid" from outgoing Facebook links: #2207.

@ghostwords - I've been using the extension for about a week on Opera and it does not remove Facebook's url parameter "fbclid".

**Comment by ghostwords** [comment] 2019-12-29 18:18
@iVoka Could you open a new issue including steps for how to reproduce the problem please?
