### ISSUE TITLE
Changing tracking domain behavior for one site changes it for all sites

### ISSUE THREAD

**Issue by sylerner** [EFForg/privacybadger#1792] opened 2017-11-27 20:21 UTC
Often, a tracking domain will break only a few - often just one - website.

When viewing a broken web page, clicking on the PrivacyBadger toolbar icon and changing a problematic domain's behavior (e.g., from red to yellow or green) may fix this one web page, but it then globally allows the tracking domain to track activity for all websites that use it, even though the vast majority of them were not broken when the tracking domain was blocked.

Either the default behavior of changing a tracking domain's behavior needs to be limited to the website being viewed, or there needs to be an option whether the change is local the the current website or global to all websites.

Not realizing the current behavior of editing a web pages tracking domain list, I accidentally enabled several heavily used tracking domains to be globally active for my browser until I recently discovered this.

**Comment by ghostwords** [comment] 2017-11-27 20:29
Duplicate of #622.

**Closed by ghostwords** 2017-11-27 20:29 UTC
