### ISSUE TITLE
Can't Export Data

### ISSUE THREAD

**Issue by BlackRabbit22** [EFForg/privacybadger#1561] opened 2017-08-05 20:41 UTC
I can't export my data due to it being too large. Is there a workaround for this?

**Comment by ghostwords** [comment] 2017-08-05 22:19
This bug will be fixed in the next Privacy Badger release.

Duplicate of #1318.

**Comment by ghostwords** [comment] 2017-08-05 22:20
Let me know if you're OK waiting for it to be fixed, or if you'd like to try an experimental workaround now.

**Closed by ghostwords** 2017-08-05 22:19 UTC
Labels: bug, duplicate

**Comment by BlackRabbit22** [comment] 2017-08-06 06:43
@ghostwords I'll wait. thank you for your answer.

**Comment by shapiro125** [comment] 2017-09-27 13:40
I'm getting this issue as well using PB 2017.9.12.1 on Firefox 57.0b3. If i click the "download" button, nothing happens.

**Comment by ghostwords** [comment] 2017-09-27 14:02
@shapiro125 Could you open a new issue please?
