### ISSUE TITLE
Is privacy-badger blocking Discourse from loading correctly?

### ISSUE THREAD

**Issue by aschrijver** [EFForg/privacybadger#1953] opened 2018-04-09 09:44 UTC
There was a [_"Cannot load App" for meta-topic"_](https://meta.discourse.org/t/cannot-load-app-for-a-meta-topic/78008) on Discourse Meta a while ago

![Discourse Error After Revisiting Firefox Tab](https://meta-s3-cdn.freetls.fastly.net/original/3X/9/7/976407d89eb97a74df92bae8a33e13ddbb1a6078.png)

In that case it was uBlock that was the cause, but I now have this issue with Firefox 58, both on Ubuntu and Android, and it seems related to Privacy Badger (see also [my original post](https://meta.discourse.org/t/cannot-load-app-for-a-meta-topic/78008/9) on meta.discourse.org).

The issue occurs when resuming Ubuntu session, or reopening Samsung phone browser, after period of inactivity. Sometimes the privacy-badger menu shows an empty dialog (no chrome to disable PB), sometimes it shows '0 trackers' (just pertains to the error page). Disabling PB and then the page displays again. I use PB `2018.3.21` and have the issue on multiple forums (e.g. [Humane Technology](https://community.humanetech.com) and Meta)

When not disabling, on Android a refresh page is sufficient to get the correct view back, but on Ubuntu opening an entirely fresh tab is required.

Edit: I just noticed that in my Ubuntu FF browser when opening meta.discourse.org PB is showing the empty menu screen, and is not getting triggered at all, unless restarting the browser (with saved tabs).

**Comment by ghostwords** [comment] 2018-04-09 20:06
At least some of this appears to be a Discourse/Firefox bug unrelated to Privacy Badger. If I open Firefox in a fresh profile, visit a Discourse Meta page and restart Firefox, I get the same error screen (see below). No extensions loaded.

![screenshot from 2018-04-09 16 05 00](https://user-images.githubusercontent.com/794578/38520164-fb32b4e2-3c0f-11e8-95db-9d1ffc35a974.png)

**Comment by ghostwords** [comment] 2018-04-09 20:14
Privacy Badger-wise, why do I see the "not-a-valid-HTTP-page" screen on Discourse pages sometimes? It seems to happen to the second page when I have two pages opened, but I am not sure yet. Only seems to happen in Firefox.

![screenshot from 2018-04-09 16 13 30](https://user-images.githubusercontent.com/794578/38520504-03d57c82-3c11-11e8-871d-bcefcec9720f.png)

**Comment by ghostwords** [comment] 2018-04-09 20:15
So I am not sure Privacy Badger is responsible for your problem (since I can reproduce without Privacy Badger) but something weird is going on here (Privacy Badger's popup is in the wrong state sometimes).

**Comment by aschrijver** [comment] 2018-04-09 20:38
Thanks a lot for your time and effort @ghostwords !! I am not familiar in both codebases.. will report back to the Discourse thread!

**Comment by xfalcox** [comment] 2018-04-09 22:12
Discourse implements the minimum necessary service worker to show the "Add to Homescreen"/PWA banner.

It was extracted from https://googlechrome.github.io/samples/service-worker/custom-offline-page/ so I believe many sites will have a similar implementation.


> @ghostwords: At least some of this appears to be a Discourse/Firefox bug unrelated to Privacy Badger. If I open Firefox in a fresh profile, visit a Discourse Meta page and restart Firefox, I get the same error screen (see below). No extensions loaded.

Yes, this is a bug in Firefox "Session Restore". It doesn't restart the service workers or something like that.

**Comment by ghostwords** [comment] 2018-05-13 18:10
This is related to (or is the same issue as) #1144.

We should figure out what the Firefox bug is exactly, and then see if this is an existing [Mozilla Bugzilla](https://bugzilla.mozilla.org) issue and report it if it's not.

There seem to be reports of similar situations in our error reports database. What stands out is that the one reported blocked domain is also the site domain.

**Comment by aschrijver** [comment] 2018-05-17 18:13
I think this might be solved in FF 60.0. I am not entirely sure, but don't remember having seen the issue since I upgraded. Not on Android mobile nor on my Ubuntu laptop.

**Comment by ghostwords** [comment] 2018-11-07 20:48
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1499523#c4, this should be fixed in Firefox when ["Service worker e10s redesign"](https://bugzilla.mozilla.org/show_bug.cgi?id=1231208) is complete. We may release workarounds in Privacy Badger before then, however.

Closing as a duplicate of #1144.

**Closed by ghostwords** 2018-11-07 20:48 UTC
Labels: Firefox, bug, duplicate
