### ISSUE TITLE
CSP failures with script injection

### ISSUE THREAD

**Issue by kesara** [EFForg/privacybadger#3037] opened 2024-12-11 02:11 UTC
Browser: Firefox 133.0.3 (aarch64)
OS: macOS 15.1.1 (24B91)
Privacy Badger version: 2024.7.17

When `unsafe-inline` CSP rule is not set or ignored by Firefox, Firefox console shows an error:
```
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “...”
```

Error points to https://github.com/EFForg/privacybadger/blob/master/src/js/contentscripts/utils.js#L42

Example: https://www.google.com (Firefox ignores `'unsafe-inline'` rule)

**Comment by ghostwords** [comment] 2024-12-11 13:54
Thanks for opening an issue!

This is a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) where the browser fails to override site CSPs for page context ("main world") scripts injected by extension content scripts.

This will be fixed when Firefox fixes their bug, or when we change how we inject into page contexts.

Privacy Badger injects page context scripts for things like [click-to-activate widget placeholders](https://www.eff.org/deeplinks/2024/01/privacy-badger-puts-you-control-widgets), DNT/[GPC](https://globalprivacycontrol.org/) signals in JavaScript, and denying JavaScript cookie access to "cookie-blocked" ("yellowlisted") domains. Core tracker blocking functionality is not affected.

Closing as a duplicate of #1793.

**Closed by ghostwords** 2024-12-11 13:54 UTC
Labels: bug, duplicate, Firefox, MV2
