### ISSUE TITLE
Prevent keystroke and mouse movement tracking

### ISSUE THREAD

**Issue by jurekb** [EFForg/privacybadger#1785] opened 2017-11-21 09:37 UTC
Sites log your keystrokes and mouse movements in real time, before you click submit.
https://arstechnica.com/tech-policy/2017/11/an-alarming-number-of-sites-employ-privacy-invading-session-replay-scripts/

**Comment by ghostwords** [comment] 2017-11-21 13:38
Thank you! Duplicate of #715.

**Closed by ghostwords** 2017-11-21 13:38 UTC
Labels: duplicate, enhancement, heuristic, privacy
