### ISSUE TITLE
future enhancements: redirect and referrer cleaning

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1080] opened 2016-12-15 17:07 UTC
I was just thinking about some of the other tracking and logging mechanisms out there.  Maybe it's out of the scope of this add-on but I wondered if things such as Google image search hover/click referrer stuff can be cleaned from links as well as sites which contain links to with long referrer strings in them.

Seems like links could be stripped of all of that junk and still work.  I have trouble remembering all of the buzzwords for these techniques to even know what add-ons or settings are needed to do these things.

**Comment by cooperq** [comment] 2016-12-16 22:09
duplicate of #85

**Closed by cooperq** 2016-12-16 22:09 UTC
