### ISSUE TITLE
googletagservices.com script surrogate breaks doodle.com

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1151] opened 2017-01-23 23:29 UTC
The script surrogate for googletagservices.com seems to break on doodle.com. It can be fixed by moving googletagservices.com to yellow but we should fix the surrogate instead. 

cc @ghostwords

**Comment by ghostwords** [comment] 2017-01-24 19:07
Filed https://github.com/uBlockOrigin/uAssets/issues/277.

**Comment by cooperq** [comment] 2017-01-24 22:08
Workaround in dc9013e7dcefabed9856860185edd1131b7fb20a
Should be reverted once this is properly fixed.

**Comment by ghostwords** [comment] 2017-01-24 22:10
I'm not sure Google Tag Services is worth yellowlisting because of a single domain ...

**Comment by cooperq** [comment] 2017-01-25 00:11
Looking through the broken sites list I actually expect that it breaks a
couple of other things as well.

**Comment by cowlicks** [comment] 2017-07-24 06:43
I can no longer reproduce this on doodle.com. Closing.

**Closed by cowlicks** 2017-07-24 06:43 UTC
Labels: broken site

**Comment by ghostwords** [comment] 2017-11-14 14:48
This is a good candidate for removal from the yellowlist in #1593.
