### ISSUE TITLE
snapfish family of sites broken

### ISSUE THREAD

**Issue by markbarnes** [EFForg/privacybadger#2530] opened 2019-12-23 12:45 UTC
The Snapfish family of sites is broken because it uses a CDN that Privacy Badger blocks. The CDN is *.sf-cdn.com.

A number of other sites are powered by Snapfish and therefore use the same CDN. I am aware of the following domains which use *.sf-cdn.com:
snapfish.co.uk
truprint.co.uk
bootsphoto.com

**Comment by ablanathtanalba** [comment] 2020-01-04 02:29
Thanks for the report, and apologies for the delayed response. Could you describe the environment you're seeing this particular bug? I'm currently unable to reproduce this issue on a fresh instance of Privacy Badger in Chrome (v79) and Firefox (v71). In both those attempts, the badger doesn't learn to block the various `sf-cdn.com` domains that are detected.

If I'm able to reproduce this issue, I can verify that (https://github.com/EFForg/privacybadger/tree/add-snapfishcdn-mdfp)[this branch] would fix the error. If so, I'll open a PR for that branch.

**Comment by markbarnes** [comment] 2020-01-04 13:01
I am using Chrome 79 on Windows.

To test, I just deleted all the *.sf-cdn.com domains from the "Tracking Domains" section of Privacy Badger. I then clicked around on snapfish.co.uk for a few minutes. I then visited bootsphoto.com, and immediately those domains were blocked. They remained blocked when I then returned to snapfish.co.uk
![snapfish](https://user-images.githubusercontent.com/128895/71765947-4d2d5000-2ef2-11ea-91d9-d069db268f7b.png)

**Comment by markbarnes** [comment] 2020-01-04 13:04
I just checked the pull request, and it doesn't seem to address the issue with the three specific domains I mentioned:
snapfish.co.uk
truprint.co.uk
bootsphoto.com

**Comment by ablanathtanalba** [comment] 2020-01-04 18:18
Thanks for pointing that out! Thought I included them in the first hit. The PR has been updated.

**Comment by ghostwords** [comment] 2020-01-06 22:52
Looks like this is another case of Cloudflare cookies no longer being ignored because of the new `SameSite` attribute. This bug is fixed on master (775ff3e69eb952e83b3da54cdfa2a851ed4cc7cf), which is why we had trouble reproducing.

**Comment by ablanathtanalba** [comment] 2020-01-07 05:49
Thanks @ghostwords ! I'll close the related PR.

**Closed** 2020-01-07 20:01 UTC
Labels: MDFP, broken site
