### ISSUE TITLE
*.ib.metapix.net blocks inkbunny.net private CDN

### ISSUE THREAD

**Issue by GreenReaper** [EFForg/privacybadger#1338] opened 2017-04-22 08:00 UTC
[Privacy Badger has been reported to block _nl.ib.metapix.net_](https://twitter.com/WikiNorn/status/855678836897460224). It would be nice if it didn't do that, as it breaks the site (most images/content), which is using it for every European visitor by default.

The _ib.metapix.net_ subdomains are [used on both dedicated servers and VPS to distribute access to content](https://en.wikifur.com/wiki/Inkbunny#Hardware) for [furry art site _inkbunny.net_](https://inkbunny.net). The purpose of having a separate domain is to _avoid_ the transfer of cookies with such requests, in part because the host may be a VPS in a country outside of Inkbunny's jurisdiction. Such caches are managed by Inkbunny staff and do not serve content for other websites.

[Inkbunny does not log successful accesses to these caches](https://wiki.inkbunny.net/wiki/Security#The_Inkbunny_SSL_Certificate); in fact it blocks accesses from sites which are not _inkbunny,net_ or _metapix.net_ domains via referer, to prevent bandwidth theft.

It's possible that visitors have tried to embed links on other websites, perhaps triggering Privacy Badger to think these subdomains are part of a public CDN, but such accesses should be refused.

**Comment by ghostwords** [comment] 2017-04-22 21:23
I see what you mean about `metapix.net` being a non-tracking, single-site CDN. I can't figure out how to reproduce though ... It would help if we could ask whoever ran into this problem to run some debugging code in their Privacy Badger to help us figure out how this happened. Here are the instructions:

Could you run the following JavaScript code in your Privacy Badger's background page console, and send me what it prints out?

```javascript

(function () {
  const STR = "metapix";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

This should print the decisions your Badger reached for all "metapix" domains, and also the site domains Badger saw "metapix" domains perform tracking on.

To open Badger's background page console in your Chrome browser, visit "chrome://extensions", make sure "Developer mode" is checked (in the upper right), find the row for Privacy Badger, and click on the "background page" link on that row. Then, in the newly appeared window, make sure the "Console" tab is selected, click somewhere within the ">" prompt, paste the code from link above, and press the Enter key.

**Comment by GreenReaper** [comment] 2017-04-23 07:12
Furries use Firefox, because it has a fox. Is there an equivalent or similar method of determining the reason for the decision in this browser?

I cannot immediately reproduce the issue myself on Chrome or Firefox, so maybe it's to do with other sites the end-user accessed?

**Comment by GreenReaper** [comment] 2017-04-23 07:26
OK, I figured out the method. For the benefit of that end-user:
* Open the URL `about:debugging`
* Enable add-on debugging and click Debug next to Privacy Badger
* Click the OK button on the popup warning about remote debugging.
* Enter the above script into the console after the >>

Personally I get:
```
**** ACTION_MAP for metapix 
nl.ib.metapix.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1493361237208
} 
**** SNITCH_MAP for metapix
```

**Comment by GreenReaper** [comment] 2017-04-23 07:30
The end-user's result:
```
**** ACTION_MAP for metapix 
nl.ib.metapix.net {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1493104222984
} 
metapix.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492879096021
} 
**** SNITCH_MAP for metapix 
metapix.net [
  "zafur.co.za",
  "businessinsider.de",
  "inkbunny.net"
]
```

**Comment by ghostwords** [comment] 2017-04-23 14:17
Cool, thank you for tracking this down!

**Comment by ghostwords** [comment] 2017-06-15 14:11
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Closed by ghostwords** 2017-06-15 14:11 UTC
Labels: broken site, mystery

**Comment by ghostwords** [comment] 2018-01-29 15:43
This might have instead been caused by a different mis-attribution bug, what I describe in https://github.com/EFForg/privacybadger/pull/1642#issuecomment-328681731

**Comment by nicheAsQuiche** [comment] 2024-02-21 15:59
Hello 👋 I own/ run MetaPix.art & metapix.io - I've recently had what looks like a bot drive some fake traffick - obviously to mess up analytics etc. this isn't related at all is it? I checked your site out @inkbunny but didn't see no issues so had a look then left aha!

**Comment by GreenReaper** [comment] 2024-02-21 17:04
> Hello 👋 I own/ run MetaPix.art & metapix.io - I've recently had what looks like a bot drive some fake traffick - obviously to mess up analytics etc. this isn't related at all is it?

I'm afraid not, this issue is about an old bug in some privacy software that misidentified our private CDN as a tracker, identified by one of our users (because this software blocked the site). We don't do any referer stuffing to promote the site.
