### ISSUE TITLE
UI is blank in Firefox when JavaScript is disabled

### ISSUE THREAD

**Issue by Chryssalyn** [EFForg/privacybadger#1058] opened 2016-12-14 01:01 UTC
Since the switch to 2.0 PB seems not to work at all, even if I disable other add-ons. The UI window shows nothing but blank boxes, and even the settings page displays strangely and is non-functional.

I'm on FF 50.1 and have ABP, NoScript, TabMix, Self-Destructing Cookies, and RequestPolicy add-ons.

**Comment by cooperq** [comment] 2016-12-14 01:04
Can you try disabling and re-enabling privacy badger? Also maybe try
restarting firefox.?

**Comment by Chryssalyn** [comment] 2016-12-14 01:11
Yep, I've tried that. Here's some pics:
![ui window](https://cloud.githubusercontent.com/assets/24556907/21165827/d5aa0fac-c16f-11e6-963e-bc0907deff64.jpg)
![setup page](https://cloud.githubusercontent.com/assets/24556907/21165911/454f1f32-c170-11e6-8e97-24f263b95dd2.jpg)

**Comment by groovecoder** [comment] 2016-12-14 04:11
What OS? Also can you try disabling and re-enabling each other add-on individually?

**Comment by Chryssalyn** [comment] 2016-12-14 04:20
Win 7 Pro 64 bit.

I tried disabling each add on individually, including restarting FF - no dice.

**Comment by groovecoder** [comment] 2016-12-14 04:47
Okay, I can't reproduce on my Mac but I'll try on a Windows machine tomorrow.

**Comment by congma** [comment] 2016-12-14 10:06
This happens here too.  Might be related to this?

[Content security policy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_Security_Policy#Default_content_security_policy)

Default content security policy
------------

The default content security policy for WebExtensions is:

    "script-src 'self'; object-src 'self';"

This will be applied to any WebExtension that has not explicitly set its own content security policy using the `content_security_policy` `manifest.json` key. It has the following consequences:

* You may only load `<script>` and `<object>` resources that are local to the add-on.
* The add-on is not allowed to evaluate strings as JavaScript.
* Inline JavaScript is not executed.

**Comment by Chryssalyn** [comment] 2016-12-14 10:17
Maybe? Way out of my ability level to know how to test this, lol.

**Comment by airone506** [comment] 2016-12-18 20:03
I can see similar behaviour of PB on my computer. I use the [QuickJS](https://addons.mozilla.org/en-US/firefox/addon/quickjs/) Add-on for Firefox to quickly enable/disable JavaScript.

If the JavaScript is disabled, the Privacy Badger's UI looks like the screenshot above. If the JavaScript is enabled, the UI looks OK. So the only difference in my settings is the JavaScript enabled/disabled in my case.

This behaviour did not occur on the pre-2.x versions of the PrivacyBadger, the UI was OK no matter if JavaScript was disabled or enabled in the Firefox.

Currently I use  Firefox 50.1.0 on Ubuntu & Privacy Badger version 2016.12.15.1.

**Comment by cooperq** [comment] 2017-01-04 19:33
I notice that your icons are at the bottom of the window. do you have some addon like classic theme restorer or do you have a strange fork of firefox or something like that?

**Comment by ghostwords** [comment] 2017-02-08 15:00
The problem here seems to be that Firefox incorrectly disables background scripts for WebExtensions addons when JavaScript is disabled. Here is the Mozilla Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1329731

**Comment by tl87** [comment] 2017-02-16 12:10
I am also experiencing this issue. I also use QuickJS to disable/enable JS.

**Comment by ghostwords** [comment] 2017-04-21 16:07
According to [Bugzilla@Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1329731#c14), this should be fixed in Firefox 54.

**Comment by ghostwords** [comment] 2017-06-15 22:24
@Chryssalyn @tl87 @airone506 Firefox 54 just got released; could you check if it solved the problem of disabling JavaScript breaking WebExtensions?

**Comment by airone506** [comment] 2017-06-21 09:43
@ghostwords I just tested the Privacy Badger 2017.6.13.1 with Firefox 54.0 and JavaScript disabled. Everything seems to be working fine now. The UI of the Privacy Badger is not broken any more.

**Comment by ghostwords** [comment] 2017-06-21 14:16
Excellent, thanks for checking!

**Closed by ghostwords** 2017-06-21 14:16 UTC
Labels: bug, Firefox
