### ISSUE TITLE
Privacy Badger is breaking hs.fi video

### ISSUE THREAD

**Issue by lamtonylam** [EFForg/privacybadger#2704] opened 2020-10-21 17:25 UTC
#### What is your browser and browser version?
Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)
#### What is broken and where?
https://hs.fi on an article where there is a video, it detects Adblock and doesn't play.

![image](https://user-images.githubusercontent.com/63186670/96754705-56809e00-13da-11eb-9215-021730e80128.png)

#### What is the "culprit" domain?
it is 7caa2.v.fwmrm.net

#### What is your debug output for this domain?
```
**** ACTION_MAP for fwmrm.net
140cc.v.fwmrm.net {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
7caa2.v.fwmrm.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1603675105070,
  "userAction": "user_allow"
}
adm.fwmrm.net {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
fwmrm.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
**** SNITCH_MAP for fwmrm.net
fwmrm.net [
  "geeksforgeeks.org",
  "foodnetwork.com",
  "nbc.com"
]
```

#### Notes
I have "Learn to block new trackers from your browsing" setting in Privacy Badger turned off.

**Comment by ghostwords** [comment] 2020-10-21 17:39
Hello and thanks for the report!

As another problem with videos and FreeWheel, this might be a duplicate of #2346.

Does setting the slider for `7caa2.v.fwmrm.net` to "yellow" work around the issue?

**Comment by lamtonylam** [comment] 2020-10-21 18:54
@ghostwords Hello, thank you for your swift reply.

It does let the video play, but then I get ads.

A quite anti-tracking friendly that news site is.

**Closed** 2020-10-22 20:44 UTC
Labels: broken site, widgets, yellowlist
