### ISSUE TITLE
Buttons on various sites don't work in Firefox

### ISSUE THREAD

**Issue by settonull** [EFForg/privacybadger#1357] opened 2017-04-29 14:04 UTC
I just was having trouble logging into the WSJ customer service site while using PB.  I've noticed this on a number of sites, sometimes I can figure out which site to stop it from blocking, other times I just disable it (my current solution is to leave it disabled, too infuriating to have random things not work).  
I haven't noticed if this is consistent (I swear for instance I was able to log into the WSJ the other day, perhaps because it hasn't started blocking it yet?).  It would be great (though I understand perhaps not reasonable) if there was a way to alert you that a button or other interactive feature isn't working because of PB.

**Comment by TonyK1321** [comment] 2017-05-01 14:59
I too have the problem (sometimes) of clicking on a link on a webpage and nothing happens.  In fact, other working links on that page now no longer work.  I need to reload the webpage to get it working again.  When I do that, the page that I was trying to go to is now there.  But also now other links also work.  I have about 10 add-on loaded in Firefox 53.0 (64-bit) in Win10, so to find the offending add-on, I started with clean FF profile, then started adding add-ons until it stopped working, closing FF then restarting between each test.  BTW, the webpage that is the worst but also the most consistent in failing is Fidelity.com, when I click on the News & Research then CD Rate link.  I hope this helps in getting this great add-on fixed.  Also BTW, since PrivacyBadger is based on AdBlockPlus, do I need both add-ons or will PrivacyBadger do all that ABP does and more?
Thanks,
Tony

**Comment by ghostwords** [comment] 2017-05-04 00:52
Might be a duplicate of #1295.

**Comment by ghostwords** [comment] 2017-05-04 00:53
Does this happen in a fresh profile with only Privacy Badger installed?

**Comment by TonyK1321** [comment] 2017-05-04 05:44
I just created a new profile, installed Privacy Badger, and it seems to work fine.  So is there a known incompatibility with another add-on?

 

Tony

**Comment by TonyK1321** [comment] 2017-05-04 12:24
I just power-cycled my computer and tried it again, and it failed.  This was with no other add-on loaded.  

 

Tony

 

From: Tony Kozlowski [mailto:tonyk1321@gmail.com] 
Sent: Wednesday, May 3, 2017 11:44 PM
To: EFForg/privacybadger
Subject: RE: [EFForg/privacybadger] Buttons on various sites don't work in Firefox (#1357)

 

I just created a new profile, installed Privacy Badger, and it seems to work fine.  So is there a known incompatibility with another add-on?

 

Tony

**Comment by 77Mugen** [comment] 2017-05-06 10:58
Hi there,
I have an similare problem with firefox. After I installed my comp new Win10 64 and put PB to firefox it is just not the same PB like befor. It actually does not show all the pages which were blocked before. I normally make a learn tour for PB. On Pages where it showed me 50 pages to block. Now I ve got only 3 or 4.
So I went to the options and on the filter settings its getting weird. Just to be save I setted all buttons on red (if I need something I can switch it to yellow and back). Some stay red, some are green when I open options again (example: instagram.com), others jump to the green position while I am blocking others (openx.net) and parts of google stay yellow and aren't to move at all (khms2.google.com, labs.google.com, mt0.google.com, picasaweb.google.com, gstatic.com).
Has something changed within the app?
Does browsers give PB more pressure?
What can I do to to protect my privacy from those Datafascist?
Thanks

**Comment by ghostwords** [comment] 2017-06-15 21:57
@TonyK1321 Do you run into the same issues if you load only the following test extension I made (disabling all other add-ons for now) https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip

**Comment by ghostwords** [comment] 2017-06-15 22:00
To load the above add-on in Firefox, unzip the archive somewhere, visit `about:debugging`, click on Load Temporary Add-on, and pick the `manifest.json` file inside the unzipped folder.

**Comment by TonyK1321** [comment] 2017-06-16 17:13
Hi Alexi – I d/l’ed that zip, unzipped it, and tried to install the Manifest file from the add-in page (install from a file option), but got a message in FF that it was corrupt.  Is there a different way to install those 2 files?

 

Tony

**Comment by ghostwords** [comment] 2017-06-16 17:25
@TonyK1321 I'm attaching a couple of screenshots showing me about to select `manifest.json` and what you should see if it worked. Hope they help. I re-downloaded and unzipped the archive myself to confirm it works.

![screenshot from 2017-06-16 13 22 05](https://user-images.githubusercontent.com/794578/27237432-11a4aff4-5297-11e7-9327-2285131e49ac.png)

![screenshot from 2017-06-16 13 22 22](https://user-images.githubusercontent.com/794578/27237435-14b4643c-5297-11e7-86ee-41218dd09530.png)

**Comment by TonyK1321** [comment] 2017-06-19 13:46
Hi Alexei – I just tried the temp add-on, and no joy.  It still fails as before.  To test it, I used a profile with no other add-ons enabled, and when I did anything in Fidelity, then went to the News & Research tab, it did not load.  When I disabled your temp add-on, then navigation worked as expected.  Sorry for the bad news.

 

Tony

**Comment by ghostwords** [comment] 2017-06-19 14:08
Ah, but this is good news. The add-on here doesn't do much but also causes the bug to happen; it's a minimal test add-on for getting the bug to show itself. Now when Firefox fixes the WebExtensions bug we reported, your problems should get resolved. Thanks for confirming!

**Comment by ghostwords** [comment] 2017-08-05 23:07
According to https://github.com/EFForg/privacybadger/issues/1295#issuecomment-315998618, you should be able to get rid of this issue in your Firefox profile without having to start over from scratch by [refreshing your Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and then reinstalling all your add-ons.

**Comment by ghostwords** [comment] 2017-08-17 14:48
This might be fixed now that Firefox 55 reached stable.

**Closed** 2017-08-18 17:46 UTC
Labels: broken site, bug, Firefox
