### ISSUE TITLE
unexpected error - firefox 71

### ISSUE THREAD

**Issue by edouardduliege** [EFForg/privacybadger#2515] opened 2019-12-04 18:10 UTC
Firefox 71 64b on Fedora 31 Wayland
I have an unexpected error, no other details.

Please let me know if I can provide any more details.

**Comment by ghostwords** [comment] 2019-12-04 18:27
Hello, and thanks for getting in touch! This is a duplicate of #2474.

**Closed by ghostwords** 2019-12-04 18:27 UTC
