### ISSUE TITLE
Safari extension NOT in the Apple App store

### ISSUE THREAD

**Issue by 10Meisterbaelle** [EFForg/privacybadger#2727] opened 2021-01-02 15:29 UTC
You should make a Safari extension and publish it outside of the Apple App store

**Comment by ghostwords** [comment] 2021-01-02 18:25
Hi, thanks for the suggestion. Please see https://github.com/EFForg/privacybadger/issues/549#issuecomment-744583479 for the latest regarding Safari support.

**Comment by ghostwords** [comment] 2021-01-02 18:26
Closing as a duplicate of #549.

**Closed by ghostwords** 2021-01-02 18:26 UTC
