### ISSUE TITLE
Badger Error: QUOTA_BYTES quota exceeded

### ISSUE THREAD

**Issue by grahamwhiteuk** [EFForg/privacybadger#2676] opened 2020-09-07 13:55 UTC
#### What is your browser and browser version?
Google Chrome, Version 84.0.4147.135 (Official Build) (64-bit)
Privacy Badger from Chrome Store, version 2020.8.25
Running on Fedora 31

#### What is broken and where?
My badger is saying:
> Please tell us about the following error:
> QUOTA_BYTES quota exceeded

#### What is the problem?
I think this is a sub-domain issue as I think I may be a victim of #1864 due to the domain: `ustream.tv`

#### Debug steps taken (so far)
I ran the code snippet from the #1864 bug report:
```javascript
(function () {
  const actionMap = badger.storage.getBadgerStorageObject("action_map"),
    actions = actionMap.getItemClones();

  for (const domain in actions) {
    const map = actions[domain];
      if (map.userAction == "" && map.heuristicAction == "") {
        console.log(domain);
      }
    }
}());
```

The output showed a few different domains but then **LOADS** of entries from `ustream.tv` or more specifically `ums.ustream.tv`

I have removed the ustream entries with the code snippet by following the example from #1717:
```javascript
(function () {
  let am = badger.storage.getBadgerStorageObject('action_map');
  for (let domain in am.getItemClones()) {
    if (window.getBaseDomain(domain) == "ustream.tv") {
      am.deleteItem(domain);
    }
  }
}());
```

Running this code to remove the ustream.tv domain appears to fix my badger (for now) but the bug is still present in the version of the plugin I have.

**Comment by ghostwords** [comment] 2020-09-08 15:10
Hello and thanks for getting in touch!

You may also be interested in the following snippets: https://github.com/EFForg/privacybadger/issues/1902#issuecomment-369797768.

You can also work around this issue by clicking the Reset button under the Manage Data tab on Privacy Badger's options page.

**Comment by ghostwords** [comment] 2020-09-08 15:11
I'm going to close this as a duplicate of #888. Please let us know if this (`QUOTA_BYTES`) keeps coming up.

**Closed by ghostwords** 2020-09-08 15:11 UTC
