### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by albell** [EFForg/privacybadger#1084] opened 2016-12-15 19:08 UTC
Hi guys,

So, I was psyched to get the EFF email about the PB 2.0 release. But, I've got a Android phone. I've visited the PB install page in Firefox, Chrome, and Opera, and PB doesn't seem to be supported in any Android browser. W...... T....... F........ Am I missing something?

I love EFF. I want to see this project to succeed, beyond all of our wildest imaginations. But I have to scratch my head at the allocation of resources here. Mobile usage is approaching double that of desktop. We'll cross that line soon if we haven't already:

http://marketingland.com/digital-growth-now-coming-mobile-usage-comscore-171505

Is developing for desktop just easier? Why was a desktop release developed and released first? Mobile first, please!

I will donate hard cash towards a crowdfunding campaign for an Android release that has defined thresholds and deliverable dates. I'm sure I'm not alone. Tell me where to go.

**Comment by pde** [comment] 2016-12-15 19:49
One way you can try Privacy Badger on Android is via the [WARP browser](https://www.eff.org/deeplinks/2016/11/delivering-privacy-badger-and-https-everywhere-mobile-users-warp-speed) which includes a port of Privacy Badger 1.x (we'll also work with Qualcomm to get that up to 2.x)

**Comment by ccoenen** [comment] 2016-12-15 21:04
related to https://github.com/EFForg/privacybadgerfirefox-legacy/issues/271 which is - sadly - marked "wontfix" :-(

**Comment by jawz101** [comment] 2016-12-16 00:22
https://addons.mozilla.org/en-US/android/addon/privacy-badger17/

It's right there

**Comment by jawz101** [comment] 2016-12-16 00:34
... Note it was only made available on Android just a week ago.  There's no user interface so I can't really tell if it's doing anything.  The only thing I notice is on a rooted phone is this file

file:///data/data/org.mozilla.firefox/files/mozilla/(profile name).default/browser-extension-data/jid1-MnnxcxisBPnSXQ%40jetpack/storage.js


But the file doesn't look like it's logging anything as the desktop version does.  It just has this after a few days of browsing.  On the desktop this would be full of logged sites:

{"snitch_map":{},"action_map":{},"cookieblock_list":{},"supercookie_domains":{},"dnt_hashes":{},"settings_map":{}}

**Comment by albell** [comment] 2016-12-16 00:42
@jawz101 thanks. So it's... totally busted?

When I visit the project home page in Firefox 51 for Android this is what I see:

![privacy-badger-site-12-15-2016-on-firefox51-android](https://cloud.githubusercontent.com/assets/1142025/21247492/a7b8759a-c2e4-11e6-9463-7940df235be2.png)

This just after your big launch announcement. There's.... a lot of opportunity being left on the table here. Negative first impressions can be hard to reverse.  Does this project have full-time maintainers? If not, how can users like myself help fund the hiring of them? Privacy can be a business, too, just like advertising.

**Comment by albell** [comment] 2016-12-16 00:46
P.S. I just downloaded WARP. It's cool niche product for the determined user, but the design/marketing is painfully amateur. It's hard to see this becoming a mainstream product with a global impact. I'd love to see a clearer path towards mass adoption on mobile.

**Comment by jawz101** [comment] 2016-12-16 00:49
Well, I just go straight to the Firefox AMO page.  Also, I don't even know if Firefox for Android is indeed e10s yet.  When I go to about:support it still says multiprocess is disabled by add-ons.  Now I think half of the problem is Mozilla still hasn't rolled e10s out to the mobile Firefox.

**Comment by cooperq** [comment] 2016-12-16 20:41
Hi all, 
Lead developer here. The big blocker with android support is that mobile firefox still doesn't support web extensions. So if you want to see privacy badger on android go let mozilla know!

**Comment by jawz101** [comment] 2016-12-16 21:57
@cooperq check my post above.  I can actually find Privacy Badger on the AMO mobile site while on my Android phone.

https://addons.mozilla.org/en-US/android/addon/privacy-badger17/

**Comment by albell** [comment] 2016-12-20 17:52
@cooperq  Thanks for the response. I'm new to WebExtensions, but I'm looking at:

https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/

which says:

With the release of Firefox 48 we are announcing Android support for WebExtensions. WebExtensions add-ons can now be installed and run on Android, just like any other add-on. However, because Firefox for Android makes use of a native user interface, anything that involves user interface interaction is currently unsupported (similar to existing extensions on Android).

So is the lack of UI support the holdup? Is there a way to end-run around this, so that some version of PB2 can run on Fennec for the year 2017, before full support arrives?

**Comment by mcomella** [comment] 2017-04-08 21:13
I briefly looked into this.

A list of implemented Web Extension features on Android [can be found on MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs). For the back-end, I didn't check which ones are necessary for Privacy Badger to work.

For UI, the only currently implemented user-initiated UI element is [`pageAction`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction). This is intended to be used for interactions on specific pages (e.g. if the page can be opened in an Android app, a button will appear in the toolbar to open that app) and, imo, wouldn't be a good fit for Privacy Badger. I think we'd want something more like the [`NativeWindow.menu`](https://developer.mozilla.org/en-US/Add-ons/Firefox_for_Android/API/NativeWindow/menu) API, which would put a menu item in the 3-dot menu. When this item is clicked, I imagine a new tab would open (or the content is overlaid on the current tab) and the user would see the same content as the Privacy Badger overlay on desktop.

The [`browserAction` API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction) is expected to add a menu item on Firefox for Android, but it's not implemented yet. [Bug 1330159](https://bugzilla.mozilla.org/show_bug.cgi?id=1330159) is tracking this work and there is [a WIP in one of its dependencies](https://bugzilla.mozilla.org/show_bug.cgi?id=1331742) so I'd _guess_ we might be seeing the necessary UI APIs earliest in Firefox 56 (release is 52 right now, Nightly is 55).

**Comment by jawz101** [comment] 2017-05-21 17:14
Ublock has worked on Android for over 2 years.  Has a ui and everything.  I've given up on this add-on because they spin their wheels and develop test environments more than the actual add-on.

**Comment by ghostwords** [comment] 2017-05-21 23:41
Cool, I'll be sure to consult how uBlock did the UI on Android when I get to working on our port.

The reason I haven't jumped on porting Privacy Badger to Firefox on Android because we still have some major bugs and performance issues on the desktop. For example, I'm currently working on fixing a tracking mis-attribution bug (Badger incorrectly attributes tracking to non-tracking domains) that seems responsible for a good chunk of our [broken site backlog](https://github.com/EFForg/privacybadger/issues?q=is%3Aissue+is%3Aopen+label%3A%22broken+site%22).

I hear you are frustrated and I am sorry about that, but try to see things from my perspective. Having working tests is pretty essential to keeping a project like this (tiny team, open source) going effectively in the future. There is much to do besides implementing Badger on Firefox, a platform with a pretty small market share.

If you'd like to see a certain feature get implemented, you could make a case for making that feature higher priority. You could also help by reporting how your experience using Privacy Badger on Firefox for Android went. I know there is no UI, but it sounds like you installed and used it for a while because of a `addons.mozilla.org` bug. Did you notice a difference in your browsing (was it good? bad? etc.)?

**Comment by strugee** [comment] 2017-05-22 06:54
@jawz101 another really great way to contribute would be to write an Android UI yourself. Or find someone who's willing to.

**Comment by jawz101** [comment] 2017-05-22 21:49
@ghostwords @strugee 
I know I was grouchy so I appreciate the feedback.  If I had the skillset I would be all over helping but certain forms of programming are foreign to me.  I do SQL all day but this sort of esoteric programming... well, I respect the work you do.  Especially given Firefox seems to be in a constant state of development and poor documentation.

As for the FFox for Android add-on- right now it looks like it simply doesn't write anything to the storage.js file found in 
/data/data/org.mozilla.firefox/files/mozilla/<profilename>/browser-extension-data\jid1-MnnxcxisBPnSXQ@jetpack.storage.js

The file gets created on app install but nothing is logged as I browse.

**Comment by ShapeShifter499** [comment] 2017-06-02 11:57
I'd love to see this come to Android as I already make use of it on Firefox for Linux.

**Comment by strugee** [comment] 2017-06-06 08:25
Hey @ShapeShifter499! Please don't add +1 comments, as they don't contribute anything to the discussion and just generate more email for the maintainers (and those who are subscribed to this issue) to go through. Instead, you can support issues by using GitHub's reactions feature (smiley icon at the top-right of each comment).

**Comment by ShapeShifter499** [comment] 2017-06-06 11:03
Did something change recently?  Going to the official Privacy Badger site at EFF on Firefox for Android no longer displays that it's not compatible.

**Comment by ghostwords** [comment] 2017-06-06 13:57
Yep, there were some fixes made to the website. Visiting on Android should suggest a couple of existing privacy tools for Android, but that may not yet be working.

**Comment by lemnis** [comment] 2017-07-16 05:08
I was interested in the current state of WebExtensions within Android and checked if it was possible to make this plugin work with reasonable ease. Unfortanelly it still has some "small" issues.

-  `browserAction` is recently added (v55, current beta), but it doesn't have support for all functions yet. 
    - All functions within this API should be checked first before used
    - The pop-up doesn't work yet, so it must be faked
- The options page is not accessible within the add-ons manager, but the add-ons manager can integrate an option UI. My quick fix is to make another options UI that redirects to the real options page.

Unfortanelly if you want to make this extension work within android right now, you will break it for other browsers and the current UI of the plugin doesn't help either.

I did make a fork (with no extra comments 😑  )  for everyone who is interested. https://github.com/lemnis/privacybadger

**Comment by ghostwords** [comment] 2017-07-16 19:10
Very cool, @lemnis, thank you for your work!

Which parts of the your [WIP Android fork](https://github.com/EFForg/privacybadger/compare/master...lemnis:master) are incompatible with existing browsers?

When you say Badger's current UI is problematic for Android, what are the problems?

**Comment by lemnis** [comment] 2017-07-19 03:51
#1516 Added a pull request because we can add Android support without breaking it. As result I had to remove 1 feature.

Full detail:
* The UI that I mentioned was mostly the `overflow: hidden` that was set and prevented scrolling, see full detail on https://github.com/EFForg/privacybadger/pull/1516/commits/bc231ec1d24afbba97d07cf898266e51b406b337
   * Still you can't give back control to privacy badger within the popup, the button isn't visible. I haven't looked into this specific issue
* You can't access the settings through the addon page, this was possible in my previous commit with a detour. While FF android doesn't support `options_ui.open_in_tab`, the extension should switch to `options_ui` ( [optionsv2](https://developer.chrome.com/extensions/optionsV2) ). Because Firefox will never support `options_page` and 

   > Older versions of Chrome will only recognize options_page, and only open in tabs. Chrome 40 and onwards prefer to use the options_ui field if it's specified.

  but a proper transition will involve a new UI for the options page, because all options will be loaded inside the 'extension manage page'
* While [bugzilla 137033](https://bugzilla.mozilla.org/show_bug.cgi?id=1370333) isn't resolved, the popup must be opened with a workaround (https://github.com/EFForg/privacybadger/pull/1516 background.js + popup.js)

Tested in Firefox for Android 56.0a1 (2017-07-18), should work from 55+. Did check chrome and firefox desktop, didn't see anything unexpected.

**Comment by ghostwords** [comment] 2018-01-03 16:44
Status update: Privacy Badger is available for Firefox on Android as Beta software:

![screenshot from 2018-01-03 11 38 42](https://user-images.githubusercontent.com/794578/34529874-582bd9f2-f07b-11e7-845e-a4d5561c36ae.png)

**Comment by ccoenen** [comment] 2018-01-03 21:25
Runs on my phone, I'll report back in case anything is nor working as expected.

**Comment by aschrijver** [comment] 2018-01-12 23:32
I just installed the bèta.. worked perfectly for a little while.

But now there is no longer menu item for Privacy Badger where I can see the trackers and such.
I can still reach the settings via the Add-ons menu, but that's about it.

Android Samsung S7, and Firefox 57.0.4

**Comment by aschrijver** [comment] 2018-01-12 23:37
ok, a full phone restart brings back the menu entry :)

**Comment by ghostwords** [comment] 2019-06-20 20:52
Resolving for now, as there aren't any clear followups at this point.

**Closed by ghostwords** 2019-06-20 20:52 UTC
Labels: Android, Firefox, question
