### ISSUE TITLE
Settings dialog width not sufficient when icon in menu

### ISSUE THREAD

**Issue by finwe** [EFForg/privacybadger#1187] opened 2017-02-06 10:39 UTC
Is is not possible to change settings when I move the Badger icon from main toolbar under the menu button, because the menu width is not sufficient.

![shot_170206_113711](https://cloud.githubusercontent.com/assets/195675/22643924/d15a256a-ec60-11e6-889a-27042db39933.png)

Also there is no scrollbar visible.

Firefox 51.0.1 on Windows 7.

**Comment by cooperq** [comment] 2017-02-27 21:00
duplicate of #1120

**Closed by cooperq** 2017-02-27 21:00 UTC
Labels: firefox, ui
