### ISSUE TITLE
Mobile twitter not registering likes or reshares in Firefox

### ISSUE THREAD

**Issue by sohkamyung** [EFForg/privacybadger#1122] opened 2017-01-05 03:07 UTC
Visit mobile.twitter.com as a twitter user in Firefox. 'Like' a tweet, and refresh the page. The 'like' is gone from the tweet.

I have to disable the Privacy Badger add-on completely to make mobile.twitter.com functional. Disabling Privacy Badger on just that web page is not good enough.

I tested this on a new Firefox Profile with just the Privacy Badger add-on installed to get the bug.

**Comment by cooperq** [comment] 2017-01-06 17:35
can not reproduce this. What version of firefox and what version of privacy badger are you using?

**Comment by sohkamyung** [comment] 2017-01-09 08:11
Firefox version:  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Privacy Badger version: 2016.12.15.1

BTW, I'm not getting consistent behaviour on this. On another of my systems (Windows 10), Firefox is still getting this problem, even with Privacy Badger disabled.

I will try to update this with more information after further debugging.

**Comment by sohkamyung** [comment] 2017-01-09 13:25
Confirm that I can reproduce this bug on a different system:

Firefox version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
Privacy Badger Version: 2016.12.15.1

**Comment by alexristich** [comment] 2017-01-09 19:35
We're still having trouble reproducing this - I tried in FF 50 and 51 but no dice. Would you list the domains on this page that are showing as blocked or cookieblocked as per the Privacy Badger popup? Also, if you open the developer console in Firefox do you notice any errors showing?

**Comment by cooperq** [comment] 2017-01-09 19:45
Actually I am not able to reproduce this. I think that maybe one of our content scripts is loading even when badger is disabled and is breaking a script loaded by api.twitter.com.

@sohkamyung as a workaround for now can you just use non-mobile twitter?

**Comment by ghostwords** [comment] 2017-03-28 17:55
@sohkamyung Is this still an issue with Privacy Badger version 2017.3.22?

**Comment by ghostwords** [comment] 2017-10-06 00:27
Let me know if this is still an issue. Resolving for now.

**Closed by ghostwords** 2017-10-06 00:27 UTC
Labels: broken site, Firefox, good volunteer task
