### ISSUE TITLE
"Hidden" sharing buttons shouldn't show replacement button

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadger#892] opened 2016-08-10 10:19 UTC
See https://dev.twitter.com/web/tweet-button

With PB active, I see the following:
![two icons](https://cloud.githubusercontent.com/assets/11308076/17550090/22c73a06-5ea8-11e6-9784-dffb57d22f9a.png)

There's something weird going on here. There are 3 sharing buttons on this page, but `buttonsToReplace` from `socialwidgets.js` has six items, three being standard `<a>` elements and three others being `<iframe>` elements:
![buttonstoreplace](https://cloud.githubusercontent.com/assets/11308076/17550209/b7c81c10-5ea8-11e6-8023-68330915f645.png)

The `<iframe>` elements have `visibility: hidden` as a property, but as this is not passed through to the replacement button, a new button appears for each iframe.

I don't see any iframes on the page with PB turned off, so I'm wondering whether it's something in how the list of buttons to replace is being generated which is causing duplicates. In any case, something to look into.

**Comment by cooperq** [comment] 2016-08-11 05:55
Interesting, this actually appears to be a race condition. Refreshing the page I sometimes get two buttons and sometimes get only one. Probably relevant thoughts in #404 #227 #553

**Comment by alexristich** [comment] 2016-08-11 09:15
Ah, I see the race condition has been a pesky challenge for quite some time now. Undoubtedly not easy to fix. 

I noticed the same, with some pages loading double more frequently than others. I'm not sure I can help much with this one just yet; not a lot of experience with the DOM. Perhaps something for another brave soul to tackle soon. :)

**Comment by ghostwords** [comment] 2018-02-06 23:35
Closing as a duplicate of #788.

**Closed by ghostwords** 2018-02-06 23:35 UTC
Labels: bug, widgets
