### ISSUE TITLE
Problems when logging in on Solid servers

### ISSUE THREAD

**Issue by kjetilk** [EFForg/privacybadger#2240] opened 2018-12-11 17:20 UTC
#### Introduction

We have a general problem with Privacy Badger over at the [Solid project](https://solid.inrupt.com/), which is an effort to bring personal data control to users based on Web technology. I'm a developer on Solid, but I have also been a Privacy Badger user for some time, and it manifested itself in [several](https://github.com/solid/node-solid-server/issues/883) [problems](https://github.com/solid/node-solid-server/issues/884). Eventually, we found that many users are affected, and we now have [this issue open](https://github.com/solid/solid-auth-client/issues/95) to track it from our side

#### What is your browser and browser version?
The issue has been seen across both Firefox and Chrome. Personally, I run 60.3.0esr (64-bits) and 63.0 (64-bit) on various Debians :-) 

#### What is broken and where?

It is a bit hard to reproduce and explain, but I'll try: Solid uses [WebID-OIDC](https://github.com/solid/webid-oidc-spec) for authentication. A combination of a bearer token and a cookie will be used, depending on whether a user or a WebApp is accessing the data.

It seems like PB might be blocking parts of the protocol when credentials are reused across the Web, but we haven't been to drill into this. I think we can help reproduce the problem though, see below.

#### What is the "culprit" domain?

@JornWildt has been able to reproduce it when interacting between domains on the community-maintained site https://elfisk.solid.community/ and others. This is running an previous version of the server, but I have also reproduced it on the latest beta.

#### What is your debug output for this domain?

```
**** ACTION_MAP for solid.community
elfisk.solid.community {
"dnt": false,
"heuristicAction": "block",
"nextUpdateTime": 1543923490370,
"userAction": "user_allow"
}
solid.community {
"dnt": false,
"heuristicAction": "block",
"nextUpdateTime": 1544823052811,
"userAction": ""
}
**** SNITCH_MAP for solid.community
solid.community [
"localhost",
"elfisk.dk",
"solidrc.azurewebsites.net"
]
```

#### Host to reproduce

We have a test server for the most recent version in https://dev.inrupt.net/ Please feel to poke around it, but note that it is not for things you want to keep, it is purely for testing stuff, so stuff that is put there may be removed for any reason at any time.

I created an identity https://testpb.dev.inrupt.net/profile/card#me  with password `D#hutd4hut`. You should be able to use this identity to log into the server. Then, you can use that identity to log into my personal server too (which is not a test environment, but runs the same version. You will not be authorized to access anything non-public, but it is not necessary to reproduce the problem): https://solid.kjernsmo.net/ 

The problem I found when I did that is that you get a HTTP error `401`, even though you have logged in. The problem may manifest itself in many different ways though, for example, the login popup may become unresponsive.

We don't know if this is actually a Privacy Badger problem or a problem with the authentication code in our end, but I think it is a pretty good overlap of the audience of our two projects, so we'd love to work with you to resolve this.

**Comment by JornWildt** [comment] 2018-12-11 19:50
Let me add that each host, like for instance https://dev.inrupt.net/, keeps a local copy of an HTML page (login.html) that opens in a separate window (try it at https://ragnaros.dev.inrupt.net/ and click "Login"). The login page allows you to select an identity provider, for instance "Solid community", by clicking on the related button.

When the "Solid community" button is clicked, the code reaches out to https://solid.community/.well-known/openid-configuration using a "fetch" browser call to GET a JSON encoded configuration document. It is this call that gets blocked.

The blocking starts after a few different sites has opened their local version of "login.html" which then has reached out to https://solid.community/.well-known/openid-configuration a couple of times from these different sites.

What is https://solid.community/.well-known/openid-configuration doing wrong to get blocked?

**Comment by JornWildt** [comment] 2018-12-11 19:52
Maybe a "Do not track" policy could help? See https://www.eff.org/dnt-policy

**Comment by ghostwords** [comment] 2018-12-11 22:17
Hello and thanks for reaching out!

I can help figure out why Privacy Badger decides to start blocking `solid.community` resources, but I need some help in reproducing this behavior. Could you provide the steps for getting Privacy Badger to record any Solid domains as a tracker starting from a clean browser profile? You can also just make your Badger forget about all Solid (`solid.community`?) domains by Xing them out under the Tracking Domains tab on the options page. I don't need the steps for getting Badger to actually block the domains, just having them show up as trackers is enough.

You might have provided this already in the original report, but I'm confused by how to actually log in, for example. What should my username be?

**Comment by kjetilk** [comment] 2018-12-11 23:55
Thanks a lot, @ghostwords !

I think it might be better to work against https://dev.inrupt.net/ (and subdomains) since that runs the software we will be releasing soon (whereas solid.community runs a legacy version).

Do I start with a clean browser profile if I start a "Private Tab" in FF? Hmmm, apparently not. OK, so I crossed out solid.kjernsmo.net. Now, I'll try to get the host testpb.dev.inrupt.net recorded as a tracker. This is my attempt:

1. Open "Private Tab" (to not pull along other logged in sessions)
2. Go to https://testpb.dev.inrupt.net/
3. This will tell me I'm not logged in, and then I hit the "Log in" button
4. A popup jumps up, I pick `testpb.dev.inrupt.net` as my identity provider.
5. Use `testpb` as username (good question, BTW) and `D#hutd4hut` as password. Hit "Log In".
6. I'm logged in and redirected to a home page. No trackers are found by the Badger.
7. Go to https://solid.kjernsmo.net/ and hit "Log in"
8. I get a popup, where I write https://testpb.dev.inrupt.net/ as my identity provider in a text field. Hit "Go".
9. I see "Logged In" in the popup, but I'm still seeing "Log in to access this resource", which one of the failure modes seen when using the Badger.

Sooooo... The strange thing is that this doesn't seem to have added neither anything on `*.inrupt.net` nor `solid.kjernsmo.net` to the trackers... Could it be something other than blocking cookies that could cause this...?

**Comment by ghostwords** [comment] 2018-12-12 01:39
I run into trouble in step 4 where clicking Go doesn't do anything. Opening the console shows a CORS error. This seems to happen with or without Privacy Badger. Screenshot:

![screenshot from 2018-12-11 20 36 34](https://user-images.githubusercontent.com/794578/49841204-b476e000-fd84-11e8-919d-6f328b2868a8.png)

**Comment by kjetilk** [comment] 2018-12-12 08:55
Hmmm, that's interesting! Certainly something on our side, I'll check it out.

**Comment by JornWildt** [comment] 2018-12-12 09:15
This works for me this morning. I have registered three accounts and once I have tried to log-in to them, solid.community shows up in the list.

Steps:

- Using Chrome

- Remove solid.community from PB by X'ing them out.

- NOT using private browser.

- Open https://uther.dev.inrupt.net/, click "Login", click "Solid community" and then close the login window without actually logging in.

- Open https://ragnaros.dev.inrupt.net/, click "Login", click "Solid community" and then close the login window without actually logging in.

- Open https://aviana.dev.inrupt.net/, click "Login", click "Solid community" and then close the login window without actually logging in.

Now I find solid.community in the PB list again.

I Don't see any CORS warnings showing up in the log.

**Comment by ghostwords** [comment] 2018-12-12 17:38
@JornWildt I am unable to reproduce ... You probably have cookies set for `solid.community` and I do not. Simply visiting https://solid.community/ first doesn't seem to make a difference, so I'm not sure how to get those cookies. Are you able to reproduce in Incognito / a different browser / a new browser profile?

@kjetilk It seems that the SSL and CORS errors I see are specific to Firefox. I am able to reproduce in Chrome, but I get the same result without Privacy Badger as well ... I started from a fresh Chrome profile both times.

With Badger:

![screenshot from 2018-12-12 12 33 19](https://user-images.githubusercontent.com/794578/49887366-23e2e300-fe0a-11e8-92bf-f73673a409df.png)

Without Badger:

![screenshot from 2018-12-12 12 37 18](https://user-images.githubusercontent.com/794578/49887555-acfa1a00-fe0a-11e8-8e78-bb26b35e94ee.png)

**Comment by kjetilk** [comment] 2018-12-12 22:03
@ghostwords Those cookies are set for authenticating a Web App on behalf of the user, so they are probably set when you are logged in differently. I haven't got a good understanding of that part of our code. The whole thing seems rather obscure. Lets see what we can find.

**Comment by ghostwords** [comment] 2019-01-04 19:51
I'm going to close this for now. Let me know if I can help with anything else.

**Closed by ghostwords** 2019-01-04 19:51 UTC
Labels: broken site
