### ISSUE TITLE
Allow an option to show placeholders for blocked elements if feasible

### ISSUE THREAD

**Issue by pvsomebody** [EFForg/privacybadger#1133] opened 2017-01-12 05:03 UTC
It allows the web page to look more visually similar to how it was meant to by its designers before you turned up PrivacyBadger; for example, AdBlock and uBlock have an option do it and it works great.

**Comment by ghostwords** [comment] 2017-03-31 13:40
Is this the opposite of #442?

**Comment by pvsomebody** [comment] 2017-03-31 13:55
I would assume so! :) (Except the other but report is taking about default
behavior.)

31 бер. 2017 р. 3:41 пп "Alexei" <notifications@github.com> пише:

**Comment by cowlicks** [comment] 2017-07-25 04:30
related to #688

**Comment by ghostwords** [comment] 2020-08-05 18:17
Closing as a duplicate of #442.

**Closed by ghostwords** 2020-08-05 18:17 UTC
Labels: enhancement, ux
