### ISSUE TITLE
Fails on website which uses xmlhttprequest instead of main_frame

### ISSUE THREAD

**Issue by quipri** [EFForg/privacybadger#2391] opened 2019-06-16 00:37 UTC
Right now Privacy Badger isn't working on slate.com using Firefox.

The problem seems to be related to the fact that after the website has stored it's cookie and site data, if you access any pages in a new tab the page is loaded using xmlhttprequest and never main_frame. Then recordFrame() is never called with a frame_id of 0, and PB breaks.

**Comment by ghostwords** [comment] 2019-06-16 15:49
Hi quipri, this is a known issue that has to do with Service Workers and browser bugs related to Service Worker requests as processed by extensions. We hope to have a workaround in the next few updates.

**Comment by ghostwords** [comment] 2019-06-16 15:50
Duplicate of #1144 or #2335.

**Closed by ghostwords** 2019-06-16 15:50 UTC
