### ISSUE TITLE
Invalid charset for localized labels/strings in Firefox on Linux

### ISSUE THREAD

**Issue by sergioleo** [EFForg/privacybadger#1412] opened 2017-06-05 16:31 UTC
I have used Privacy Badger may be for two years and from some day may be a half of year ago it starts display strings (probably localized ones? some words in English are displayed properly) as abracadabra. Both in drop-down panel and on settings page. 
Looks like if there is some UTF16/UTF8 problem with localized strings
Screenshot is attached.
I tried to remove and reinstall addon, that did not help. 

![privacy_badger_screenshot](https://cloud.githubusercontent.com/assets/23107451/26792936/c376b950-4a24-11e7-80b7-2178aa878219.png)

My locale:
$ locale
LANG=ru_UA.UTF-8
LANGUAGE=ru_UA:ru
LC_CTYPE="ru_UA.UTF-8"
LC_NUMERIC="ru_UA.UTF-8"
LC_TIME="ru_UA.UTF-8"
LC_COLLATE="ru_UA.UTF-8"
LC_MONETARY="ru_UA.UTF-8"
LC_MESSAGES="ru_UA.UTF-8"
LC_PAPER="ru_UA.UTF-8"
LC_NAME="ru_UA.UTF-8"
LC_ADDRESS="ru_UA.UTF-8"
LC_TELEPHONE="ru_UA.UTF-8"
LC_MEASUREMENT="ru_UA.UTF-8"
LC_IDENTIFICATION="ru_UA.UTF-8"
LC_ALL=

**Comment by ghostwords** [comment] 2017-06-05 18:00
Which version of Firefox do you have? This seems like a duplicate of #1222. If it is, this is a Firefox bug that you can fix by upgrading Firefox. Please see https://github.com/EFForg/privacybadger/issues/1222#issuecomment-285542771 for more information.

**Closed by ghostwords** 2017-06-05 18:00 UTC

**Comment by sergioleo** [comment] 2017-06-06 09:47
FF ESR 45.9.0 (goes with Debian 8.7)
Yes, it seems it is same issue to #1222.
Thank you!

**Comment by sergioleo** [comment] 2017-06-21 14:43
I just write to confirm: Debian stable has updated its FF to FF ESR 52.2.0 and this fixed problem with Privacy Badger. Thanks.

**Comment by ghostwords** [comment] 2017-06-21 15:22
Excellent, thanks for confirming!
