### ISSUE TITLE
Google currency charts currently blocked

### ISSUE THREAD

**Issue by episanty** [EFForg/privacybadger#864] opened 2016-06-10 11:27 UTC
Looking for currency conversions on Google, such as e.g. https://www.google.co.uk/search?q=1usd+to+gbp, in general produces a widget with a currency conversion tool and a chart of the recent history of the exchange rate. Since recently, however, Privacy Badger blocks this chart:

![selection_034](https://cloud.githubusercontent.com/assets/6827034/15962283/30c81f58-2f0a-11e6-9733-7559d3249f74.png)

This impairs the usability of a site that the user is explicitly asking for, and it does not expose the user to additional external tracking - the user is already visiting Google under their T&Cs, and the chart is provided by Google. Thus Privacy Badger should allow the chart through. (Whether this can be done without creating an ugly exception, of course, is another matter.)

**Comment by alexristich** [comment] 2016-07-14 02:33
I started looking into this issue, and it seems there is a higher level problem. The resource that is being blocked comes from `encrypted.google.com`, which is not on the same FQDN as the page you're visiting (i.e. google.com vs. google.co.uk).

I'm working on a tweak right now that will override any heuristic action for subdomains of a page that a user is visiting, but this does not include a solution for sites such as Google that host services across multiple top level domains. Immediately, no good generic solution comes to mind for this problem, but having it work across properties on the same TLD should be an improvement nonetheless. 

I'm thinking that perhaps in the case of popular services like Google, it can just be manually configured (such as having a reference table), as this would cover most cross-TLD services.

**Comment by alexristich** [comment] 2016-07-16 06:45
Ah, just realized that the extension already gracefully handles blocked resources from the same base domain :)

So, the issue is just with sites like Google that have regional TLDs but call resources from properties with other TLDs. Continuing to poke around the code and see how everything is arranged. I've got a couple ideas on how to handle this neatly; will see if I can get something put together this weekend.

**Comment by ghostwords** [comment] 2017-05-04 01:12
Same as #1253?

**Comment by ghostwords** [comment] 2017-05-04 01:14
Should be fixed by #910.

**Closed by ghostwords** 2017-05-04 01:14 UTC
Labels: broken site, good volunteer task, heuristic
