### ISSUE TITLE
Add "white list" entry by GPO (when using Privacy badger in a Windows Domain)

### ISSUE THREAD

**Issue by jeanbruder** [EFForg/privacybadger#2466] opened 2019-09-24 15:23 UTC
#### What is your browser and browser version?
Google Chrome - Latest version

#### What is broken and where?
Feature request - Add "white list" entry using GPO

#### What is the "culprit" domain?
"Vimeo" video are brocken (cookies not allowed on "player.vimeo.com")

#### What is your debug output for this domain?
N/A

**Comment by ghostwords** [comment] 2019-09-24 16:11
Hello!

This sounds like a duplicate of #1887 

Regarding configuring Privacy Badger using GPO: Please see https://github.com/EFForg/privacybadger/blob/master/doc/admin-deployment.md. Disabling Privacy Badger on certain sites (don't do anything on the Coursera website) is already supported, but changing slider settings (set `vimeo.com` to "green") is not at this time.

Let me know if you have any questions.

**Closed by ghostwords** 2019-09-24 16:11 UTC
