### ISSUE TITLE
Shop search gets blocked by Privacy Badger

### ISSUE THREAD

**Issue by clem3ns** [EFForg/privacybadger#2109] opened 2018-07-20 11:53 UTC
Our search (by Epoq @ www.asmc.de ) gets blocked by Privacy Badger.
Would be nice if Privacy Badger wouldn't block Epoq so our customers
can use the search in our onlineshop.

**Comment by ghostwords** [comment] 2018-07-20 18:12
Is this a duplicate of #2108?

**Comment by ghostwords** [comment] 2018-07-20 18:14
Could you provide the debugging information requested in https://github.com/EFForg/privacybadger/blob/1cac5ba752517802d0596645c464ffd55a60c9d0/.github/ISSUE_TEMPLATE/broken-site-report.md?

**Comment by clem3ns** [comment] 2018-07-23 07:59
Yeah duplicated. Will close it

**Closed** 2018-07-23 07:59 UTC
Labels: broken app
