### ISSUE TITLE
Block by default

### ISSUE THREAD

**Issue by Chaython** [EFForg/privacybadger#2248] opened 2018-12-18 07:07 UTC
Around a 1k potential tracking sites; if you want to manually go through them you have to select them one by one; how about a block all potential?
I went through about the first 100; and they were all definitely tracking or malicious domains
Scrolling through the entire list I maybe saw 10 domains I would recognize as allowable; though they're likely still tracking :/
Would be more efficient for me to block all and the select which to not block :/
Similar to #1229 however I want it as a toggle and not a default; also a complete block not just blocking cookies; I already block all cookies by default using the native option within the respective browser
If not a toggle to block all "possibles" by default; perhaps bulk selection options such as shift clicking to highlight a group and then bulk blocking them...
Does privacy badger already have an extensive list of sites to block by default? Or does it always have to build the list per-instance? I know the purpose of this extension is to infer trackers and block them; but this could potentially be better for malicious protection than tracking; if it blocked all potential rather than those it "confirms"

**Comment by ghostwords** [comment] 2018-12-18 16:07
Hello!

Privacy Badger is meant to be a no-configuration-necessary, hands-off tool. Generally speaking, I suggest leaving the sliders alone and letting Badger do its job automatically.

Privacy Badger learns to block a domain once it sees that domain track you on three different websites. The idea is to stop trackers from following you around the Web; being allowed to load once or twice should not be a big deal.

>Does privacy badger already have an extensive list of sites to block by default? Or does it always have to build the list per-instance

It's both; we pre-train Privacy Badger before every update, and your Badger continues to learn from your browsing. Please see [our blog post](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start) to learn more.

Please note that when you tell your browser to deny all third-party cookies, Privacy Badger no longer gets to learn from cookies or HTML5 local storage set via JavaScript. Privacy Badger still gets to learn from third parties trying to set cookies via HTTP headers (as well as from other tracking techniques such as canvas fingerprinting), however.

We'll keep working on making Badger's automatic learning better while breaking fewer sites. We'll also keep working on making it more clear how Privacy Badger works and how it is meant to be used (#2021).

I'll mark this as a duplicate of #1422. Let me know if you have any questions.

**Closed by ghostwords** 2018-12-18 16:07 UTC

**Comment by Chaython** [comment] 2018-12-18 22:47
Still why not leave a toggle to block all "possible" ?
You seem to be saying because you don't want to break sites; but you could leave this toggle off by default with a large recommendation not to use it.
________________________________

**Comment by ghostwords** [comment] 2018-12-18 23:16
Right, if you block everything, Privacy Badger will break much more stuff than it does now. If you want to block everything by default, I don't think Privacy Badger is the right tool for you. I also don't think we should spend time making Privacy Badger into something it isn't meant to be, basically into a different kind of tool. We should focus on making Privacy Badger as good as it can be at what it already is for most people: a hands-off privacy tool to automatically learn about and stop non-consensual tracking across the Web.

If who want a high degree of control over exactly what gets to load on every website, I recommend learning to use uMatrix (brought to you by the same person who works on uBlock Origin). You could also use uBlock Origin in "advanced" mode, which is sort of like uMatrix-"lite".
