### ISSUE TITLE
Tracker count on the same page is inconsistent

### ISSUE THREAD

**Issue by aschrijver** [EFForg/privacybadger#2172] opened 2018-09-26 07:51 UTC
So I was editing a response to a Discourse post in the [Humane Tech](https://humanetech.com) community: [Recent changes to Google Chrome cause huge uproar in tech community!](https://community.humanetech.com/t/recent-changes-to-google-chrome-cause-huge-uproar-in-tech-community/2732) when I noticed Privacy Badger to report 22 (!!) trackers on this page.

I've seen this behavior for some time, but always the trackers were added when including open graph link previews in a post. I know Discourse usually does not have that many trackers (usually just 2 or 3), so I looked at the source, but could not detect where this count was coming from.

So I opened the same page on a new tab. This time the count icon on the toolbar showed 0 trackers, but the dropdown menu showed there were 2 trackers (the regular Discourse ones). Strange.

Then on that tab I pressed 'Duplicate tab' and now on the new tab Privacy Badger does not keep any count. The dropdown menu is just the logo and 'Donate to EFF'. A reload of the page does not change this.

It seems like this is a bug in Privacy Badger.

I am using PB `2018.9.20` installed on FF `61.0.1` on Ubuntu `16.04`

**Comment by ghostwords** [comment] 2018-09-26 15:08
It's probably something about Service Workers confusing Privacy Badger in Firefox. Previously: https://github.com/EFForg/privacybadger/issues/1953#issuecomment-379879534. I think these issues are all a duplicate of #1144.

**Comment by ghostwords** [comment] 2018-09-26 15:11
Which domains does Privacy Badger report in the popup when this happens?

**Comment by aschrijver** [comment] 2018-09-26 22:05
I had closed the one with 22 trackers. Also there is no easy way to copy the trackers AFAIK, also screenshot is hard, as the menu disappears when snapping.

Currently I have 3 tabs open on the same page, one with 0, one with 1, and one with 4 trackers. I think the actual number of trackers should be 2: `avatars.discourse.org` and `community.humanetech.com` (at least I think so, since these are most commonly shown, but the numbers vary continuously)

**Comment by ghostwords** [comment] 2018-11-07 20:49
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1499523#c4, this should be fixed in Firefox when ["Service worker e10s redesign"](https://bugzilla.mozilla.org/show_bug.cgi?id=1231208) is complete. We may release workarounds in Privacy Badger before then, however.

Closing as a duplicate of #1144.

**Closed by ghostwords** 2018-11-07 20:49 UTC
Labels: Firefox, bug, duplicate

**Comment by ghostwords** [comment] 2018-11-07 20:54
@aschrijver As per https://bugzilla.mozilla.org/show_bug.cgi?id=1499523#c4, you could confirm if toggling "dom.serviceWorkers.parent_intercept" in `about:config` and restarting Firefox makes this issue go away. Be sure to restore the setting to its default state afterwards as the setting apparently disables important security protections around service workers.
