### ISSUE TITLE
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by Vinnl** [EFForg/privacybadger#2404] opened 2019-06-20 10:25 UTC
I guess this is the same as #2156 and #2374, but it just occurred for me now even though those are closed, and it asked me to report it, so...

Privacy Badget showed this error:

> InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

![image](https://user-images.githubusercontent.com/4251/59842120-217fb980-9356-11e9-95ec-ce3116eb5b4f.png)

Not sure what else to do with it.

**Edit:** Oh, this might have to do with the fact that I'm getting close to my disk space limit?

**Comment by ghostwords** [comment] 2019-06-20 12:08
Disk space limit: yes, possibly, but it's not clear that's the cause.

Is your disk low on space? And if you restart Firefox, does this happen again?

Indeed a duplicate of #2156. I'll close this as this isn't something Privacy Badger can do anything about probably. Happy to continue to discuss though.

**Closed by ghostwords** 2019-06-20 12:08 UTC
