### ISSUE TITLE
Privacy Badger blocks trackers on sites where I've disabled it, if there is a redirect

### ISSUE THREAD

**Issue by mastazi** [EFForg/privacybadger#2706] opened 2020-10-26 04:04 UTC
#### What is your browser and browser version?

Firefox 82.0 (64-bit)
Brave 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)

#### What is broken and where?

Privacy Badger every now and then blocks trackers on sites where I've disabled it. I can see the greyed out Privacy Badger icon (which signifies it is disabled in the current site) and yet I can see the little yellow badge in the corner (telling me that a certain number of trackers has been blocked in the current page).

After refreshing, it works as intended, so it's really hard to reproduce this issue as it happens seemingly randomly.

The issue started happening after this change and I had never experienced it before: https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better

**Comment by ghostwords** [comment] 2020-10-26 15:25
Hello and thanks for getting in touch!

Is this something that happens in both Firefox and Brave? Can you share the sites where this happens?

**Comment by ghostwords** [comment] 2020-10-26 16:08
This sounds like a duplicate of #1997, although I haven't yet reproduced the badge behavior. Does this happen when opening links to a disabled site into a new tab in the background?

**Comment by mastazi** [comment] 2020-10-26 22:15
@ghostwords interesting now that I think of it, I open background tabs very often, I will test.
PS yes it happens both in Firefox and Brave

**Comment by mastazi** [comment] 2020-10-26 22:25
@ghostwords I was just able to reproduce it and I think that the problem is with 301 redirections.

The website of the company I work for, 301-redirects from root domain plastiq.it to subdomain www.plastiq.it

If I follow the link https://plastiq.it the redirection will occur, and I am able to reproduce this every time in Brave (at the moment I can't reproduce on Firefox though)

However if I follow the link https://www.plastiq.it then there is no redirection, and the bug does not happen.

When it happens, you can see not only the badge:

![2020-10-27 09_16_39-Window](https://user-images.githubusercontent.com/1661655/97234981-08cec000-1836-11eb-821d-a3d20f7aff34.png)

But also some elements being blocked (some of the logos on our site, such as "Bohoo" and the "Card network" are served from an advertising network, so if Privacy Badger was active, it would be correct for it to block them - the problem is that I have it turned off)

![2020-10-27 09_17_17-Window](https://user-images.githubusercontent.com/1661655/97235113-492e3e00-1836-11eb-98b1-e86a2ddf4e27.png)
![2020-10-27 09_17_28-Window](https://user-images.githubusercontent.com/1661655/97235122-4cc1c500-1836-11eb-8d7c-9f8e08fcedc3.png)

**Comment by ghostwords** [comment] 2020-10-27 22:09
Interesting! Thank you for figuring out reproductions steps.

**Comment by ThomasFogwell** [comment] 2020-11-11 05:07
I'm seeing something similar with Notion.so. Privacy badger is disabled for the site and when an export happens it breaks Notion. I'm not certain if it involves a redirect. 

I don't mean to hijack the thread if this is not related I will start a new one. 

![image](https://user-images.githubusercontent.com/18213584/98771082-17ec6b00-23fd-11eb-8b47-d7cf4227f4f5.png)

**Comment by ghostwords** [comment] 2020-11-11 16:38
The export issue sounds like #2234.

**Comment by ghostwords** [comment] 2020-11-17 18:29
This is yet another tab attribution bug. Privacy Badger needs to (synchronously) know the tab URL for any given tab ID while processing requests. This is [not supported by Chrome extension APIs](https://bugs.chromium.org/p/chromium/issues/detail?id=856766#c6). (We should be able to resolve this class of bugs with [Firefox-specific APIs](https://github.com/EFForg/privacybadger/pull/2198/files#diff-93196b7720cb23d3dad418fe60c02cf704c2d472f02ac72cc1593a0c7229b244R457-R477), however. Although this particular issue doesn't seem to affect Firefox.)

`www.joinjamjar.com.au` uses Service Workers. The first time you visit it via `plastiq.it` in Chrome, Privacy Badger gets an `onBeforeNavigate` event for `plastiq.it`, an `onBeforeRequest` for  `plastiq.it`, and another `onBeforeRequest` for `www.joinjamjar.com.au`.

The second time you navigate to `plastiq.it` in Chrome, Privacy Badger gets the `onBeforeNavigate` for `plastiq.it` and the first `onBeforeRequest`, the one for `plastiq.it`. Privacy Badger doesn't know it's actually on `www.joinjamjar.com.au` at this point because the `www.joinjamjar.com.au` was served by a cached Service Worker (cached requests bypass the `webRequest` API).

Our previous workaround to handle Service Workers (#2454) doesn't help here because Chrome doesn't fire an `onBeforeNavigate` event for the destination page on redirection. It seems like it should though ... I wonder if this is also because of caching.

The popup shows up as disabled because it gets the correct tab URL asynchronously from the browser using `chrome.tabs.query()`.

**Comment by ghostwords** [comment] 2020-11-17 18:32
You could work around this problem by adding `plastiq.it` to Privacy Badger's list of disabled sites on the options page.

**Comment by mastazi** [comment] 2020-11-17 22:32
Thank you @ghostwords I will do that as a workaround, and thanks for the very detailed explanation above

**Closed** 2022-11-01 21:25 UTC
Labels: bug, Chrome, heuristic
