### ISSUE TITLE
Block cookies by default for potential tracking domains

### ISSUE THREAD

**Issue by brenthuisman** [EFForg/privacybadger#1229] opened 2017-03-02 10:01 UTC
Maybe I misunderstand how Privacy Badger works, but I see some domains showing up in the list of possible tracking domain, and they in fact definitely are, but the default policy seems to be to do nothing (at first perhaps? could find documentation on that). I was wondering if an option in the preferences could be considered where a bit more aggressive behavior can be set to be default, namely cookie-blocking suspected domains as soon as they are suspect.

**Comment by ghostwords** [comment] 2017-03-02 14:52
I'll mark this as a duplicate of #1016. Let me know if that's not the case.

Privacy Badger will start blocking a tracker once it sees that tracker on three separate websites. @cooperq What's the best place to point to for the rationale behind this logic?

The real problem might be that this behavior isn't obvious to users who open Badger's popup. This might also lead to users learning to manually block domains (wasting labor and making it more likely for PB to break sites).

**Closed by ghostwords** 2017-03-02 14:52 UTC

**Comment by ghostwords** [comment] 2017-03-02 14:57
Also #1090. This will keep coming up until we make it clear why Badger doesn't block right away.

**Comment by ghostwords** [comment] 2017-03-02 15:04
More: #1072, #960, #925 (sort of), #889, ...

**Comment by brenthuisman** [comment] 2017-03-02 15:11
It's not that obvious, before installation, that Privacy Badgers 'learns', and certainly not how (it's not on the FAQ page and that page isn't great in any case). Thanks for your explanation @ghostwords! Indeed, #1016 is what I was thinking of.

**Comment by ghostwords** [comment] 2017-03-02 23:45
PB actually used to have a "why isn't anything blocked" feature: aa64ef2d5550977b494f26af8ba8eec2c0e805c7. @cooperq Do you remember why it was removed?

**Comment by cooperq** [comment] 2017-03-06 21:22
Nope. Maybe UI reasons?
