### ISSUE TITLE
Privacy Badger clears Youtube caption settings

### ISSUE THREAD

**Issue by jimbo1qaz** [EFForg/privacybadger#1980] opened 2018-04-22 18:11 UTC
Privacy Badger has a feature to clear Local Storage. When the extension is enabled, I frequently lose my Youtube caption settings:

![image](https://user-images.githubusercontent.com/913957/39081920-e0ddde44-44fe-11e8-9328-014a5454c9b6.png)

Is it possible to fix this bug?

**Comment by ghostwords** [comment] 2018-04-22 18:28
Looks like YouTube stores these settings in the `yt-html5-player-modules::subtitlesModuleData::display-settings` local storage key for `https://www.youtube.com`. It doesn't seem like Privacy Badger should have any effect on this as this is first-party storage.

**Comment by jimbo1qaz** [comment] 2018-04-22 20:59
Some time ago, before filing this bug, I grepped through my addon source codes and found that only Privacy Badger mentioned localstorage. I recall disabling this extension for a while, and not getting any Youtube captions cleared. To make sure, I'll run Chrome for a while with Badger disabled and close this issue if it's not Badger's fault. Anything else I can do to test?

I've attached a photo of browser extensions (since I cannot Ctrl+A or Ctrl+S the extensions page due to user-hostile Shadow DOM behavior). Note that ScriptSafe is *not* the cause, as I installed it a few days ago and have been experiencing this issue for months. I have HTTPS Everywhere and uBlock Origin and The Great Suspender installed in another Chrome profile without issue.

![chrome_2018-04-22_13-55-24](https://user-images.githubusercontent.com/913957/39099801-feecd1d8-4634-11e8-9acd-61ea8a00f965.png)

**Comment by ghostwords** [comment] 2018-04-22 23:00
You could disable Privacy Badger just on YouTube by clicking on the "Disable Privacy Badger for This Site" button in Badger's popup while on a YouTube page.

I suggest installing Privacy Badger into a new profile, importing your Badger data from your existing profile, and attempting to reproduce the problem on YouTube with no other extensions installed.

**Comment by ghostwords** [comment] 2018-04-28 15:56
I'm going to close this for now. Let me know if you have any updates.

**Closed by ghostwords** 2018-04-28 15:56 UTC
Labels: unable to reproduce
