### ISSUE TITLE
Incorrect size of popup window

### ISSUE THREAD

**Issue by Kilill** [EFForg/privacybadger#1203] opened 2017-02-13 17:26 UTC
The slider poppup window (that appears when clicking on the icon in the menu bar) is to narow / not dynamically sized, which makes it a bit difficult to set the sliders.

The poppup behaves correctly if opened via the "Open Menu" icon.

Browser: Mozilla Firefox for  Ubuntu 51.0 64 bit , Ubuntu 15.10

![badger](https://cloud.githubusercontent.com/assets/12996386/22894302/ca319954-f218-11e6-9c11-b81d918489a8.png)

**Comment by cowlicks** [comment] 2017-02-16 01:22
Thanks for the report @Kilill ,
What version of privacy badger do you have?
What is the "open menu" icon? I don't see it in my Firefox.

**Comment by Kilill** [comment] 2017-02-16 12:22
Version of Badger: 2017.1.26

adding 3 screen shots: 

badger1.png that shows the location of the "menu icon" in this case opened
and having the badger icon as part of that menu.

Badger2.png shows the badger popup as clicked from the above menu i didnt realize before, but this window is also to narrow
for the sliders to show properly.

Badger3.png  here i moved the badger icon to the menubar and clicked it, as you see its now even narower

---

On onsdag 15. februar 2017 17.22.07 CET Blake Griffith wrote:
> Thanks for the report @Kilill ,
> What version of privacy badger do you have?
> What is the "open menu" icon? I don't see it in my Firefox.
> 
> 
--
Kim Lilliestierna
"Do wizards use spellchekers?" eller "Bruker skiløpere stavekontroll?"

**Comment by Kilill** [comment] 2017-02-16 12:23
Hmm might be an idea to also attach the screenshots ... 
so here we go again

On onsdag 15. februar 2017 17.22.07 CET Blake Griffith wrote:
> Thanks for the report @Kilill ,
> What version of privacy badger do you have?
> What is the "open menu" icon? I don't see it in my Firefox.
> 
> 

-- 
--
Kim Lilliestierna
"Do wizards use spellchekers?" eller "Bruker skiløpere stavekontroll?"

**Comment by Kilill** [comment] 2017-02-16 14:57
Hmm #2, sent the attachment as mail reply, doesn't seem to show up here in the issue list here on github, did you receive them or do i need to upload them here?

**Comment by cowlicks** [comment] 2017-02-16 19:37
@Kilill please re-upload them. I think emailing links to github works, for future reference. 

Takk skal du ha

**Comment by Kilill** [comment] 2017-02-17 08:49
Ok here they come.  And do i detect some scandinavian ties here ? :)

![badger1](https://cloud.githubusercontent.com/assets/12996386/23058539/ba870446-f4f5-11e6-9c8e-b7bdbf795b2f.png)

![badger2](https://cloud.githubusercontent.com/assets/12996386/23058559/d0f8b2a6-f4f5-11e6-9d5d-4d0b7d1ba791.png)

![badger3](https://cloud.githubusercontent.com/assets/12996386/23058571/db0ee8c8-f4f5-11e6-847a-2cb7310121d5.png)

**Comment by cooperq** [comment] 2017-02-27 20:49
related to #1217

**Comment by cooperq** [comment] 2017-02-27 20:50
duplicate of #1048 #1120

**Closed by cooperq** 2017-02-27 20:50 UTC
Labels: bug
