### ISSUE TITLE
Copy button on youtube widget placeholder

### ISSUE THREAD

**Issue by finn0** [EFForg/privacybadger#2687] opened 2020-09-18 13:43 UTC
**Type :** feature request

### Description
It would be nice, if PB has a copy button on Youtube's widget placeholder to copy video's URL to clipboard, easily. Similar to HTTPSEveryWhere's [copy button](https://github.com/EFForg/https-everywhere/issues/19385) on EASE page.

### Use case
This feature would handy for people who have set slider for `youtube.com` to `red`, but want watch some specific videos by either downloading it using `youtube-dl` or watch it later in their free time (by adding it todo manager), without allowing page to load information about video in their current browsing session. Currently, there is no other way to know video URL without allowing widget to load video.

**Comment by ghostwords** [comment] 2020-09-18 16:21
Thanks for the suggestion! I'll mark this as a duplicate of #2384.

**Closed by ghostwords** 2020-09-18 16:21 UTC
Labels: duplicate, enhancement, widgets
