### ISSUE TITLE
The buttons in the pop-up are sometimes not visible

### ISSUE THREAD

**Issue by realnc** [EFForg/privacybadger#1563] opened 2017-08-07 11:44 UTC
I am unable to access the controls in the PB pop-up in some pages:

![screenshot](https://user-images.githubusercontent.com/1665903/29025236-721d4994-7b7e-11e7-8c55-21b83ccab8e0.png)

The buttons at the bottom are cut off. In this case, it's not possible to disable PB for that page.

(In this case, the site was https://gitlab.com.)

Google Chrome Version 60.0.3112.78 (Official Build) (64-bit)
Gentoo Linux 64-bit

**Comment by ghostwords** [comment] 2017-08-07 22:04
Badger's popup doesn't work well when you increase the default page zoom level in Chrome settings. We are going to try to fix this in the next couple of Privacy Badger updates.

**Comment by ghostwords** [comment] 2017-08-07 22:05
Duplicate of #1113.

**Closed by ghostwords** 2017-08-07 22:05 UTC
Labels: bug, duplicate, ui
