### ISSUE TITLE
Causes issues while using Twitter

### ISSUE THREAD

**Issue by hook54321a** [EFForg/privacybadger#1727] opened 2017-10-16 03:33 UTC
Web Browser: Waterfox 55.2.2
Operating System: Windows 10

Steps to reproduce:
1. Install Waterfox
2. Open Waterfox
3. Install Privacy Badger.
4. Restart Waterfox (not sure if this is necessary or not)
5. Open Waterfox
6. Open Twitter
7. Log into Twitter
8. Wait until Twitter is completely loaded and then go to the URL bar and try to search for something
Result: It doesn't load the search page unless you do something like press the refresh button.

**Comment by ghostwords** [comment] 2017-10-16 14:04
Is this a duplicate of https://github.com/EFForg/privacybadger/issues/1337#issuecomment-324109443?

**Comment by hook54321a** [comment] 2017-10-21 22:43
I'm not sure

**Comment by ghostwords** [comment] 2018-02-27 22:42
Let me know if this is still an issue. Resolving for now.

**Closed by ghostwords** 2018-02-27 22:42 UTC
Labels: Firefox, bug
