### ISSUE TITLE
Unable to "disable privacy badger" for site or uninstall [enterprise policy installation in Chrome]

### ISSUE THREAD

**Issue by dscheidig** [EFForg/privacybadger#1541] opened 2017-07-31 19:25 UTC
I've encountered several wikia sites that privacy badger is blocking content on.  When I click the button in the top right corner of the chrome browser all of the options are greyed out and unclickable.  I can't click the button "disable for this site", I can't click the settings wheel, and if I try and disable the extension the option to disable is greyed out and I can't select it.  How can I disable privacy badger for these sites.

**Comment by ghostwords** [comment] 2017-07-31 19:28
Are you using Privacy Badger on Firefox in an Incognito window by any chance?

**Comment by dscheidig** [comment] 2017-07-31 19:31
No, I'm using chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by ghostwords** [comment] 2017-07-31 19:44
If, while on a page with this issue, you right-click on Badger's icon in Chrome's toolbar, select "Inspect popup", and then select the Console tab in the window that appears, do you see any error messages there?

Is Privacy Badger's UI broken on all sites or just some sites? Does restarting the browser fix the issue?

Are you saying that the option to disable Privacy Badger is disabled on the `chrome://extensions` page?

**Comment by dscheidig** [comment] 2017-07-31 19:47
There is no "inspect popup" option if I right click on the badger icon.

It's only broken on some sites, I'm able to disable it for some other sites.  Restarting/resetting the browser doesn't work

And yes, on the extensions page the checkbox for privacy badger is greyed out and I can't uncheck it

**Comment by ghostwords** [comment] 2017-07-31 19:55
Ah, sorry, to get the "Inspect popup" option, you have to first visit `chrome://extensions/` and enable Developer mode at the top of the page.

**Comment by dscheidig** [comment] 2017-07-31 19:58
I enabled developer mode, and selected the "inspect popup" but all it did was open privacy badger, and once again everything is greyed out.  I can't scroll to see everything blocked, I can't disable for the site, and I can't click the settings wheel.  The developer tool pop up window shows no errors : 
![image](https://user-images.githubusercontent.com/30604775/28795781-1fa0ab36-7609-11e7-9389-20e1abfbe0a2.png)

**Comment by ghostwords** [comment] 2017-07-31 20:00
I see, no errors, but Privacy Badger's buttons don't look disabled to me, that's how they usually look, no? (We may want to update their styling ...)

**Comment by dscheidig** [comment] 2017-07-31 20:01
I literally can't click any thing in that privacy badger window

**Comment by ghostwords** [comment] 2017-07-31 20:13
I am sorry, I haven't seen this kind of issue before; I am not sure what could be causing it.

As a workaround, you could try opening Badger's options page (maybe by right-clicking on Badger's icon and picking "Options"), adding the domain of the site you have issues with to Badger's list under the "Whitelisted domains" tab, and reloading that site's pages.

**Comment by ghostwords** [comment] 2017-07-31 20:16
I am also not sure why Badger's Enabled checkbox is grayed out for you on `chrome://extensions`. You could try uninstalling and reinstalling ... You should be able to preserve Badger's learning by exporting the data from the Manage Data tab on Badger's options page before uninstalling, and importing it after reinstalling.

**Comment by ghostwords** [comment] 2017-07-31 20:17
Regarding the ad blocking overlay on `wikia.com` sites, this is something we should really look into and fix for all Privacy Badger users. I think we get a lot of these with our error reports. I looked into it briefly, but haven't been able to reproduce getting the overlay yet, not sure what I'm missing.

**Comment by dscheidig** [comment] 2017-07-31 20:18
how do I uninstall it?  It doesn't show up under add/remove programs.  Also, adding a the domain to the whitelist works, but this is incredibly inefficient especially since I'd have to do that for every possible format of a site.  For example wikia.com, something.wikia.com something.something.wikia.com etc.  It doesn't look like wild cards work?  Like *.wikia.com ?

**Comment by dscheidig** [comment] 2017-07-31 20:19
nevermind, I see wildcards do work, but still very ineffective

**Comment by ghostwords** [comment] 2017-07-31 20:22
You should be able to remove Privacy Badger by clicking on the trash icon in its row on `chrome://extensions`. Remember to export your Badger's data first if you don't want to start from scratch (which is fine too).

![screenshot from 2017-07-31 16 20 21](https://user-images.githubusercontent.com/794578/28796657-670e324c-760c-11e7-92cf-3b6c984abb69.png)

**Comment by dscheidig** [comment] 2017-07-31 20:24
There is no trash icon because it's been installed by our enterprise policy.  However I've talked with my IT manager (I work in the IT dept as well) and our policy shouldn't prevent the removal or disabling of Privacy Badger

**Comment by ghostwords** [comment] 2017-07-31 20:28
I see, it sounds like the IT Policy installation (which I'm not familiar with) interferes with your ability to disable/uninstall the extension. Still no idea why your Badger popup doesn't respond to input on certain sites though.

**Comment by ghostwords** [comment] 2017-08-01 15:41
Could you provide a screenshot of Privacy Badger on your `chrome://extensions` page for future reference? Does it say, "installed by enterprise policy" under the grayed-out checkbox?

**Comment by dscheidig** [comment] 2017-08-01 15:43
Yes it does: 
![image](https://user-images.githubusercontent.com/30604775/28833862-a41fdc10-76ae-11e7-9937-63ca1d822555.png)

**Comment by rjackvony** [comment] 2017-08-07 14:16
I am also having the issue where I cannot click anything in the Privacy Badger window. This only happens to me in Chrome on my work Windows 10 computer.

Chrome version: Version 60.0.3112.90 (64-bit)

**Comment by ghostwords** [comment] 2017-08-18 15:58
@rjackvony Is your Privacy Badger also installed by "enterprise policy"?

**Comment by dscheidig** [comment] 2017-10-02 15:36
Still having this issue 3 months later.  any updates?

**Comment by ghostwords** [comment] 2017-10-03 01:30
I haven't gotten any other reports of Privacy Badger's popup being unclickable on certain sites.

You said this happens on certain sites only. Could you provide a few examples of sites the popup is broken for you, and a few examples of where the popup works?

When the popup is broken, is anything in it clickable? Can you visit the options page from the popup?

**Comment by dscheidig** [comment] 2017-10-03 18:23
It happens for any site. I used wikipedia.com as an example.  I may have some more details. It looks like it might be related to multiple windows being open.  I am running with 3 screens. if I open chrome on the main screen privacy badger, for the most part, works, in any tab on that window. if I open a new chrome window on the second screen to the right, privacy badger is greyed out for all sites

**Comment by ghostwords** [comment] 2017-10-03 21:28
Ah, good to know! So this is a problem with Chrome windows on a secondary monitor. What is your operating system version? Does this problem happen to any other Chrome extensions with browser popups?

**Comment by dscheidig** [comment] 2017-10-03 21:29
it actually appears to happen with any chrome extension

**Comment by ghostwords** [comment] 2017-10-03 21:33
I am not sure I see this bug filed already, here is a search for [`"secondary monitor" popup`](https://bugs.chromium.org/p/chromium/issues/list?can=2&q="secondary+monitor"+popup&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids). Would you mind opening a new https://crbug.com issue?

**Comment by ghostwords** [comment] 2017-11-28 22:36
Being unable to use Privacy Badger's popup on a secondary monitor might be one or both of these Chrome issues:

- [Mouse pointer issue in chrome extension while accessing it from additional monitor screen](https://bugs.chromium.org/p/chromium/issues/detail?id=667659)
- [Mouse cursor alignment wrong on extension popup window (on secondary monitor with different DPI) on Windows 10](https://bugs.chromium.org/p/chromium/issues/detail?id=659642).

Possibly related reports: #1744, #1787.

**Comment by ghostwords** [comment] 2017-11-30 20:08
Closing as a duplicate of #1787.

**Closed by ghostwords** 2017-11-30 20:08 UTC
Labels: broken site, bug, Chrome, ui

**Comment by ghostwords** [comment] 2018-01-25 18:42
There seems to be a workaround for the multi-monitor Chrome bug: https://github.com/EFForg/privacybadger/issues/1787#issuecomment-360475604
