### ISSUE TITLE
Layout seems to be broken when icon is hidden in menu (Firefox)

### ISSUE THREAD

**Issue by atelierabintra** [EFForg/privacybadger#1751] opened 2017-10-29 13:15 UTC
Hi there,

A few months ago Privacy Badger started displaying wonky for me when the icon is hidden in menu.

![untitled-1](https://user-images.githubusercontent.com/33198403/32144035-df8da2a2-bd06-11e7-8734-16ade2f1bf8f.jpg)

However, when the icon is moved to the toolbar then it displays as normal.

![untitled-2](https://user-images.githubusercontent.com/33198403/32144044-064c24ae-bd07-11e7-9af3-ba48d844704a.jpg)

Any idea what could be causing this? I've been using Firefox 47, but after updating to 56.0.2 today the problem didn't improve. I have Javascript enabled and I'm running on a Windows 8.1 machine.

There's absolutely no problem with Privacy Badger on Chrome, however. It displays normally whether the icon is on the toolbar or in the menu.

Thank you in advance. ^^

**Comment by ghostwords** [comment] 2017-10-29 18:29
Duplicate of #1120.

**Closed by ghostwords** 2017-10-29 18:29 UTC
Labels: bug, duplicate, Firefox, ui

**Comment by ghostwords** [comment] 2017-10-29 18:34
I think what happened was this broke in the move from the legacy Firefox add-on infrastructure ([1.9.2](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/versions/1.9.2) is the final legacy add-on version) to WebExtensions.
