### ISSUE TITLE
pb seen as adblocker

### ISSUE THREAD

**Issue by urfausto** [EFForg/privacybadger#2656] opened 2020-07-30 18:34 UTC
https://www.money.it identifies privacybadger as an adblocker, is it normal?

**Comment by ghostwords** [comment] 2020-07-30 19:24
It's "normal", but not good. I'll mark this as a duplicate of #1596.

**Closed by ghostwords** 2020-07-30 19:24 UTC

**Comment by urfausto** [comment] 2020-07-30 19:57
> It's "normal", but it's not good. I'll mark this as a duplicate of #1596.

may you elaborate?

**Comment by ghostwords** [comment] 2020-07-30 20:29
Please see my comments in the linked issue and let me know if you have any questions here.

**Comment by urfausto** [comment] 2020-07-30 21:19
i mean is this an accepted behaviour or needs to be fixed?

**Comment by ghostwords** [comment] 2020-07-30 22:01
Have you looked at #1596? Yes, this is a problem.

**Comment by urfausto** [comment] 2020-07-31 08:14
> Have you looked at #1596? Yes, this is a problem.

yeah, and is it fixable?

**Comment by ghostwords** [comment] 2020-07-31 13:02
You could write to money.it and tell them [Privacy Badger is not an adblocker](https://privacybadger.org/#Why-does-Privacy-Badger-block-ads).

In the meantime, you could either disable Privacy Badger on money.it, or figure out which of the trackers is causing the message to appear and move the slider for that tracker to "yellow" (block cookies) or "green" (fully allow). If you figure out the responsible tracker domain, please let us know here.

We consider the general problem of Privacy Badger triggering adblocker messages a serious issue. You could subscribe to #1596 for updates.

**Comment by urfausto** [comment] 2020-07-31 13:30
> We consider the general problem of Privacy Badger triggering adblocker messages to be a serious issue that we would like to respond to eventually. Please subscribe to #1596 for updates.

done, thanks.



> or figure out which of the trackers is causing the message to appear and move the slider for that tracker to "yellow" (block cookies) or "green" (fully allow). If you figure out the responsible tracker domain, please let us know here.

i have found out what slider is causing the issue and it is always google (who else?):
tpc.googlesyndication.com
i only switched it to yellow and no more adblock messages pop up

**Comment by urfausto** [comment] 2020-08-01 07:25
it's weird but today anti adblock frames popped up again and i had to turn yellow also **pagead2.googlesyndication.com**

**Comment by urfausto** [comment] 2020-08-05 10:52
today, popup showed up again -_____________________________________________-
disabled **www.google-analytics.com** and seems working again

wtf is happening?!?!

**Comment by urfausto** [comment] 2020-08-07 07:36
today popup again. i don't know eventually what is causing it. i will try to contact the website owners.
