### ISSUE TITLE
Helping user in selective filtering

### ISSUE THREAD

**Issue by nextLane** [EFForg/privacybadger#711] opened 2015-12-19 09:58 UTC
We can make the display of list of links that track the users, more user friendly, as in if the user is able to know what that link is exactly responsible for in that particular webpage he/she can decide whether to block it or not. One probable way of doing it might be that when I hover over the link PB marks the portion of webpage the link is affecting (if it is affecting visibly at all) or we can give informative labels to the links to help user filter out.

**Comment by cooperq** [comment] 2015-12-23 18:59
Hmm, that is an interesting idea. Might be tricky to implement but I definitely would not be opposed to it.

**Comment by ghostwords** [comment] 2017-03-31 13:54
Seems related to #320.

**Comment by ghostwords** [comment] 2017-09-05 13:48
Might be a duplicate of #688.

**Comment by ghostwords** [comment] 2018-07-24 22:31
We would like Privacy Badger to become an install-and-forget kind of extension. Anything that gets into customizing sliders needs to be clearly worth it benefit/complexity-wise. This proposal seems complex, while we already have a recommended alternative for when sites break, which is to use the "Disable Privacy Badger for This Site" button. Closing as "wontfix".

**Closed by ghostwords** 2018-07-24 22:31 UTC
Labels: enhancement, ui, ux
