### ISSUE TITLE
Delete list of allowed domains after x number of days

### ISSUE THREAD

**Issue by samuel8941** [EFForg/privacybadger#2320] opened 2019-02-24 17:58 UTC
The list of allowed domains is basically a collection of all domains ever visited, which is a privacy hole, and it can not separately be deleted. 

The list has no practical purpose, so I propose allowed domains should not be saved by default at all. 

Simply allow everything that is not blocked or partially blocked. Alternately automatically purge the list of allowed domains after x days, or let the user delete it without having to delete the blocked and partially blocked domains, which serve a purpose.

**Comment by ghostwords** [comment] 2019-02-24 18:09
Hello!

Privacy Badger only keeps track of which third-party domains were seen tracking on which sites. Once Privacy Badger sees the same third-party domain track you on three separate sites, Privacy Badger will either block or "cookieblock" that domain.

As this is a privacy concern, I'll close this as a duplicate of #266. Let me know if you have any questions.

**Closed by ghostwords** 2019-02-24 18:09 UTC

**Comment by samuel8941** [comment] 2019-02-24 18:14
thanks for your input.

I think offering an option to purge all allowed domains only and keep everything else is not covered by #266, so that may be a worthwhile endeavour. 

I also do not understand why the process of categorizing third-party domains requires a list of allowed domains at all.

**Comment by ghostwords** [comment] 2019-02-24 18:30
The thing is that the "allowed domains" are only there because there are tracking domains that have only been seen tracking once or twice. So if you purge them, you're messing with Privacy Badger's learning.

If you'd like to avoid having anything get recorded by Privacy Badger, I suggest using a Private or Incognito window. Privacy Badger does not learn (or record anything) in Private windows by default. 

Let me know if this helps.

**Comment by samuel8941** [comment] 2019-02-24 18:32
Thanks, I am not really bothered by it, but simply thought it could be worthy to add, as I had seen such logs came up as a criticism. I don't know the technical details and whether other unauthorized apps, be it on the OS layer or within the browser, could access such list.

**Comment by ghostwords** [comment] 2019-02-24 18:36
My take is that if you have malware on your computer, you have bigger things to worry about (than a list of tracking domains you've seen in your non-private browsing).
