### ISSUE TITLE
Chrome: issue showing charting graphs on investing.com

### ISSUE THREAD

**Issue by zrodrps** [EFForg/privacybadger#1915] opened 2018-03-20 22:39 UTC
Hello!

There are some errors when using PB at investing.com viewing chart graphs. This issue is resolved when I disable the extension, but not if I only disable PB. It seems that I can't enable the extension without seeing error on charting views.

Please see pics with enabled and disabled PB extension.
![investing com badger](https://user-images.githubusercontent.com/37600191/37686455-d8087286-2c97-11e8-9be3-e1dc6429b80a.PNG)
![investing com no badger](https://user-images.githubusercontent.com/37600191/37686461-dc5b37ce-2c97-11e8-92fa-800dcc1c7b73.PNG)
![investing com badger2](https://user-images.githubusercontent.com/37600191/37686462-e01b5c18-2c97-11e8-8b4d-4961134a25f9.PNG)
![investing com no badger2](https://user-images.githubusercontent.com/37600191/37686463-e1cbedfc-2c97-11e8-8685-d94999a02d7b.PNG)

**Comment by ghostwords** [comment] 2018-03-20 22:48
Hello! The part about the visual chart issues not going away even after telling Privacy Badger to not do anything on the site should be fixed with the next Privacy Badger update, due in the next few days. Marking the rest as a duplicate of #1854.

**Closed by ghostwords** 2018-03-20 22:48 UTC
