### ISSUE TITLE
Extension not from chrome webstore

### ISSUE THREAD

**Issue by gh0sti** [EFForg/privacybadger#1733] opened 2017-10-17 01:17 UTC
Chrome keeps saying that Privacy Badger isn't from the Chrome Webstore even though I just installed again from the web store after it got corrupted recently

**Comment by ghostwords** [comment] 2017-10-17 02:48
Duplicate of #1496.

**Closed by ghostwords** 2017-10-17 02:48 UTC
Labels: Chrome, duplicate, wontfix

**Comment by ghostwords** [comment] 2017-10-17 02:50
> after it got corrupted recently

How did Privacy Badger get corrupted?

**Comment by gh0sti** [comment] 2017-10-29 22:02
idk how had that with couple of my extensions saying they were corrupted they are working now.
