### ISSUE TITLE
Add versioning to yellowlist/DNT hashes updating

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1576] opened 2017-08-15 00:48 UTC
Instead updating the internal cookieblocked state by diffing the existing CBL with the one pulled from the EFF. We should use versions, probably based on timestamps. This way we will only update when we receive a version we know is newer than the existing version.

**Comment by ghostwords** [comment] 2017-10-16 16:17
Marking as a duplicate of #1623.

**Closed by ghostwords** 2017-10-16 16:17 UTC
Labels: enhancement, yellowlist
