### ISSUE TITLE
ERR_INSUFFICIENT_RESOURCES error in Chromium 57

### ISSUE THREAD

**Issue by cynddl** [EFForg/privacybadger#1322] opened 2017-04-16 11:58 UTC
I recently ran into an error with the Privacy Badger extension on Chromium: ```ERR_INSUFFICIENT_RESOURCES``` (with 272MB used by the extension on my computer, which does not seem unusual).

Killing the extension and restarting it solved the problem. Not sure what happened, opening this issue to let you know. Maybe a caching error?

**Comment by shanempope** [comment] 2017-04-17 03:17
I have been getting this error as well recently.

**Comment by ghostwords** [comment] 2017-04-17 14:04
Can you find a set of steps that consistently get this error to happen?

**Comment by shanempope** [comment] 2017-04-17 14:40
No, is there any sort of privacy browser log I could look at to help next time it happens?

**Comment by ghostwords** [comment] 2017-04-17 14:46
It's possible that this is caused by periodic Do Not Track policy rechecking, which we fixed in Badger version 2017.3.28 and which we will remove in the next update. If so, you shouldn't run into this anymore once #1312 is released.

**Comment by ghostwords** [comment] 2017-04-21 01:09
This should be fixed as of Privacy Badger version 2017.4.19.1, released yesterday. Let me know if it isn't.

**Closed by ghostwords** 2017-04-21 01:09 UTC
Labels: bug, Chrome, performance
