### ISSUE TITLE
Click Coordinates off in Dropdown Control Menu [Chrome bug with multiple monitors]

### ISSUE THREAD

**Issue by LeeGDavis** [EFForg/privacybadger#1787] opened 2017-11-24 17:46 UTC
Windows 10pro x64
Privacy Badger: 2017.11.20.
Chrome: 62.0.3202.94 
Firefox: 57.0

I run a 4 monitor setup and depending on the monitor scale, in Chrome, the coordinates on the pointer don't line up with the buttons in the options. For example on 100%, if I hover about 15-20 pixels above the given button I can see that it is selected and the click is registered. However all the way up to 250% (4k), the coordinates are so off that it is not possible to click anything.

It seems scaled to 150% (2560x1600) works fine, however 100%(1680x1050), 125%(1920x1200), 250%(3840x2160) for example the coordinates are off. I don't know if it is relevant, but I also run an nvidia optimus m2200 with intel p630 on chip graphics.

Chrome (My pointer is roughly hovering over the line of text, 'handles each one...', and you can see that 'Disable Privacy Badger...' is highlighted as if it is being hovered:
![image](https://user-images.githubusercontent.com/3057514/33220160-0134513c-d0fb-11e7-90f4-0ce8419f4692.png)

Firefox on the other hand is unusable with scaling issues.  
![image](https://user-images.githubusercontent.com/3057514/33220035-7a4e4c7c-d0fa-11e7-8415-06cd40667e4a.png)

I should also note that both of the above snips are taking on a Monitor with 100% scaling and oddly enough both work fine on the monitor scaled to 150% (2560x1600).  This issue could also be related to #1744 and #1113

**Comment by ghostwords** [comment] 2017-11-28 22:26
This seems like a browser bug, perhaps one or both of these:

- [Mouse pointer issue in chrome extension while accessing it from additional monitor screen](https://bugs.chromium.org/p/chromium/issues/detail?id=667659)
- [Mouse cursor alignment wrong on extension popup window (on secondary monitor with different DPI) on Windows 10](https://bugs.chromium.org/p/chromium/issues/detail?id=659642).

**Comment by ghostwords** [comment] 2017-11-28 22:30
This might be a duplicate of #1744. I don't think #1113 is related.

**Comment by ghostwords** [comment] 2017-11-28 22:30
Can you reproduce a similar problem with other extensions?

**Comment by ghostwords** [comment] 2017-11-28 22:32
This seems related: https://github.com/andryou/scriptsafe/issues/253#issuecomment-332506440.

**Comment by LeeGDavis** [comment] 2017-11-28 22:38
@ghostwords good call.  Not all extensions, however, I see very similar behaviour on others too.  Stylish extension being the closest as far as similarities with coordinates and where something is actually "clickable".  So Privacy Badger is not alone here...

**Comment by jfhorn** [comment] 2018-01-25 14:05
SOLUTION: Per the Chromium forums, disable this flag in the browser/Chrome:
[chrome://flags/#enable-use-zoom-for-dsf
](chrome://flags/#enable-use-zoom-for-dsf)

This is a browser issue and in theory, the browser could auto-disable this feature if it detected multiple monitors running at different DPIs (or is it resolutions?).  This did not break browser functionality for me.

**Comment by LeeGDavis** [comment] 2018-01-25 17:19
@jfhorn Things seem a lot better for me in Chrome 64 and Firefox 58, without making any changes.

**Comment by ghostwords** [comment] 2018-02-27 14:56
This appears to be fixed as of Chrome 64: https://bugs.chromium.org/p/chromium/issues/detail?id=659642#c62.

**Comment by jfhorn** [comment] 2018-02-27 15:32
Confirmed as fixed.

I turned-off the disabling chrome://flags/#enable-use-zoom-for-dsf workaround (set it back to enabled or default), and my extensions (Ad Block Plus and Privacy Badger) again function correctly.

**Closed** 2018-02-27 15:34 UTC
Labels: Chrome, bug, ui
