### ISSUE TITLE
Chrome's Privacy Badger breaks Twitter when connecting via corporate proxy

### ISSUE THREAD

**Issue by alexandru** [EFForg/privacybadger#2672] opened 2020-08-25 09:46 UTC
#### What is your browser and browser version?

Chrome 84.0.4147.135, running on macOS Catalina 10.15.6.

#### What is broken and where?

Privacy Badger breaks [Twitter](https://twitter.com/) when connecting via a corporate proxy. At work we can connect via a VPN, requiring a corporate proxy to connect to the Internet.

Notes:

- Privacy Badger on Firefox on the other hand works fine
- Disabling Privacy Badger for Twitter.com does not work, what works is disabling the extension completely in Chrome, or disconnecting from the VPN/proxy

#### What is the "culprit" domain?

Calls to `api.twitter.com` fail with `net::ERR_FAILED`. 

#### What is your debug output for this domain?

Unfortunately the debug output isn't helpful, because this isn't an issue of Privacy Badger wrongfully flagging this domain:

```
**** ACTION_MAP for twitter.com
api.twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
platform.twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1582162919502,
  "userAction": ""
}
syndication.twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
**** SNITCH_MAP for twitter.com
twitter.com [
  "msn.com",
  "bitly.com",
  "espn.com",
  "alexn.org"
]
```

If it helps, not sure how, here's what I see in the console:

![image](https://user-images.githubusercontent.com/11753/91159597-eeab2100-e6d0-11ea-8505-ef1f181ce83f.png)

**Comment by ghostwords** [comment] 2020-08-25 14:10
Thanks for letting us know! Is this the same issue as #2418? It might be worth opening a crbug.com issue.

**Comment by ghostwords** [comment] 2020-11-17 20:54
Closing as a duplicate of #2418. Let me know if you have any more information.

**Closed by ghostwords** 2020-11-17 20:54 UTC
Labels: Chrome, bug, duplicate
