### ISSUE TITLE
broken website2

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadger#1089] opened 2016-12-17 01:38 UTC
@cooperq 
video not playing on this website
`http://economictimes.indiatimes.com/et-now/daily/demonetisation-was-needed-in-1971-we-are-late-narendra-modi/videoshow/56021422.cms`

blocking of s0.2mdn.net completely ; prevents video from playing...
![screenshot 86](https://cloud.githubusercontent.com/assets/20338483/21283390/6a3b937a-c427-11e6-97fe-97433f5ff97e.png)

moving to cookie block solves the problem

![screenshot 87](https://cloud.githubusercontent.com/assets/20338483/21283393/769be4bc-c427-11e6-85a1-194670672e98.png)

**Comment by ghajini** [comment] 2016-12-17 20:19
completely broken
http://www.givemesport.com/939951-dave-meltzer-claims-wwe-need-to-cash-in-on-tye-dillingers-momentum-at-the-royal-rumble
![screenshot 88](https://cloud.githubusercontent.com/assets/20338483/21289446/1c411e5e-c4c4-11e6-8ff8-f7c7d6932970.png)
![screenshot 89](https://cloud.githubusercontent.com/assets/20338483/21289447/1c4239b0-c4c4-11e6-8daf-fb08371ceac2.png)

with privacy badger disabled site loads its content completely

![screenshot 90](https://cloud.githubusercontent.com/assets/20338483/21289451/290970a0-c4c4-11e6-8df4-577a27a25eb9.png)

**Comment by ghajini** [comment] 2016-12-17 20:44
another one 
www,jagran.com

blocking of edgesuit.net allows browser to display website improperly
![screenshot 91](https://cloud.githubusercontent.com/assets/20338483/21289615/5e6df5d8-c4c7-11e6-896d-deec46d74ac2.png)

movie it to cookkieblock only preserves site display properly
![screenshot 92](https://cloud.githubusercontent.com/assets/20338483/21289623/a7322708-c4c7-11e6-85cb-3a1722a24bd8.png)

**Comment by ghostwords** [comment] 2017-10-06 00:29
Duplicate of #1236.

**Closed by ghostwords** 2017-10-06 00:29 UTC
Labels: broken site, good volunteer task

**Comment by ghostwords** [comment] 2017-10-06 00:31
`azureedge.net` fixed in #1644.

**Comment by ghostwords** [comment] 2017-10-06 00:33
For `edgesuite.net`, see #1127.
