### ISSUE TITLE
Please allow wildcards in the action list

### ISSUE THREAD

**Issue by ItStillDoesNotWork** [EFForg/privacybadger#1698] opened 2017-09-28 17:01 UTC
I'm sick of blocking every. single. damned. .ru domain.  Why can't I just blackhole Russia - *.ru - and be done with it?

**Comment by ghostwords** [comment] 2017-09-28 18:03
Would you say this is a duplicate of #1422?

**Comment by ghostwords** [comment] 2017-10-03 01:43
Closing as a duplicate.

**Closed by ghostwords** 2017-10-03 01:43 UTC
Labels: duplicate, enhancement, ui, ux
