### ISSUE TITLE
Privacy Badger breaks binance.com

### ISSUE THREAD

**Issue by AlexIsNice** [EFForg/privacybadger#2261] opened 2019-01-02 21:30 UTC
#### What is your browser and browser version?
Chromium,71.0.3578.98
### What is broken and where?
You can not login,when privacy badger is enabled it says  Network unavailable,please refresh and try again

### What is the "culprit" domain?
`api.geetest.com`

### What is your debug output for this domain?

```
**** ACTION_MAP for geetest.com
api.geetest.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1546651827141,
  "userAction": "user_allow"
}
geetest.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
monitor.geetest.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1545615321027,
  "userAction": ""
}
static.geetest.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1547065680975,
  "userAction": ""
}
**** SNITCH_MAP for geetest.com
geetest.com [
  "axs.com",
  "binance.com",
  "nexo.io"
]
```

The site is binance.com

**Comment by AlexIsNice** [comment] 2019-01-02 21:36
Forgot to mention that If you set api.geetest.com to yellow (block cookies)it still works,so blocking it breaks it however if you have it on yellow it works.

**Comment by ghostwords** [comment] 2019-01-02 21:41
Hello and thanks for the report! Does this seem like a duplicate of #1440?

**Comment by AlexIsNice** [comment] 2019-01-03 06:40
Hello,it seems like it is yes!

Thank you very much for pointing that out i didnt see it.

Would you like me to close this issue?

**Comment by ghostwords** [comment] 2019-01-03 18:14
OK, cool. I'll close this as a duplicate. Interesting that setting to yellow works for you here but not for the original reporter in #1440.

**Closed by ghostwords** 2019-01-03 18:14 UTC
