### ISSUE TITLE
Privacy Badger menu mislocated and unscrollable on Firefox

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadger#1252] opened 2017-03-17 17:29 UTC
See this screenshot. Zooming in or out does not seem to affect the bug at all.

![badger-menu-ff](https://cloud.githubusercontent.com/assets/479213/24055174/4c013bf0-0afc-11e7-9ac4-b51f95f09283.png)

My font settings are:
Proportional: Serif, Serif: Baskerville-Regular, Sans-Serif: Sans-Serif  (all size 16)
Monospace: Inconsolata (size 20)
Allow sites to use custom fonts: yes

**Comment by ghostwords** [comment] 2017-03-17 19:15
Seems related to #1081, but that one is in Chrome.

**Comment by ghostwords** [comment] 2017-03-17 19:27
I'm having trouble reproducing ... What do you see if you [inspect the popup](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_popups) and select the "body" tag in the Inspector tab? Here is what I see after the following steps:

1) Visit `about:debugging`, check "Enable add-on debugging".
2) Click "Debug" next to Privacy Badger, click "OK".
3) Suppress popup auto-hiding in the debugger by clicking the highlighted icon in [this screenshot](https://mdn.mozillademos.org/files/13877/toolbox-popup.png).
4) Open PB's popup.
5) Select the popup in the debugger by clicking the highlighted icon in [this screenshot](https://mdn.mozillademos.org/files/13863/toolbox-iframe.png).
6) Select the "body" tag of the popup.

![screenshot from 2017-03-17 15 27 11](https://cloud.githubusercontent.com/assets/794578/24059643/3559dd1a-0b26-11e7-9c8e-3d42eff02d69.png)

**Comment by pde** [comment] 2017-03-17 21:42
OK, here are a couple of shots of what the debugger is showing there:

![debug1](https://cloud.githubusercontent.com/assets/479213/24064111/ebda961c-0b1f-11e7-8d17-1da88babb463.png)

![debug3](https://cloud.githubusercontent.com/assets/479213/24064120/f04d28d6-0b1f-11e7-905b-3fce5f34407c.png)

**Comment by pde** [comment] 2017-03-17 21:43
Another data point: I can only reproduce this with my external monitor disabled. Once I enable it, the popup seems to be in the correct location.

**Comment by ghostwords** [comment] 2017-03-17 22:04
Have you selected the popup (step 5 above) by clicking on [this icon](https://mdn.mozillademos.org/files/13863/toolbox-iframe.png) and selecting the popup in the dropdown?

**Comment by pde** [comment] 2017-03-17 23:03
I hadn't gotten that last step right. Now I see:

![debug4](https://cloud.githubusercontent.com/assets/479213/24065847/51382b0e-0b2b-11e7-8f32-b870d672dda0.png)

**Comment by ghostwords** [comment] 2017-03-17 23:14
Ah, I see that the width is a CSS `calc` function instead of `400px`. This was recently reverted (in 7022d8c3431152d96535acff887900f5df0a00ff) but not released yet I see. Could you see if changing the body's width manually to 400px in the debugger fixes it?

**Comment by pde** [comment] 2017-03-17 23:54
It doesn't seem to help. In fact when I look at the `computed` tab, the `calc` seems to have computed the width to `400px` anyway.  

Perhaps related, perhaps not: I noticed that `overflow-y` is set to `hidden`. When I delete or change that to `scroll`, I get scroll bars but they are weird (ie, for the sliders but not the whole popup) and don't actually work for seeing everything.

**Comment by pde** [comment] 2017-03-18 00:00
I can forcibly set `height` and `max-height` in the `body` element, or the surrounding `html` element, and it changes the computed layout in the debugger, but doesn't actually make the popup larger. I'm starting to suspect that this might be a browser bug...

**Comment by pde** [comment] 2017-03-18 00:01
(I'm on the FF beta channel)

**Comment by pde** [comment] 2017-03-18 00:13
Hmmm, I've tried reproducing this in another profile, and I can't, even when matching extensions, theme, and font settings :/

I have consistent reproduction in my main profile.

**Comment by ghostwords** [comment] 2018-08-28 19:45
I'm going to close this for now as this seems like a Firefox bug and we've had many Firefox releases since this was filed. Let me know if this is still an issue.

**Closed by ghostwords** 2018-08-28 19:45 UTC
Labels: Firefox, bug, ui
