### ISSUE TITLE
Information about Privacy Badger contains symbols in FF Linux

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1410] opened 2017-06-05 00:13 UTC
The Privacy Badger information in Swedish have unreadable symbols in Firefox for Linux. In Chrome for Linux the information have no symbols.

![skarmbild fran 2017-06-05 02-05-25](https://cloud.githubusercontent.com/assets/23194385/26766521/f5b7a15e-4993-11e7-85c4-8e03308d9ed9.png)

**Comment by ghostwords** [comment] 2017-06-05 00:53
Which version of Firefox do you have? This might be a duplicate of #1222. If so, this is a Firefox bug that you can fix by upgrading Firefox. Please see https://github.com/EFForg/privacybadger/issues/1222#issuecomment-285542771 for more information.

**Comment by jony0008** [comment] 2017-06-05 07:48
I am using Firefox 45.9.0 on Debian Stretch so it seems to be the same problem as in #1222.

**Closed** 2017-06-05 12:32 UTC
Labels: bug, Firefox, translations
