### ISSUE TITLE
Privacy Badger removes releases table from Azure Devops Releases page on Firefox Mobile

### ISSUE THREAD

**Issue by nitzanms** [EFForg/privacybadger#2365] opened 2019-05-21 12:32 UTC
Privacy Badger removes releases table from Azure Devops Releases page on Firefox Mobile

I accessed Azure Devops in a private tab, so I don't think cookies are related to the issue.

When I disabled Privacy Badger, the releases page displayed normally. See attached image for how it looks with Privacy Badger on.

![photo5989810667617628278](https://user-images.githubusercontent.com/464489/58096470-cdaa7500-7bdd-11e9-810f-cb042a8e5888.jpg)

**Comment by ghostwords** [comment] 2019-05-21 15:11
Hello!

What is the domain of the broken site?  Is this a site we could look at?

Could you go through the steps in https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain to try to figure out which domain is responsible for breakage and also why Privacy Badger learned to block it?

**Comment by ghostwords** [comment] 2019-05-21 15:14
Is the broken site `dev.azure.com`, and is the breakage caused by subdomain(s) of `visualstudio.com`?

**Comment by ghostwords** [comment] 2019-05-21 15:19
This might be a duplicate of #2347 (where the responsible domain was `vsassets.io`), in which case this will fixed in the next version of Privacy Badger.

Let me know if that's the case, or if you have any questions.

**Comment by vaindil** [comment] 2019-05-21 15:34
Yeah, the specific subdomain is `ms.gallery.vsassets.io`, so I assume the fix in #2347 will fix this too.

**Comment by ghostwords** [comment] 2019-05-23 16:31
Closing as a duplicate.

**Closed by ghostwords** 2019-05-23 16:31 UTC
Labels: MDFP, broken site, duplicate
