### ISSUE TITLE
"This extension may have been corrupted."

### ISSUE THREAD

**Issue by HalinReno** [EFForg/privacybadger#911] opened 2016-09-01 23:57 UTC
As of Chrome Version 53.0.2785.89 beta (64-bit), I am getting "This extension may have been corrupted." Repair or reinstalling extension is not working. Probably not helpful to you, but I also get this error with Https everywhere as of this version. Let me know if you need anything such as logs, etc.

Also running Antergos w/MATE 64 bit

**Comment by kirkw** [comment] 2016-09-02 02:40
I can confirm this problem on windows 7 (64 bit)
53.0.2785.89 m (64-bit)
I have tried re-install chrome, resetting hash setting.  It luanches and dies.  
I briefly see the icon in the toolbar.

**Comment by Dowwie** [comment] 2016-09-02 10:35
Can confirm for Debian 8 Jessie, as of Sept 1 2016

**Comment by thrnz** [comment] 2016-09-02 21:03
I was able to fix it by visiting the extensions page on the [chrome web store](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US) - there was a message at the top of the screen saying the extension was disabled and there was a link to re-enable it.

I found that this was also happened with HTTPS Everywhere.

**Comment by HalinReno** [comment] 2016-09-02 21:42
Thanks thrnz! Worked for me.

**Comment by diffficult** [comment] 2016-09-02 23:27
@thrnz thanks mate, that actually solved the problem. I'm running **54.0.2840.8 dev-m** and re-enabling it from the `chrome://extensions` page or reinstalling the extension didn't work.

**Comment by war59312** [comment] 2016-09-04 23:48
Confirmed. Same workaround as thrnz. Thanks. And indeed works with HTTPS Everywhere too.

Even on Chrome Dev.

**Comment by cooperq** [comment] 2016-09-10 00:04
Same issue as #901. So it turns out this is an issue in chrome, the chrome devs are aware of it and are working on a fix now. Follow the issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=643814  

For now you can fix it by uninstalling and reinstalling privayc badger, however this will cause you to loose all of your data. As soon as the chrome bug is fixed you will be able to fix the issue by hitting 'repair' without losing any data.

**Comment by lelyveld** [comment] 2016-09-11 01:02
In 53.0.2785.89, this error now manifests as a warning "Not from Chrome Web Store" on chrome://extensions.

**Comment by DaveLessnau** [comment] 2016-09-12 15:37
In the Chrome browser Version 54.0.2840.16 beta (64-bit) under Linux Mint 17.3 Cinnamon x64, I also got the "This extension may have been corrupted" error.  I uninstalled the extension and re-installed it from the Chrome Web Store.  It now shows "Not from Chrome Web Store" (though it does run).

**Comment by DaveLessnau** [comment] 2016-09-12 16:48
I'm not sure if this belongs here, but after recovering from this, do we have to worry that we've got tracking cookies on our system?  I have no idea how long I went before noticing the Privacy Badger icon wasn't at the top of my Chrome Browser window and was disabled.  Should we clear our browsing history of everything back to the beginning of time?  Or does the mere presence of a running Privacy Badger stop them from being used?

**Comment by cooperq** [comment] 2016-09-14 00:00
Sorry the "not from chrome web store" is my fault. It is related to my attempt to workaround this bug on my own, and I guess it worked to a degree. Nothing to worry about and it will be fixed in the next release. 

@DaveLessnau you shouldn't have to worry about tracking cookies on your system, privacy badger will now be blocking them as third parties. However they could still be read by a first party so you may wish to clear them anyway. Up to you.

**Comment by halleycarleton** [comment] 2016-12-14 14:26
I'm having this issue in Ubuntu 16.04, Chrome 55.0.2883.87.

No issues on Windows 10 though.

**Comment by brunoqc** [comment] 2016-12-14 14:36
I have the problem on Windows 10 with Privacy Badger 2.0. I was already using privacy badger from the Chrome Store and I got the problem when I used the update button in dev mode.

I also wasn't able to install it again from the store.

**Comment by egg-shell** [comment] 2016-12-15 18:54
Seeing this in Ubuntu-Gnome 16.04. Chrome is at 55.0.2883.87.

Windows 10 version works fine.

**Comment by alexristich** [comment] 2016-12-15 20:28
Closing this issue so as to merge with discussion in #1057.

**Closed by alexristich** 2016-12-15 20:28 UTC
