### ISSUE TITLE
Bug report privacybadger

### ISSUE THREAD

**Issue by AlyaJK** [EFForg/privacybadger#2374] opened 2019-05-28 19:02 UTC
I just had this error:
**InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.**
It's the first time i'm writing here about a problem of the extension so I don't know if this error was already signalled or not.

**Comment by ghostwords** [comment] 2019-05-28 19:18
Hello and thanks for letting us know! This has indeed already been reported, but that's OK, it helps to know that our users keep running into the problem. I'll close this as a duplicate of #2156.

Is your drive running out of space by any chance?

**Closed by ghostwords** 2019-05-28 19:18 UTC
