### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by micrarior** [EFForg/privacybadger#1744] opened 2017-10-25 08:38 UTC
I have 2 displays of different sizes and there is a bug  in small one. 
When move window to bigger it works normally. Bigger set as primary. 

![untitled_li](https://user-images.githubusercontent.com/6170034/31988593-0f4d398e-b989-11e7-9b10-60049a008a47.jpg)

Windows 10
Google Chrome 61.0.3163.100

**Comment by micrarior** [comment] 2017-10-25 09:02
Some details are found
Smaller display scaling is set to 125%
When decrease it to 100 the popup works well

**Comment by ghostwords** [comment] 2017-10-25 13:30
Is this a duplicate of #1113?

**Comment by micrarior** [comment] 2017-10-26 23:04
Not quite. Vertical scrolling is working
It is the bug with the horizontal sliders when display scalling is differs from 100%. 
On screenshot cursor is below  and to the right of the highlighted slider (adservice)

**Comment by ghostwords** [comment] 2017-10-27 15:15
Ah! Is the problem that the cursor is a hand cursor when hovering over an empty space?

We fixed up the popup's UI a bit in the recently released 2017.10.25.1 update. Could you check if this is still a problem with the latest version?

**Comment by micrarior** [comment] 2017-10-30 02:06
I have already installed 2017.10.25.1 version. The problem still persists

**Comment by ghostwords** [comment] 2017-11-28 22:29
This seems like a browser bug, perhaps one or both of these:

- [Mouse pointer issue in chrome extension while accessing it from additional monitor screen](https://bugs.chromium.org/p/chromium/issues/detail?id=667659)
- [Mouse cursor alignment wrong on extension popup window (on secondary monitor with different DPI) on Windows 10](https://bugs.chromium.org/p/chromium/issues/detail?id=659642).

**Comment by ghostwords** [comment] 2017-11-28 22:30
Can you reproduce a similar problem with other extensions?

**Comment by ghostwords** [comment] 2017-11-28 22:32
This seems related: https://github.com/andryou/scriptsafe/issues/253#issuecomment-332506440.

**Comment by ghostwords** [comment] 2017-11-30 20:07
Closing as a duplicate of #1787.

**Closed by ghostwords** 2017-11-30 20:07 UTC
Labels: bug, Chrome, ui

**Comment by ghostwords** [comment] 2018-01-25 18:41
There seems to be a workaround for this Chrome bug: https://github.com/EFForg/privacybadger/issues/1787#issuecomment-360475604
