### ISSUE TITLE
version 2017.3.28 causes Chrome CPU usage to spike to 100%

### ISSUE THREAD

**Issue by db163** [EFForg/privacybadger#1297] opened 2017-04-04 02:19 UTC
Updating to the most recent version caused Chrome to spike to 100% CPU and stay there, even with zero tabs open.

I'm using the latest version of Chrome (57.0.2987.133) on OS X Mavericks.

**Comment by ghostwords** [comment] 2017-04-04 13:34
What other extensions do you have installed?

**Comment by db163** [comment] 2017-04-04 18:46
![screen shot 2017-04-04 at 11 42 54 am](https://cloud.githubusercontent.com/assets/26888917/24673134/0d35fe22-192c-11e7-99bf-6f834edb89d6.png)

See attached for the list of active extensions. As you'll notice, Privacy Badger is running hot and pretty much the only thing that's causing Chrome's overall CPU usage. I've noticed that it also causes intermittent spikes to CPU usage from the Reddit Inbox Revamp extension... but when I disable Privacy Badger, the Reddit extension drops back down to zero CPU.

**Comment by ghostwords** [comment] 2017-04-04 18:57
My guess is that one of your other extensions does something periodically (and rapidly, to cause CPU trouble) that Badger intercepts and maybe blocks. Could you try (temporarily) disabling your extensions, one at a time, in order to find the exact conflict? Then I should be able to jump in and see what's it's all about.

**Comment by pierre4l** [comment] 2017-04-06 01:46
Looks like I'm having a similar issue, but I'm using Firefox 52 on Linux with the latest 2017.3.28. Even when displaying static webpages, the CPU usage is going potty on my old Core Duo laptop, jumping about a lot and never idling, and in turn sending the fan wild and the core temperature up to 97°C. I have 5 extensions enabled. I tried disabling each of the other 4 first since Privacy Badger was the one I suspected the least, but none of those had any effect. The instant I disable Privacy Badger the CPU goes to idle and stays there.

The last couple of days I've had some weird annoyances with sites I use regularly and which don't normally cause problems. Twitter sometimes goes braindead. There have been moments where the CPU usage stops going quite so mad, but having now disabled Privacy Badger I'm seeing the general CPU load lower than it's been in a fair while.

**Comment by db163** [comment] 2017-04-06 07:06
I followed your suggestion of sequentially disabling extensions. Eventually they were all disabled except for Privacy Badger and the CPU usage continued.

However, I then enabled all the extensions again, restarted the browser, and the problem went away. I don't have an explanation.

I'll report back if it returns, but for the past 24 hours it's been working normally.

**Comment by ghostwords** [comment] 2017-04-07 16:33
These performance issues may be caused by DNT policy rechecking (see #1303).

**Comment by terrorist96** [comment] 2017-04-12 03:58
I have the same issue.

**Comment by ghostwords** [comment] 2017-04-18 18:57
This should be fixed by #1312, which we'll try to release tomorrow.

**Comment by ghostwords** [comment] 2017-04-21 01:09
This should be fixed as of Privacy Badger version 2017.4.19.1, released yesterday. Let me know if it isn't.

**Closed by ghostwords** 2017-04-21 01:09 UTC
Labels: bug, Chrome, performance
