### ISSUE TITLE
QUOTA_BYTES quota exceeded

### ISSUE THREAD

**Issue by kamilion** [EFForg/privacybadger#1902] opened 2018-03-02 01:07 UTC
![badger](https://user-images.githubusercontent.com/412608/36878242-ddffe8b0-1d72-11e8-93c4-529cf03e8325.png)

As requested, here is your issue report.

Now, how do I make it go away?

**Comment by ghostwords** [comment] 2018-03-02 02:15
Hello! Thanks for reporting your problem. Could you run the following code in your Badger's background page and let me know what gets printed?

To get to the background page console in Chrome, visit chrome://extensions, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

Let me know if you have any questions.

This should print how much space your Badger uses:
```javascript
chrome.storage.local.get(null, r=>console.log(
  parseFloat(JSON.stringify(r).length / 1024 / 1024).toFixed(2), "MB"));
```

This should print what your most populous domains are:
```javascript
(function () {
  let action_map = badger.storage.getBadgerStorageObject('action_map').getItemClones();

  let result = _.chain(Object.keys(action_map))
    .countBy(domain => getBaseDomain(domain))
    .map((v, k) => {
      return {
        base: k,
        count: v
      };
    })
    .sortBy('count')
    .reverse()
    .slice(0, 10)
    .map(i => {
      i.domains = _.filter(Object.keys(action_map), d => d.endsWith(i.base));
      return i;
    })
    .value();

  console.log(JSON.stringify(result, null, 2));
}());
```

**Comment by kamilion** [comment] 2018-03-02 02:22
First one returns 4.91 MB,
Second one returns:
"base": "pubnub.com",
    "count": 35576,
 "base": "googlevideo.com",
    "count": 553,
"base": "disqus.com",
    "count": 549,
"base": "wordpress.com",
    "count": 179,
"base": "photobucket.com",
    "count": 158,
"base": "google.com",
    "count": 86,
"base": "alicdn.com",
    "count": 54,
"base": "akamaihd.net",
    "count": 45,
"base": "tinypic.com",
    "count": 44,
"base": "googleusercontent.com",
    "count": 32,

**Comment by ghostwords** [comment] 2018-03-02 02:37
Oh wow, I think we know what the problem is, it's `pubnub.com`. Well, it's really the combination of #888 and #1864. Well, for now, as a workaround (this problem may come back until we take care of #1864), you can run the following code in your Badger's background page to make it forget about `pubnub.com`:
```javascript
(function () {
  let am = badger.storage.getBadgerStorageObject('action_map');
  for (let domain in am.getItemClones()) {
    if (window.getBaseDomain(domain) == "pubnub.com") {
      am.deleteItem(domain);
    }
  }
}());
```
Let me know if running the code and restarting Privacy Badger (by clicking Reload on `chrome://extensions` or by restarting the browser) helps.

**Comment by kamilion** [comment] 2018-03-02 03:29
4.91MB -> 1.33MB.

Here's the dump, with the disqus and wordpress entries removed for privacy.

I am in Silicon Valley, if that helps as a georeference for the listed servers.

[pbadger.json.gz](https://github.com/EFForg/privacybadger/files/1773607/pbadger.json.gz)

**Comment by ghostwords** [comment] 2018-03-02 03:51
OK, thanks for following up! Closing this as the fix is tracked in #888. Let me know if this comes up again.

**Closed by ghostwords** 2018-03-02 03:51 UTC

**Comment by kamilion** [comment] 2018-03-02 04:03
What's the best method to whitelist the noisy-named domains cleanly?
`*.pubnub.com` on it's own line?
I can remove it in six months or a year.

**Comment by ghostwords** [comment] 2018-03-02 05:17
What do you mean by "whitelist"?

Correction to https://github.com/EFForg/privacybadger/issues/1902#issuecomment-369801931, there is a better workaround you can run in the background page that will remove all domains that shouldn't have been recorded:
```javascript
require("migrations").Migrations.forgetNontrackingDomains(badger);
```

**Comment by alwaysontheice** [comment] 2020-09-13 06:06
I just encountered this same issue except with a Google AdSense domain:  *.googlesyndication.com.  Following the above steps (but changing the domain) allowed me to remove thousands of entries.  Not sure what caused the issue in the first place.
